### PR TITLE
Remove unnecessary delete() in sync_timing.py

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request removes an unnecessary `.delete(&key)` in `sync_timing.py` and updates the tutorial accordingly.

### CODE REVIEW

**Comment by drzaeus77** [comment]
ok to test

**Comment by 4ast** [comment]
the delete() is actually necessary at the moment due to the kernel bug in the update() that was introduced in May and bugfix wasn't merged yet.
Otherwise update() will eventually fill the whole map and new updates will stop working.

**Comment by drzaeus77** [comment]
Link to bugfix?

Also, in that case, @pchaigno could you update this PR to be a comment mentioning the reason for the extra .delete().

**Comment by pchaigno** [comment]
Thanks for the explanation @4ast! 

@drzaeus77 I'm on it!

**Comment by 4ast** [comment]
> link to bugfix

https://git.kernel.org/cgit/linux/kernel/git/davem/net.git/commit/?id=a6ed3ea65d9868fdf9eff84e6fe4f666b8d14b02
it's in net tree, but not in linus tree yet.

**Comment by pchaigno** [comment]
Pull request updated!

**Pull request merged**
