### PR TITLE
Improved mallocstack

### PR DESCRIPTION
**Pull request by devidasjadhav**
1. to print information about size.
2. using perf_submit now.
3. validating segmentation fault due to missing check before stack walk.

### CODE REVIEW

**Comment by yonghong-song** [comment]
So, just check stack id before stack_traces.walk() should fix the problem, right? I would like to avoid using perf_submit(). One advantage of bpf is to do in-kernel accumulation before sending the result to user space. This example is such a use case. Could you just add stack_id checking if it fixed the issue?

**Comment by devidasjadhav** [comment]
@yonghong-song 
this was long pending pull request.
I did exactly as you suggested.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
looks good. Thanks!

**Pull request merged**
