### PR TITLE
cmake: link dynamically to libclang-cpp if found and ENABLE_LLVM_SHARED is set

### PR DESCRIPTION
**Pull request by bluca**
ENABLE_LLVM_SHARED allows to dynamically link against libLLVM, but
libclang is still unconditionally linked statically.
Search for libclang-cpp.so, and if it is found and ENABLE_LLVM_SHARED
is set dynamically link against it.
Also expand the libstdc++ static linking check to include this new
condition.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
@bluca The change looks good. I am able to build successfully with addition cmake option `-DLLVM_BUILD_LLVM_DYLIB=ON` when building llvm. I have the following libbcc.so
```
[/home/yhs/work/bcc/tools]# ldd ../build/src/cc/libbcc.so
        linux-vdso.so.1 (0x00007ffdabfc0000)
        libclang-cpp.so.12git => /home/yhs/work/llvm-project/llvm/build/install/lib/libclang-cpp.so.12git (0x00007feecca76000)
        libLLVM-12git.so => /home/yhs/work/llvm-project/llvm/build/install/lib/libLLVM-12git.so (0x00007feec87ca000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007feec85b1000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007feec821c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007feec7e9a000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007feec7c82000)
        libc.so.6 => /lib64/libc.so.6 (0x00007feec78bf000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007feec769f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007feec7497000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007feec7293000)
        /lib64/ld-linux-x86-64.so.2 (0x00007feed2e29000)
        libz.so.1 => /lib64/libz.so.1 (0x00007feec707c000)
[root@devvm1886.ftw0 /home/yhs/work/bcc/tools]#
```

When I tried to run a bcc tool, I got the following error
```
[/home/yhs/work/bcc/tools]# LD_LIBRARY_PATH=/home/yhs/work/llvm-project/llvm/build/install/lib ./profile.py 
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```
The same happens when I am trying to run an example,
```
[/home/yhs/work/bcc/build/examples/cpp]# ./HelloWorld 
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```

I have not figured out how to resolve this. Did you hit such issues during your development?

**Comment by bluca** [comment]
> @bluca The change looks good. I am able to build successfully with addition cmake option `-DLLVM_BUILD_LLVM_DYLIB=ON` when building llvm. I have the following libbcc.so
> 
> ```
> [/home/yhs/work/bcc/tools]# ldd ../build/src/cc/libbcc.so
>         linux-vdso.so.1 (0x00007ffdabfc0000)
>         libclang-cpp.so.12git => /home/yhs/work/llvm-project/llvm/build/install/lib/libclang-cpp.so.12git (0x00007feecca76000)
>         libLLVM-12git.so => /home/yhs/work/llvm-project/llvm/build/install/lib/libLLVM-12git.so (0x00007feec87ca000)
>         libelf.so.1 => /lib64/libelf.so.1 (0x00007feec85b1000)
>         libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007feec821c000)
>         libm.so.6 => /lib64/libm.so.6 (0x00007feec7e9a000)
>         libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007feec7c82000)
>         libc.so.6 => /lib64/libc.so.6 (0x00007feec78bf000)
>         libpthread.so.0 => /lib64/libpthread.so.0 (0x00007feec769f000)
>         librt.so.1 => /lib64/librt.so.1 (0x00007feec7497000)
>         libdl.so.2 => /lib64/libdl.so.2 (0x00007feec7293000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007feed2e29000)
>         libz.so.1 => /lib64/libz.so.1 (0x00007feec707c000)
> [root@devvm1886.ftw0 /home/yhs/work/bcc/tools]#
> ```
> 
> When I tried to run a bcc tool, I got the following error
> 
> ```
> [/home/yhs/work/bcc/tools]# LD_LIBRARY_PATH=/home/yhs/work/llvm-project/llvm/build/install/lib ./profile.py 
> : CommandLine Error: Option 'use-dbg-addr' registered more than once!
> LLVM ERROR: inconsistency in registered CommandLine options
> Aborted (core dumped)
> ```
> 
> The same happens when I am trying to run an example,
> 
> ```
> [/home/yhs/work/bcc/build/examples/cpp]# ./HelloWorld 
> : CommandLine Error: Option 'use-dbg-addr' registered more than once!
> LLVM ERROR: inconsistency in registered CommandLine options
> Aborted (core dumped)
> ```
> 
> I have not figured out how to resolve this. Did you hit such issues during your development?

@yonghong-song  no haven't seen that, it works fine for me. Are you sure all the relevant LD_LIBRARY_PATHs are set? It sounds like your run mixes old and new libraries, some linked statically and some dynamically? Hence the double registration. Running from the build directory, with no bpfcc installed in the system path:

```
$ sudo LD_LIBRARY_PATH=src/cc/ PYTHONPATH=src/python/bcc-python3 python3 ../tools/profile.py 
Sampling at 49 Hertz of all threads by user + kernel stack... Hit Ctrl-C to end.
^C
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    [unknown]
    g_main_context_dispatch
    -                chrome (2438)
...
$ sudo ./examples/cpp/HelloWorld 
Starting HelloWorld with BCC 0.17.0-e9f69488
     gnome-shell-2212    [001] d...  1421.963660: bpf_trace_printk: Hello, World! Here I did a sys_clone call!
$ lddtree ./examples/cpp/HelloWorld
HelloWorld => ./examples/cpp/HelloWorld (interpreter => /lib64/ld-linux-x86-64.so.2)
    libclang-cpp.so.11 => /usr/lib/llvm-11/lib/libclang-cpp.so.11
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
    libLLVM-11.so.1 => /usr/lib/llvm-11/lib/libLLVM-11.so.1
        libffi.so.7 => /usr/lib/x86_64-linux-gnu/libffi.so.7
        libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2
            libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6
        libz3.so.4 => /usr/lib/x86_64-linux-gnu/libz3.so.4
    libelf.so.1 => /usr/lib/x86_64-linux-gnu/libelf.so.1
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.
```

**Comment by yonghong-song** [comment]
@bluca I found the reason why I got error in my environment. First, I am using the following script to build llvm and clang-cpp libraries.
```
cd llvm-project/llvm/build

cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja \
    -DLLVM_ENABLE_PROJECTS="clang" \
       -DLLVM_TARGETS_TO_BUILD="BPF;X86" \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_BUILD_LLVM_DYLIB=ON \
        -DLLVM_ENABLE_ZLIB=OFF \
    -DCMAKE_INSTALL_PREFIX=$PWD/install

ninja && ninja install
```

Both libLLVM.so and libclang-cpp.so have constructors to add options to the internal data structure. In my case, the option `use-dbg-addr` will be added to system by both libclang-cpp.so and libLLVM.so and this will cause the above errors.
I hacked LLVM to skip such duplicated errors but it failed later.

In llvm-project/llvm/lib/Support/CommandLine.cpp:
```
  void addOption(Option *O, SubCommand *SC) {
    bool HadErrors = false;
    if (O->hasArgStr()) {
      // If it's a DefaultOption, check to make sure it isn't already there.
      if (O->isDefaultOption() &&
          SC->OptionsMap.find(O->ArgStr) != SC->OptionsMap.end())
        return;

      // Add argument to the argument map!
      if (!SC->OptionsMap.insert(std::make_pair(O->ArgStr, O)).second) {
        errs() << ProgramName << ": CommandLine Error: Option '" << O->ArgStr
               << "' registered more than once!\n";
        HadErrors = true;
      }
    }
```

I tried to use the above script to build llvm11 and got the same error. There must be a way to build these shared libraries properly and both libLLVM.so and libclang-cpp.so can be linked. Where did you get llvm/clang package on your system? I would like to check how they build such a package so I can mimic in my environment to make it work.

**Comment by bluca** [comment]
@yonghong-song it's from the packages from Debian testing

**Comment by bluca** [comment]
https://packages.debian.org/source/bullseye/llvm-defaults
https://sources.debian.org/src/llvm-defaults/0.51+nmu1/debian/rules/

**Comment by yonghong-song** [comment]
@bluca thanks for the pointer. I missed CLANG_LINK_CLANG_DYLIB, adding that, my locally built shared library works fine now.

**Pull request merged**
