### PR TITLE
Need support for BUILD_ID support for BPF stackmap

### PR DESCRIPTION
**Pull request by vijunag**
Added build_id support for BPF stackmap.
The scope of the changes is as below
1) Create a new stackmap with the required BUILD_ID flag. It is achieved with the help of a macro. 
2) Support for adding builds to build sym cache. A mapping is setup between build_id to resolve symbols within the file. 
3) Changes to libbcc python module to support the stack trace reported in the new format. 
4) Made sure the changes are backwards compatible. 
5) An example tool is also available in tools/stack_buildid_example.py.

### CODE REVIEW

**Comment by yonghong-song** [comment]
@vijunag This is great. Thanks for the work! 
Currently, if you go to "Files changed" tab to review the code, the multiple commits in your pull request did not merge together. For example,  I cannot find the defunition of `find_buildid()`. This is probably caused by your "Merge branch 'master' into master" commit. Could you update your pull request without a "Merge branch" commit? This will make review much easier.

Also, `stack_buildid_example.py` does not belong to tools directory, you can put it under `examples/tracing` directory. It would be good if you can add a test for the new feature. The buildid kernel support is on 4.17 and later release.

**Comment by vijunag** [comment]
@yonghong-song  - Can you please elaborate how I can merge them all into a single merge commit ?

**Comment by yonghong-song** [comment]
@vijunag I still the problem, the "Merge" commit is still in your pull request commit list. Maybe you can just squash all commits in your end into one single commit and then submit here.
https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo/31644273
It should work. If it does not, feel free to close this one and submit a new pull request.

Thanks for the changes about moving examples to examples directory. I will enable testing of this commit just to see whether everything works fine or not.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by vijunag** [comment]
That merge commit is a conflict resolution commit. I know not how I can get rid of that. Also, closing this pull request doesn't help since we end up in the same state. Please suggest an alternative. 

Btw, I added support for eBPF::APIs and cc/python test cases.

**Comment by yonghong-song** [comment]
Let me give a try later today to remove the "Merged" commit. Thanks for adding tests!

**Comment by yonghong-song** [comment]
@vijunag For conflicts, some manual resolution is needed to prevent "Merge" commits.
I manually resolved the conflicts and squashed all commits into one. I put it under
bcc repo yhs_dev2 branch `https://github.com/iovisor/bcc/tree/yhs_dev2`.
I made a few changes:
  - modified the commit subject line to make it more clear
  - added `#!/usr/bin/env python` as the shebang of `examples/tracing/stack_buildid_example.py`
  - did `chmod +x examples/tracing/stack_buildid_example.py` to that file.

You can take the code in this branch and resubmit as your pull request. I will then do a review then.
Thanks!

**Pull request closed without merging**
