### PR TITLE
Travis CI: Is it enabled?

### PR DESCRIPTION
**Pull request by cclauss**
DO NOT MERGE!

### CODE REVIEW

**Comment by cclauss** [comment]
Not enabled yet.

**Comment by drzaeus77** [comment]
Do I need to do something from the Travis admin page side once I'm logged in and have authorized the API level integration?

**Comment by drzaeus77** [comment]
Try again?

**Comment by cclauss** [comment]
Now it works.  Thanks!  https://travis-ci.org/iovisor/bcc

**Pull request closed without merging**
