### PR TITLE
tools/{cachetop,cachestat}: Introduce tracepoint writeback_dirty_{page,folio}

### PR DESCRIPTION
**Pull request by Rtoax**
Add tracepoint:writeback:writeback_dirty_{page,folio} support.

kernel commit 9fb0a7da0c52("writeback: add more tracepoints") add writeback_dirty_page tracepoint, kernel commit b9b0ff61eef5("mm/writeback: Convert tracing writeback_page_template to folios") replace writeback_dirty_page to writeback_dirty_folio.

Both folio_account_dirtied() and account_page_dirtied() are static functions and they may be gone during compilation and this may introduce some inaccuracy, when attaching kprobe fails, report the running error in time. Instead of getting incorrect statistical results.

### CODE REVIEW

**Comment by yonghong-song** [comment]
This is not right. for cachestat, the bpf function
```
int do_count(struct pt_regs *ctx) {
    struct key_t key = {};
    u64 ip;

    key.ip = PT_REGS_IP(ctx);
    counts.atomic_increment(key); // update counter
    return 0;
}
```
is for kprobe. Did you test it with tracepoints?

**Comment by yonghong-song** [comment]
With 5.12, I hit
```
$ sudo python3.6 ./cachestat.py 1 1
ioctl(PERF_EVENT_IOC_SET_BPF): Invalid argument
Traceback (most recent call last):
  File "./cachestat.py", line 114, in <module>
    b.attach_tracepoint(tp="writeback:writeback_dirty_page", fn_name="do_count")
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1040, in attach_tracepoint
    (fn_name, tp))
Exception: Failed to attach BPF program b'do_count' to tracepoint b'writeback:writeback_dirty_page'
```

**Comment by Rtoax** [comment]
> With 5.12, I hit
> 
> ```
> $ sudo python3.6 ./cachestat.py 1 1
> ioctl(PERF_EVENT_IOC_SET_BPF): Invalid argument
> Traceback (most recent call last):
>   File "./cachestat.py", line 114, in <module>
>     b.attach_tracepoint(tp="writeback:writeback_dirty_page", fn_name="do_count")
>   File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1040, in attach_tracepoint
>     (fn_name, tp))
> Exception: Failed to attach BPF program b'do_count' to tracepoint b'writeback:writeback_dirty_page'
> ```

I forgot which platform I tested on and the test was no problem at that time. I just tested again, there is indeed the problem you mentioned, let me try to solve it! Thank you for correcting.

**Comment by Rtoax** [comment]
> With 5.12, I hit
> 
> ```
> $ sudo python3.6 ./cachestat.py 1 1
> ioctl(PERF_EVENT_IOC_SET_BPF): Invalid argument
> Traceback (most recent call last):
>   File "./cachestat.py", line 114, in <module>
>     b.attach_tracepoint(tp="writeback:writeback_dirty_page", fn_name="do_count")
>   File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1040, in attach_tracepoint
>     (fn_name, tp))
> Exception: Failed to attach BPF program b'do_count' to tracepoint b'writeback:writeback_dirty_page'
> ```

Due to the introduction of tracepoint, PT_REGS_IP() can no longer be used as an index for counts, so I changed it to an enumeration NF_{APCL, MPA, MBD, APD}, so that kprobe and tracepoint can reuse the do_count() function. I tested correctly on Fedora37. (6.2.8-200.fc37.x86_64)

**Comment by Rtoax** [comment]
At the same time, the introduction of tracepoint, using ksym seems to no longer work, which may lead to wrong data, so replacing it with an enumeration is the solution.

**Pull request merged**
