### PR TITLE
add instructions for installing on Amazon Linux from source

### PR DESCRIPTION
**Pull request by tekumara**

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
tested twice, fc27 has a jenkins failure. it should be a test infra issue. Will try again tomorrow to see whether the problem still exists.
At the same, I see the installation instruction tries to get llvm 3.7.1. it works but i wonder whether you can try with a later version of llvm (e.g., llvm 6.0.1)? Thanks!

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by tekumara** [comment]
@yonghong-song I did try with LLVM 6.0.0 (there wasn't a Fedora binary for 6.0.1) but got the following error when running `make` for bcc:


```
Scanning dependencies of target HelloWorld
[ 37%] Building CXX object examples/cpp/CMakeFiles/HelloWorld.dir/HelloWorld.cc.o
[ 37%] Linking CXX executable HelloWorld
../../src/cc/libbcc.a(bpf_module.cc.o): In function `ebpf::BPFModule::dump_ir(llvm::Module&)':
bpf_module.cc:(.text+0x7c2f): undefined reference to `llvm::createPrintModulePass(llvm::raw_ostream&, std::string const&, bool)'
../../src/cc/libbcc.a(bpf_module.cc.o): In function `ebpf::BPFModule::run_pass_manager(llvm::Module&)':
bpf_module.cc:(.text+0x7dc3): undefined reference to `llvm::createPrintModulePass(llvm::raw_ostream&, std::string const&, bool)'
../../src/cc/libbcc.a(bpf_module.cc.o): In function `llvm::RTDyldMemoryManager::getSymbolAddress(std::string const&)':
bpf_module.cc:(.text._ZN4llvm19RTDyldMemoryManager16getSymbolAddressERKSs[_ZN4llvm19RTDyldMemoryManager16getSymbolAddressERKSs]+0x4): undefined reference to `llvm::RTDyldMemoryManager::getSymbolAddressInProcess(std::string const&)'
../../src/cc/libbcc.a(bpf_module.cc.o): In function `llvm::RTDyldMemoryManager::findSymbol(std::string const&)':
bpf_module.cc:(.text._ZN4llvm19RTDyldMemoryManager10findSymbolERKSs[_ZN4llvm19RTDyldMemoryManager10findSymbolERKSs]+0x18): undefined reference to `llvm::RTDyldMemoryManager::getSymbolAddressInProcess(std::string const&)'
../../src/cc/libbcc.a(bpf_module.cc.o): In function `non-virtual thunk to llvm::RTDyldMemoryManager::findSymbol(std::string const&)':
bpf_module.cc:(.text._ZN4llvm19RTDyldMemoryManager10findSymbolERKSs[_ZN4llvm19RTDyldMemoryManager10findSymbolERKSs]+0x69): undefined reference to `llvm::RTDyldMemoryManager::getSymbolAddressInProcess(std::string const&)'
../../src/cc/libbcc.a(bpf_module.cc.o):(.data.rel.ro._ZTVN4ebpf15MyMemoryManagerE[_ZTVN4ebpf15MyMemoryManagerE]+0x50): undefined reference to `llvm::SectionMemoryManager::finalizeMemory(std::string*)'
../../src/cc/libbcc.a(bpf_module.cc.o):(.data.rel.ro._ZTVN4ebpf15MyMemoryManagerE[_ZTVN4ebpf15MyMemoryManagerE]+0x90): undefined reference to `llvm::RTDyldMemoryManager::getPointerToNamedFunction(std::string const&, bool)'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::BTypeVisitor::VisitBinaryOperator(clang::BinaryOperator*)':
b_frontend_action.cc:(.text+0x3fcd): undefined reference to `clang::Rewriter::getRewrittenText(clang::SourceRange) const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::BTypeVisitor::genParamIndirectAssign(clang::FunctionDecl*, std::string&, char const**)':
b_frontend_action.cc:(.text+0x4f41): undefined reference to `clang::Rewriter::getRewrittenText(clang::SourceRange) const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::BTypeVisitor::genParamDirectAssign(clang::FunctionDecl*, std::string&, char const**)':
b_frontend_action.cc:(.text+0x61a4): undefined reference to `clang::Rewriter::getRewrittenText(clang::SourceRange) const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::BTypeVisitor::VisitCallExpr(clang::CallExpr*)':
b_frontend_action.cc:(.text+0x7600): undefined reference to `clang::Rewriter::getRewrittenText(clang::SourceRange) const'
b_frontend_action.cc:(.text+0x7707): undefined reference to `clang::Rewriter::getRewrittenText(clang::SourceRange) const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o):b_frontend_action.cc:(.text+0x838d): more undefined references to `clang::Rewriter::getRewrittenText(clang::SourceRange) const' follow
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::ProbeVisitor::VisitUnaryOperator(clang::UnaryOperator*)':
b_frontend_action.cc:(.text+0xe0da): undefined reference to `clang::QualType::getAsString() const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::ProbeVisitor::VisitArraySubscriptExpr(clang::ArraySubscriptExpr*)':
b_frontend_action.cc:(.text+0xe546): undefined reference to `clang::QualType::getAsString() const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::ProbeVisitor::VisitMemberExpr(clang::MemberExpr*)':
b_frontend_action.cc:(.text+0xfaea): undefined reference to `clang::Rewriter::getRewrittenText(clang::SourceRange) const'
b_frontend_action.cc:(.text+0xfb0c): undefined reference to `clang::QualType::getAsString() const'
b_frontend_action.cc:(.text+0xfb43): undefined reference to `clang::QualType::getAsString() const'
../../src/cc/frontends/clang/libclang_frontend.a(b_frontend_action.cc.o): In function `ebpf::BTypeConsumer::HandleTranslationUnit(clang::ASTContext&)':
b_frontend_action.cc:(.text+0x10327): undefined reference to `clang::QualType::getAsString() const'
../../src/cc/frontends/clang/libclang_frontend.a(tp_frontend_action.cc.o): In function `ebpf::TracepointTypeVisitor::VisitFunctionDecl(clang::FunctionDecl*)':
tp_frontend_action.cc:(.text+0x17b4): undefined reference to `clang::QualType::getAsString() const'
../../src/cc/libbcc.a(bcc_debug.cc.o): In function `ebpf::SourceDebugger::dump()':
bcc_debug.cc:(.text+0x802): undefined reference to `llvm::TargetRegistry::lookupTarget(std::string const&, std::string&)'
../../src/cc/libbcc.a(json_map_decl_visitor.cc.o): In function `ebpf::BMapDeclVisitor::genJSONForField(clang::FieldDecl*)':
json_map_decl_visitor.cc:(.text+0x47c): undefined reference to `llvm::APInt::toString(unsigned int, bool) const'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/cpp/HelloWorld] Error 1
make[1]: *** [examples/cpp/CMakeFiles/HelloWorld.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by yonghong-song** [comment]
From:
../../src/cc/libbcc.a(bpf_module.cc.o): In function `ebpf::BPFModule::dump_ir(llvm::Module&)':
bpf_module.cc:(.text+0x7c2f): undefined reference to `llvm::createPrintModulePass(llvm::raw_ostream&, std::string con...
It looks like some package is missing...

But since you can build from source, I think it is okay for now. Thanks!

**Pull request merged**
