### PR TITLE
docs: add latest eBPF helpers to features list

### PR DESCRIPTION
**Pull request by qmonnet**
I'm maybe a bit behind for generic BPF features in the list, but at least we're in sync for helpers. This commit adds the four helpers merged to the kernel those last days.

### CODE REVIEW

**Comment by brendangregg** [comment]
[buildbot, ok to test]

**Comment by brendangregg** [comment]
thanks

**Comment by yonghong-song** [comment]
@qmonnet We have a script check-helpers.sh to keep helper definitions consistent across bcc code base.
```
-bash-4.2$ ./scripts/check-helpers.sh 
The lists of helpers in src/cc/libbpf.c and docs/kernel-versions.md differ:
25,28d24
< msg_apply_bytes
< msg_cork_bytes
< msg_pull_data
< msg_redirect_map

The lists of helpers in docs/kernel-versions.md and src/cc/compat/linux/bpf.h differ:
25,28d24
< msg_apply_bytes
< msg_cork_bytes
< msg_pull_data
< msg_redirect_map

-bash-4.2$ 
```

The helpers also need to be defined in src/cc/libbpf.c and src/cc/compat/linux/{bpf.h, virtual_bpf.h}.
Could you help definitions to these places as well?
Thanks!

**Comment by qmonnet** [comment]
Done as PR #1645.

By the way, `./scripts/check-helpers.sh` does not check `src/cc/compat/linux/virtual_bpf.h`, maybe this should be fixed?
/cc @pchaigno

**Comment by pchaigno** [comment]
Missed that; fixed in #1646. Thanks @qmonnet!

**Pull request merged**
