### PR TITLE
opensnoop: -d option for duration

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
Looks like `-d` starts to appear in more and more tools. Maybe it is worthwhile to standardize this option to all tools (even including trace.py, argdist.py, etc.)?

**Comment by yonghong-song** [comment]
cc @brendangregg  @goldshtn

**Comment by brendangregg** [comment]
Yes, we'll likely add a "-d duration_secs" to more tools that don't already have a duration, as it's useful for scripting.

Note that this code only works because b.kprobe_poll() doesn't sleep, but we might want to change that to a 100 ms default. See #1033. In this case, having a 100 ms rounding error on the sleep duration shouldn't be a big problem.

**Pull request merged**
