### PR TITLE
man/bps: Add a man page for introspection/bps.c

### PR DESCRIPTION
**Pull request by iamkafai**
This patch adds a man page for bps.c and also introduces
bps in README.md

Signed-off-by: Martin KaFai Lau <kafai@fb.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by iamkafai** [comment]
Fix an indentation issue in bps_example.txt.  Please kick buildbot again.

**Comment by yonghong-song** [comment]
cc @brendangregg  @goldshtn

**Comment by goldshtn** [comment]
LGTM! Thanks.

**Pull request merged**
