### PR TITLE
Fix unsiggned typo introduced in commit 7c489469

### PR DESCRIPTION
**Pull request by myllynen**

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Comment by drzaeus77** [comment]
The '...ok to test' command is slightly different, if you want to kick a build off I would use '..test this please' instead.

**Comment by yonghong-song** [comment]
@drzaeus77 Thanks. Will use `test this please` later.

**Pull request merged**
