### PR TITLE
inject: add option to limit number of overrides

### PR DESCRIPTION
**Pull request by vianpl**
Signed-off-by: Nicolas Saenz Julienne <nsaenzjulienne@suse.de>

### CODE REVIEW

**Comment by vianpl** [comment]
I've been using the inject tool to test USB devices error recovery after GFP_ATOMIC alloc failures (pretty much any USB device is affected by that). I need to limit the number of errors injected to actually test if they get back to normal operation. 
An example that injects 100 consecutive errors on the usb device located at  bus 1: dev 2) :
```
sudo ./inject kmalloc -v  -c 100 -P 1 -I linux/usb.h "(true)
=> usb_submit_urb(struct urb *urb, gfp_t mem_flags)(mem_flags == GFP_ATOMIC && urb->dev->bus->busnum == 1 && urb->dev->devnum == 2)
"
```

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Could you change thee man page since a new option is added?

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
