### PR TITLE
Fix bytes<->str mixing in python3.

### PR DESCRIPTION
**Pull request by r4f4**
I tried to fix all the tools I could execute and check the output.

These are the tools missing from this patch: mysql_qslower, btr*, solisten, oomkill, ucalls, uflow, ugc, uthreads, xfs*, zfs*.

I'll open an issue for ucalls, uflow, ugc and uthreads soon, since my fix attempt breaks the internal library finding procedure and I can't figure out why.

### CODE REVIEW

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Comment by goldshtn** [comment]
@r4f4 Can you please rebase and force-push so we can get this merged?

**Comment by goldshtn** [comment]
@r4f4 Can you please take a look at the build failure and also rebase this so we can get this merged?

**Comment by r4f4** [comment]
Sure, I'm looking into it.

**Comment by goldshtn** [comment]
Thanks very for much for this, I've taken the liberty of fixing up the commit message slightly. If you could follow up on the tools you said were showing some problems, it would be great.

**Comment by r4f4** [comment]
@goldshtn It seems the internal library finding is working again, so I'm sending a patch for the remaining tools.

**Comment by r4f4** [comment]
Well, never mind. The whole thing was reverted.

**Comment by goldshtn** [comment]
@r4f4 We haven't reverted this, actually. And looks like we're not going to. So -- could you look into patching the remaining tools, like you wrote above?

**Pull request merged**
