### PR TITLE
argdist, trace: Native tracepoint support

### PR DESCRIPTION
**Pull request by goldshtn**
This PR modifies argdist and trace to use the `TRACEPOINT_PROBE` infrastructure rather than the hackish kprobe-based perf functions for enabling tracepoints.

### CODE REVIEW

**Comment by goldshtn** [comment]
Rebased so it can be merged automatically. This also resolves #591.

**Comment by brendangregg** [comment]
Tested both argdist and trace, (and with -v to confirm TRACEPOINT_PROBE()), and they both work. Thanks!

**Comment by brendangregg** [comment]
I think I broke the land speed record for time from PR to test. :)

**Comment by 4ast** [comment]
should we remove old 'tracepoint' hacks? or keep them around for old kernels?
I don't think anyone really used them (or planning to use), so I'd remove.

**Comment by goldshtn** [comment]
@brendangregg Yes you did! :)

@4ast Do you mean removing the tracepoint.py and perf.py files that aren't used anymore? I think there are no references to them in any of the tools at this point.

**Comment by 4ast** [comment]
yes. so they don't accumulate dust.

**Comment by brendangregg** [comment]
can the old versions be put under tools/old?

**Comment by goldshtn** [comment]
@brendangregg I was thinking of putting them in tools/old, but that won't work if we get rid of the tracepoint.py and perf.py files. Also, it's unlikely that the old tools will actually work as the bcc module diverges going forward... So maybe it's best to just preserve them in git history.

**Comment by goldshtn** [comment]
OK, so the `Perf` class is actually used elsewhere. The `Tracepoint` class is now completely unused, so I'm removing it.

**Comment by brendangregg** [comment]
@goldshtn ok, if the tools are unlikely to work, then people's best bet is to grab an older bcc release, instead of putting them in tools/old

**Pull request merged**
