### PR TITLE
Update profile.py to use new perf support

### PR DESCRIPTION
**Pull request by brendangregg**

### CODE REVIEW

**Comment by brendangregg** [comment]
... @palmtenor made some minor llcstat docs adjustments in a commit, just letting you know.

**Comment by brendangregg** [comment]
@4ast @drzaeus77 ... I just wrote a quick blog post I can post tomorrow morning if this merges beforehand. :)

**Comment by 4ast** [comment]
I'd like @palmtenor to do a quick review before merging...

**Comment by palmtenor** [comment]
Looks good to me, thanks a lot for the documentation update:)

**Pull request merged**
