### PR TITLE
remove trailing white spaces from source code files

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
I found a lot of noise in git due to trailing white spaces in some files.

This PR removes them in .h, .c, .cc, .py and .lua files.

### CODE REVIEW

**Comment by palmtenor** [comment]
I've always been waiting for a day that we "clang-format everything"......

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Comment by 4ast** [comment]
it will create a bunch of conflicts with pending PRs, but i'm pushing it now, since trailing white spaces were annoying to me as well.
and ignoring py_brb failure.

**Comment by yonghong-song** [comment]
python test_brb does not fail in my local fc25 VM, even after I updated with latest python2-pyroute2 package.

**Pull request merged**
