### PR TITLE
Add example for new helper bpf_get_ns_current_pid_tgid() to documentation.

### PR DESCRIPTION
**Pull request by cneira**
This PR completes the work done for [PID filtering issues when running bpf script inside container ](https://github.com/iovisor/bcc/issues/1329).

- Added  bpf_get_ns_current_pid_tgid helper to developer reference documentation. 
- Added example cloning hello_perfoutput.py as hello_perfoutput_using_ns.py replacing  bpf_get_current_pid_tgid() with the new helper  bpf_get_ns_current_pid_tgid().

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Thanks!

**Comment by cneira** [comment]
> Thanks!

Would it be worth to change calls from  bpf_get_current_pid_tgid() with the new helper bpf_get_ns_current_pid_tgid() on the tools that use that helper?

**Comment by yonghong-song** [comment]
> > Thanks!
> > @yonghong-song
> > Would it be worth to change calls from  bpf_get_current_pid_tgid() with the new helper bpf_get_ns_current_pid_tgid() on the tools that use that helper?

That will be a good idea. We need to test whether the helper is available or not before using it. Also, we may want to have an option to control. We can first try one or two and see what is the best user interface. Thanks for working on this!

**Comment by cneira** [comment]
@yonghong-song 

I like that approach!, I'll work on the first approach:
- if  bpf_get_ns_current_pid_tgid()  exists then use that, if not defer to bpf_get_current_pid_tgid() helper.

Thanks for your feedback!.

**Pull request merged**
