### PR TITLE
Update oomkill.py

### PR DESCRIPTION
**Pull request by smita-koralahalli**
@yonghong-song I have copied the older oomkill file from tools/oomkill to tools/old/oomkill
And then modified the existing oomkill.py to support later kernel versions.
Please review the same and let me know!
Additionally sorry for the confusion as I'm a graduate student and this was my first pull request made.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
utuntu 16.04 py_test_tools_smoke failed. Could you add the following for the 
```
@skipUnless(kernel_version_ge(4,9), "requires kernel >= 4.9")
```
to the oomkill.py test?

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
@drzaeus77 could you take a look, jenkins error?
```
Cloning repository https://github.com/iovisor/bcc.git
ERROR: Failed to clean the workspace
java.io.IOException: Unable to delete '/home/fedora/jenkins/workspace/bcc-pr'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Pull request merged**
