### PR TITLE
tools/wakeuptime: Switch to using tracepoints if available

### PR DESCRIPTION
**Pull request by ananthmg**
wakeuptime currently uses kprobes to trace schedule(). Switch to using
tracepoints if available.

Also, in some builds, try_to_wake_up() may get optimized away causing
the script to fail altogether.

With this switch, we however see stack trace entries related to BPF too
in the end for each trace. While correct, it takes up screen real estate
for each backtrace.

    target:          InputThread
    ffffffffaf000107 secondary_startup_64_no_verify
    ffffffffb12495f1 start_kernel
    ffffffffaf10e609 cpu_startup_entry
    ffffffffaf10e40b do_idle
    ffffffffaf946849 cpuidle_enter
    ffffffffaf946577 cpuidle_enter_state
    ffffffffafc00d02 asm_sysvec_apic_timer_interrupt
    ffffffffafbbbc86 sysvec_apic_timer_interrupt
    ffffffffaf0dcc32 irq_exit_rcu
    ffffffffaf02bc47 do_softirq_own_stack
    ffffffffafc01112 asm_call_irq_on_stack
    ffffffffafe000ca __softirqentry_text_start
    ffffffffaf163a66 run_timer_softirq
    ffffffffaf1639df __run_timers.part.0
    ffffffffaf162f09 call_timer_fn
    ffffffffaf8c46c3 input_repeat_key
    ffffffffaf8c318e input_pass_values.part.0
    ffffffffaf8c2085 input_to_handler
    ffffffffaf8c9e81 evdev_events
    ffffffffaf124a1c __wake_up_common_lock
    ffffffffaf1248b0 __wake_up_common
    ffffffffaf375e49 ep_poll_callback
    ffffffffaf124a1c __wake_up_common_lock
    ffffffffaf1248b0 __wake_up_common
    ffffffffaf375e0d ep_poll_callback
    ffffffffaf124a1c __wake_up_common_lock
    ffffffffaf1248b0 __wake_up_common
    ffffffffaf124681 autoremove_wake_function
    ffffffffaf108e57 try_to_wake_up
    ffffffffaf107dcc ttwu_do_wakeup
    ffffffffaf1f48a2 bpf_trace_run1
    ffffffffc16879d3 ftrace_trampoline
    ffffffffaf1f51c9 bpf_get_stackid_raw_tp
    waker:           swapper/0
        169325

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by netedwardwu** [comment]
Hi @ananthmg ,

May I ask
1. Why should we change to use tracepoint?
2. Did you compare the result of kprobe from tracepoint? Is the same result in the same scenario?

Thanks!

**Comment by netedwardwu** [comment]
> Hi @ananthmg ,
> 
> May I ask
> 
> 1. Why should we change to use tracepoint?
> 2. Did you compare the result of kprobe from tracepoint? Is the same result in the same scenario?
> 
> Thanks!

Okay... the symbol be optimized or stripped in some builds...

Should we concern the below case that is the difference between kprobe and tracepoint?
https://elixir.bootlin.com/linux/latest/source/kernel/sched/core.c#L2854
```
	/*
	 * If we are going to wake up a thread waiting for CONDITION we
	 * need to ensure that CONDITION=1 done by the caller can not be
	 * reordered with p->state check below. This pairs with smp_store_mb()
	 * in set_current_state() that the waiting thread does.
	 */
	raw_spin_lock_irqsave(&p->pi_lock, flags);
	smp_mb__after_spinlock();
	if (!(p->state & state))
		goto unlock;

	trace_sched_waking(p);
```
Thanks

**Comment by ananthmg** [comment]
> 1. Why should we change to use tracepoint?

1. Tracepoints are generally orders of magnitude faster than kprobes since they execute in the task context. As a general rule, if data we need can be obtained using tracepoints, that should be preferred over using kprobes.
2. schedule() is a very sensitive function to probe on. See the section on detaching in the wakeuptime_example.txt. With tracepoints, that overhead will reduce considerably.
3. Tracepoints are a kind of ABI (debatable). Function names and compiler optimizations are fluid.

> 2. Did you compare the result of kprobe from tracepoint? Is the same result in the same scenario?

The output is identical, except for the few bpf entries that are new in the tracepoint case.

**Comment by ananthmg** [comment]
> https://elixir.bootlin.com/linux/latest/source/kernel/sched/core.c#L2854
> 
> ```
> 	/*
> 	 * If we are going to wake up a thread waiting for CONDITION we
> 	 * need to ensure that CONDITION=1 done by the caller can not be
> 	 * reordered with p->state check below. This pairs with smp_store_mb()
> 	 * in set_current_state() that the waiting thread does.
> 	 */
> 	raw_spin_lock_irqsave(&p->pi_lock, flags);
> 	smp_mb__after_spinlock();
> 	if (!(p->state & state))
> 		goto unlock;
> 
> 	trace_sched_waking(p);
> ```

This is the case where the task is in the process of 'waking up', but not 'woken' yet. I would wager the kprobe mechanism may contain some false positive entries of tasks that are in this state. Migrating to tracepoints solves this problem, since trace_sched_wakeup() gets called from try_to_wake_up() and ttwu_do_wakeup() after the task->state is set to RUNNING.

Incidentally, this is another reason why the tracepoint method is more accurate for this case.

**Comment by netedwardwu** [comment]
Very clear, thank you

**Comment by yonghong-song** [comment]
Agree that tracepoint is better in this case. Let us use it if available. Thanks!

**Pull request merged**
