### PR TITLE
Add cmake TARGET: uninstall

### PR DESCRIPTION
**Pull request by Rtoax**
Usage:

```bash
  $ sudo make install
  $ sudo make uninstall <<=== New Target
```

### CODE REVIEW

**Comment by yonghong-song** [comment]
Looks like some python library files are not uninstalled. Could you take a look?
```
ls /usr/lib/python3.6/site-packages/bcc
containers.py  disassembler.py  __init__.py  libbcc.py  perf.py  __pycache__  syscall.py  table.py  tcp.py  usdt.py  utils.py  version.py
```

**Comment by Rtoax** [comment]
according to `make install` print, it's seems like direct copy not install from `install` TARGET

```
copying build/lib/bcc/__init__.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/containers.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/disassembler.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/libbcc.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/perf.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/syscall.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/table.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/tcp.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/usdt.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/utils.py -> /usr/lib/python3.9/site-packages/bcc
copying build/lib/bcc/version.py -> /usr/lib/python3.9/site-packages/bcc
```

**Comment by Rtoax** [comment]
Fix it in new commit

```
diff --git a/cmake/CmakeUninstall.cmake.in b/cmake/CmakeUninstall.cmake.in
index bf4a15c0..a33a49c7 100644
--- a/cmake/CmakeUninstall.cmake.in
+++ b/cmake/CmakeUninstall.cmake.in
@@ -1,11 +1,12 @@
 # SPDX-License-Identifier: GPL-2.0-or-later
 # Copyright (C) 2022 Rong Tao
 #
-if(NOT EXISTS "@CMAKE_BINARY_DIR@/install_manifest.txt")
-  message(FATAL_ERROR "Cannot find install manifest: @CMAKE_BINARY_DIR@/install_manifest.txt")
+function(UninstallManifest manifest)
+if(NOT EXISTS "${manifest}")
+  message(FATAL_ERROR "Cannot find install manifest: ${manifest}")
 endif()
 
-file(READ "@CMAKE_BINARY_DIR@/install_manifest.txt" files)
+file(READ "${manifest}" files)
 string(REGEX REPLACE "\n" ";" files "${files}")
 foreach(file ${files})
   message(STATUS "Uninstalling $ENV{DESTDIR}${file}")
@@ -22,3 +23,7 @@ foreach(file ${files})
     message(STATUS "File $ENV{DESTDIR}${file} does not exist.")
   endif()
 endforeach()
+endfunction()
+
+UninstallManifest("@CMAKE_BINARY_DIR@/install_manifest.txt")
+UninstallManifest("@CMAKE_BINARY_DIR@/install_manifest_python_bcc.txt")
diff --git a/src/python/CMakeLists.txt b/src/python/CMakeLists.txt
index f5c40b95..939571ac 100644
--- a/src/python/CMakeLists.txt
+++ b/src/python/CMakeLists.txt
@@ -40,7 +40,7 @@ foreach(PY_CMD ${PYTHON_CMD})
   install(
     CODE "
       execute_process(
-        COMMAND ${PY_CMD} setup.py install -f ${PYTHON_FLAGS} --prefix=${CMAKE_INSTALL_PREFIX}
+        COMMAND ${PY_CMD} setup.py install -f ${PYTHON_FLAGS} --prefix=${CMAKE_INSTALL_PREFIX} --record ${CMAKE_BINARY_DIR}/install_manifest_python_bcc.txt
         WORKING_DIRECTORY ${PY_DIRECTORY})"
     COMPONENT python)
 endforeach()
```

**Comment by Rtoax** [comment]
By the way, base `cmake.in` comes from https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

**Pull request merged**
