### PR TITLE
sync bpf compat headers with latest net-next

### PR DESCRIPTION
**Pull request by yonghong-song**
Signed-off-by: Yonghong Song <yhs@fb.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
@drzaeus77 Brenden, could you help take a look? Tests did not get triggered?

**Comment by drzaeus77** [comment]
Looking into it.

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Pull request merged**
