### PR TITLE
fileslower: try probing vfs_write if __vfs_write is missing

### PR DESCRIPTION
**Pull request by markdrayton**
Older kernels don't have `__vfs_write`.  Work around this by attaching to `vfs_write` instead.

### CODE REVIEW

**Comment by 4ast** [comment]
lgtm
@brendangregg

**Comment by brendangregg** [comment]
Sure, LGTM (merge button is greyed out).

**Comment by markdrayton** [comment]
Thanks. I hit "update branch" to see if it becomes mergeable.

**Comment by brendangregg** [comment]
thanks!

**Pull request merged**
