### PR TITLE
Avoid walking all symbols for unknown address

### PR DESCRIPTION
**Pull request by palmtenor**
#1002 is an awesome fix for nested functions. However it causes that for unknown symbols, we will bascially go through the entire list of symbols, which could be bad for large binaries / perf maps.
This change fixes the issue.

cc @markdrayton @goldshtn

### CODE REVIEW

**Comment by goldshtn** [comment]
[buildbot, add to whitelist]

**Comment by goldshtn** [comment]
LGTM; @markdrayton what do you think?

**Comment by markdrayton** [comment]
Nice catch. LGTM!

**Comment by danobi** [comment]
Perhaps a bit late to the party, but will this work if a function has multiple nested functions inside? `limit > it->start + it->size` doesn't seem to work if we look backwards and see another nested function that ends before `limit`.

**Pull request merged**
