### PR TITLE
tools: filter/display using PID intead of TID

### PR DESCRIPTION
**Pull request by chenhengqi**
This PR fixes PID filtering in

* gethostlatency.py
* solisten.py
* sslsniff.py
* tcpdrop.py

For background, see #3407 .

Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>

### CODE REVIEW

**Comment by chenhengqi** [comment]
The `tcpdrop.py` not works in recent kernel. Maybe due to the `tcp_drop` function get inlined.

I wonder if there are workarounds for that.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
> The `tcpdrop.py` not works in recent kernel. Maybe due to the `tcp_drop` function get inlined.
> 
> I wonder if there are workarounds for that.

Unfortunately, we don't have workaround for this if tcp_drop is completely gone due to inlining. People may be more interesting in what exactly leads to tcp drop. There is a recent commit
   https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=709c0314239992162cba26a860f04319a15860c4
will adds a new tracepoint for csum_errors. I think tcp_drop can be enhanced to utilize this tracepoint to list drops (kfree_sub's) due to csum errors.

**Comment by chenhengqi** [comment]
Thanks for the insight. Will try.

**Pull request merged**
