### PR TITLE
libbpf-tools/biosnoop: Fix run error if not support fentry

### PR DESCRIPTION
**Pull request by cuibixuan1**
Running biosnoop causes the following errors if not support fentry and btf:
        libbpf: prog 'blk_account_io_start': BPF program load failed: Invalid argument
        libbpf: prog 'blk_account_io_start': failed to load: -22
        libbpf: failed to load object 'biosnoop_bpf'
        libbpf: failed to load BPF skeleton 'biosnoop_bpf': -22
        failed to load BPF object: -22

### CODE REVIEW

**Comment by yonghong-song** [comment]
fentry is supported since 5.5. which kernel you are using? If possible, we should try to avoid adding supports for old kernels.

**Comment by cuibixuan1** [comment]
> fentry is supported since 5.5. which kernel you are using? If possible, we should try to avoid adding supports for old kernels.
Hi,
In fact, we are on Android 13 and Android 14 platforms, with aarch64 architecture. The kernel versions mainly include Linux 5.10, Linux 5.15 and Linux 6.1. Android has not yet enabled -mfentry (for higher performance), and currently only supports btf and kprobe.
So hope bcc can be supported in mainstream Android versions.

Thanks

**Comment by cuibixuan1** [comment]
> fentry is supported since 5.5. which kernel you are using? If possible, we should try to avoid adding supports for old kernels.


In fact, we are on Android 13 and Android 14 platforms, with aarch64 architecture. The kernel versions mainly include Linux 5.10, Linux 5.15 and Linux 6.1. Android has not yet enabled -mfentry (for higher performance), and currently only supports btf and kprobe.
So hope bcc can be supported in mainstream Android versions.

Thanks

**Comment by cuibixuan1** [comment]
> fentry is supported since 5.5. which kernel you are using? If possible, we should try to avoid adding supports for old kernels.

In fact, we are on Android 13 and Android 14 platforms, with aarch64 architecture. The kernel versions mainly include Linux 5.10, Linux 5.15 and Linux 6.1. Android has not yet enabled -mfentry (for higher performance), and currently only supports btf and kprobe.
So hope bcc support fentry and kprobe both for mainstream Android versions.

Thanks

**Comment by cuibixuan1** [comment]
> fentry is supported since 5.5. which kernel you are using? If possible, we should try to avoid adding supports for old kernels.

In fact, we are on Android 13 and Android 14 platforms, with aarch64 architecture. The kernel versions mainly include Linux 5.10, Linux 5.15 and Linux 6.1. Android has not yet enabled -mfentry (for higher performance), and currently only supports btf and kprobe.

Thanks

**Pull request closed without merging**
