### PR TITLE
Add install target to libbpf-tools

### PR DESCRIPTION
**Pull request by olsajiri**
We plan to put those tools in separate rpm, so we need a way to install them.

Adding install target with standard DESTDIR and prefix make variables.

### CODE REVIEW

**Comment by olsajiri** [comment]
We'd like to have these tools available in package due to
their small dependencies.

Also I'd like to start the discussion about packaging these
tools. I made test rpms that looks like:

        $ rpm -ql bcc-libbpf-tools
        /usr/bin/biolatency
        /usr/bin/biopattern
        /usr/bin/biosnoop
        /usr/bin/biostacks
        /usr/bin/bitesize
        /usr/bin/cpudist
        /usr/bin/drsnoop
        /usr/bin/execsnoop
        /usr/bin/filelife
        /usr/bin/hardirqs
        /usr/bin/llcstat
        /usr/bin/numamove
        /usr/bin/opensnoop
        /usr/bin/readahead
        /usr/bin/runqlat
        /usr/bin/runqlen
        /usr/bin/runqslower
        /usr/bin/softirqs
        /usr/bin/syscount
        /usr/bin/tcpconnect
        /usr/bin/tcpconnlat
        /usr/bin/vfsstat
        /usr/bin/xfsslower
        /usr/lib/.build-id
        /usr/lib/.build-id/0c
        ...

Would you guys agree or propose another location?

thanks,
jirka

**Comment by anakryiko** [comment]
Changes look good to me. As for the location, I don't have much of an opinion, tbh :)

**Review by anakryiko — APPROVED** [review]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by vt-alt** [comment]
@olsajiri For ALT Linux I wanted to create a package named `libbpf-tools` with binaries installed into `/usr/bin` each tool with `bpf-` prefix. What do you think?

Example _temporary_ rpm build (not yet committed to the repository): http://git.altlinux.org/tasks/265490/build/400/x86_64/rpms/libbpf-tools-0.18.0-alt2.x86_64.rpm

Why not 'bcc-` prefix for a package name? I think these tools aren't bcc specific, but libbpf specific,. they just located in `bcc` source tree (like gdb is located in binutils tree, but it's a different thing).

About binaries names, I thought, that no prefix would be confusing since there is already `execsnoop` in bcc-tools (different tool!), execsnoop in perf-tools, and execsnoop in bpftrace.

**Comment by anakryiko** [comment]
@olsajiri, @vt-alt, @mika A friendly ping. All of you expressed desire to package libbpf-tools. It would be great if you managed to do it in a consistent manner. :)

**Comment by vt-alt** [comment]
JFYI. I already packaged it for ALT like this: https://altlinux.pkgs.org/sisyphus/classic-x86_64/libbpf-tools-0.18.0-alt2.x86_64.rpm.html (Changelog date does not reflect that package is committed 13 Feb.)

**Comment by mika** [comment]
Hi!

(Cc-ing Vasudev, we're talking about https://github.com/iovisor/bcc/pull/3263 :))

* Andrii Nakryiko [Sun Mar 07, 2021 at 09:54:51PM -0800]:

> @olsajiri, @vt-alt, @mika A friendly ping. All of you expressed
> desire to package libbpf-tools. It would be great if you managed
> to do it in a consistent manner. :)

Thanks for the friendly ping! Vasudev thankfully showed up at
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978727#20
and seems to be working on libbpf-tools in Debian, so including him
in the loop. :)

regards
-mika-

**Comment by mika** [comment]
Also adding Ritesh who is also my co-maintainer of bcc package in Debian
to the loop.

Michael Prokop ***@***.***> writes:

> Hi!
>
> (Cc-ing Vasudev, we're talking about https://github.com/iovisor/bcc/pull/3263 :))
>
> * Andrii Nakryiko [Sun Mar 07, 2021 at 09:54:51PM -0800]:
>
>> @olsajiri, @vt-alt, @mika A friendly ping. All of you expressed
>> desire to package libbpf-tools. It would be great if you managed
>> to do it in a consistent manner. :)
>
> Thanks for the friendly ping! Vasudev thankfully showed up at
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978727#20
> and seems to be working on libbpf-tools in Debian, so including him
> in the loop. :)

Thanks for looping me in. If every other distro has agreed on to using
bpf- prefix to the tool name I think we can do the same in Debian.

PS: As of now tools shipped by bcc are named bpfcc-tools and all tools have
-bpfcc suffix (bcc name was taken already by some unrelated package).

Same set of tools provided by bpftrace has suffix .bt and -perf suffix
for perf-tools-unstable package.

Cheers,
Vasudev

**Comment by anakryiko** [comment]
> Cheers, Vasudev

Super confusing seeing replies from two people under the same account... Do you guys share the same computer? :)

Regarding the rest, I think `bpf-` prefix makes sense and it would be great for all distros to stick to the same convention. I hope everyone else will agree as well. Thanks!

**Comment by olsajiri** [comment]
hi,
sorry for late reply

I did not push the package yet for fedora/rhel, because I was waiting for new bcc release,
that would contain this patch, so I dont need to patch it ;-)

> @olsajiri For ALT Linux I wanted to create a package named `libbpf-tools` with binaries installed into `/usr/bin` each tool with `bpf-` prefix. What do you think?
> 
> Example _temporary_ rpm build (not yet committed to the repository): http://git.altlinux.org/tasks/265490/build/400/x86_64/rpms/libbpf-tools-0.18.0-alt2.x86_64.rpm
> 
> Why not 'bcc-`prefix for a package name? I think these tools aren't bcc specific, but libbpf specific,. they just located in`bcc` source tree (like gdb is located in binutils tree, but it's a different thing).

assuming libbpf will not come up with its own tools ;-) @anakryiko ?

makes sense, I'll check with bcc maintainer, but I think we could go with libbpf-tools

> 
> About binaries names, I thought, that no prefix would be confusing since there is already `execsnoop` in bcc-tools (different tool!), execsnoop in perf-tools, and execsnoop in bpftrace.

sounds good to me.. also easy for user to type bpf- and tab completion will do the job

thanks,
jirka

**Comment by anakryiko** [comment]
> 
> assuming libbpf will not come up with its own tools ;-) @anakryiko ?

no, of course.

> > About binaries names, I thought, that no prefix would be confusing since there is already `execsnoop` in bcc-tools (different tool!), execsnoop in perf-tools, and execsnoop in bpftrace.
> 
> sounds good to me.. also easy for user to type bpf- and tab completion will do the job

yep, sounds like a pretty nice convenience

**Comment by anakryiko** [comment]
@mika, @vt-alt as packagers, I was wondering what you thought about https://github.com/iovisor/bcc/pull/3889 ? This should allow to package libbpf-tools on much bigger variety of distros and kernels, but I'm not sure if it's relevant to you at all. Would love to hear comments, thanks!

**Comment by mika** [comment]
Hi,

* Andrii Nakryiko [Mon Mar 28, 2022 at 09:47:43AM -0700]:

> @mika, @vt-alt as packagers, I was wondering what you thought
> about https://github.com/iovisor/bcc/pull/3889 ? This should allow
> to package libbpf-tools on much bigger variety of distros and
> kernels, but I'm not sure if it's relevant to you at all. Would
> love to hear comments, thanks!

Thanks for keeping us in the loop and reaching out, @anakryiko!

I'm here-by Cc-ing (via mail) Vasudev and Ritesh, who do the actual
packaging work in Debian. :)

(Vasudev + Ritesh, see
https://github.com/iovisor/bcc/pull/3263#issuecomment-1080896149 for
the details, sorry, I didn't know your github handles, if you should
have any)

regards
Mika

**Comment by vt-alt** [comment]
BTW, in ALT we build newer kernels (of the two main flavours) with `CONFIG_DEBUG_INFO_BTF=y`.

**Pull request merged**
