### PR TITLE
killsnoop: s/failed opens/failed kill syscalls/

### PR DESCRIPTION
**Pull request by cdown**
I think this is a bad copy/paste from opensnoop, if I'm not mistaken.

### CODE REVIEW

**Comment by cdown** [comment]
Please hold off on merging until I've got approval from legal to contribute (as trivial as this may be).

**Comment by brendangregg** [comment]
Yes, thanks. LGTM.

**Comment by brendangregg** [comment]
If you have an update branch button, can you please click it? I can't merge ATM as it is out of date.

**Comment by cdown** [comment]
I'll get back once I've got the goahead from legal (yes, this is tiny and documentation only, but...)

**Comment by cdown** [comment]
Ok, this is good to go. I've also rebased it so it should be mergeable now.

**Comment by brendangregg** [comment]
thanks!

**Pull request merged**
