### PR TITLE
[CLEANUP] BPF.cc use `StatusTuple::ok()` to replace `StatusTuple::code() != 0`

### PR DESCRIPTION
**Pull request by yzhao1012**
This is part of #2697

The current plan is to carry out the changes file by file.

### CODE REVIEW

**Comment by chenhengqi** [comment]
```shell
$ grep -n -H -r -I '.code() != 0' * | awk -F: '{ print $1 }' | sort -u
examples/cpp/CGroupTest.cc
examples/cpp/CPUDistribution.cc
examples/cpp/FollyRequestContextSwitch.cc
examples/cpp/HelloWorld.cc
examples/cpp/KFuncExample.cc
examples/cpp/KModRetExample.cc
examples/cpp/LLCStat.cc
examples/cpp/pyperf/PyPerfUtil.cc
examples/cpp/RandomRead.cc
examples/cpp/RecordMySQLQuery.cc
examples/cpp/SkLocalStorageIterator.cc
examples/cpp/TaskIterator.cc
examples/cpp/TCPSendStack.cc
src/cc/api/BPF.cc
src/cc/api/BPFTable.cc
src/cc/api/BPFTable.h
src/cc/bcc_exception.h
src/cc/frontends/b/loader.cc
tests/cc/test_array_table.cc
tests/cc/test_bpf_table.cc
tests/cc/test_cg_storage.cc
tests/cc/test_hash_table.cc
tests/cc/test_map_in_map.cc
tests/cc/test_prog_table.cc
tests/cc/test_queuestack_table.cc
tests/cc/test_sk_storage.cc
tests/cc/test_sock_table.cc
tests/cc/test_usdt_probes.cc
```

There are so many files have to be touched. Can you group these changes by directory (`examples`, `src`, `tests`) ?
This way we can have a clean commit history.

**Comment by yzhao1012** [comment]
Sure let me do this, I'll create a new PR for each of the cases.

**Comment by yzhao1012** [comment]
1 quick question:
How to run tests? I noticed that there is no doc in the top or repo's readme file. And the tests/ directory doesn't have either.
I probably can figure out how to do that myself, but thought it's a better use of our time if the maintainers already know that. :)

**Comment by chenhengqi** [comment]
https://github.com/iovisor/bcc/blob/master/.github/workflows/bcc-test.yml#L64

**Pull request closed without merging**
