### PR TITLE
Making selection of kernel headers type automatic

### PR DESCRIPTION
**Pull request by dkronst**
I think this is better

### CODE REVIEW

**Comment by brendangregg** [comment]
buildbot, test this please

**Comment by brendangregg** [comment]
buildbot, test this please

**Comment by brendangregg** [comment]
buildbot, retest this please

**Comment by brendangregg** [comment]
buildbot, retest this please

**Comment by brendangregg** [comment]
sorry for all the comments; builtbot has been broken and I've been trying to fix it...

**Comment by brendangregg** [comment]
buildbot, retest this please

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Comment by 4ast** [comment]
lgtm @drzaeus77 thoughts?

**Pull request merged**
