### PR TITLE
Added the include path of luajit2.1 for the FindLuaJIT module of cmake.

### PR DESCRIPTION
**Pull request by monadbobo**
Added the default include path of luajit2.1 for the FindLuaJIT module of cmake.

### CODE REVIEW

**Comment by goldshtn** [comment]
[buildbot, add to whitelist]

**Comment by goldshtn** [comment]
[buildbot, test this please]

**Comment by goldshtn** [comment]
@drzaeus77 Not sure what's up with the build bots, could you please take a look? Complaining that the commit id is not a valid reference.

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Comment by drzaeus77** [comment]
Yeah I had noticed that before. I thought it might be related to people that were pushing back-to-back, but that is clearly not the case here. I see a difference in the console output between the two...maybe the jenkins plugin is picking a wrong variable for the commit hash somehow?

```
Fetching upstream changes from https://github.com/iovisor/bcc.git
 > git fetch --tags --progress https://github.com/iovisor/bcc.git +refs/pull/*:refs/remotes/origin/pr/*
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
Checking out Revision 34aa751eddef1a77396b77ca85bb36ace2612168 (refs/remotes/origin/pr/1120/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 34aa751eddef1a77396b77ca85bb36ace2612168
 > git rev-list d090bc6946a0c13e7c61b2bbc21e508856dc3e2e # timeout=10
```

```
Fetching upstream changes from https://github.com/iovisor/bcc.git
 > git fetch --tags --progress https://github.com/iovisor/bcc.git +refs/pull/*:refs/remotes/origin/pr/*
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
Checking out Revision d090bc6946a0c13e7c61b2bbc21e508856dc3e2e (refs/remotes/origin/pr/1120/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d090bc6946a0c13e7c61b2bbc21e508856dc3e2e
FATAL: Could not checkout d090bc6946a0c13e7c61b2bbc21e508856dc3e2e
```

I might ping a local git expert to see what he thinks.

**Pull request merged**
