### PR TITLE
Add Perl support for ucalls / uflow / ustat

### PR DESCRIPTION
**Pull request by myllynen**
Sort language entries while at it.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by myllynen** [comment]
I don't think anything special is needed for Perl; however the reason I added them is because similar wrappers exists for other languages already, for example:

```
$ ls bcc.git/tools/python{calls,flow,stat}.sh                            
bcc.git/tools/pythoncalls.sh  bcc.git/tools/pythonflow.sh  bcc.git/tools/pythonstat.sh
```

Thanks.

**Comment by yonghong-song** [comment]
Ok, sounds good then!

**Comment by brendangregg** [comment]
The only thing I don't like is the lack of specific examples; feel free to fix this in a follow up PR. Eg:

```
ls -lh perlcalls_example.txt
lrwxr-xr-x  1 bgregg  2119906183    22B Sep  4 11:36 perlcalls_example.txt@ -> lib/ucalls_example.txt
```

That's kinda a hack. Better than nothing, but as a Perl user I'm reading an example that's actually demonstrating Java. At some point I'd delete this symlink and replace it with a real perlcalls_example.txt file of Perl examples, and the same for all the others.

**Comment by myllynen** [comment]
I agree that the it's not ideal at the moment but I was following the earlier convention with the other supported languages (Node, PHP, Python, Ruby), they all link to the generic u*txt versions:

```
$ ls -1l bcc.git/tools/*stat_example.txt
lrwxrwxrwx. 1 testuser testuser   21 2017-12-06 22:10 bcc.git/tools/javastat_example.txt -> lib/ustat_example.txt
lrwxrwxrwx. 1 testuser testuser   21 2017-12-06 22:10 bcc.git/tools/nodestat_example.txt -> lib/ustat_example.txt
lrwxrwxrwx. 1 testuser testuser   21 2018-09-04 20:40 bcc.git/tools/perlstat_example.txt -> lib/ustat_example.txt
lrwxrwxrwx. 1 testuser testuser   21 2017-12-06 22:10 bcc.git/tools/phpstat_example.txt -> lib/ustat_example.txt
lrwxrwxrwx. 1 testuser testuser   21 2017-12-06 22:10 bcc.git/tools/pythonstat_example.txt -> lib/ustat_example.txt
lrwxrwxrwx. 1 testuser testuser   21 2017-12-06 22:10 bcc.git/tools/rubystat_example.txt -> lib/ustat_example.txt
```

**Comment by myllynen** [comment]
Glad you like it! FWIW, Performance Co-Pilot (PCP, https://pcp.io) now has BCC plugin (https://github.com/performancecopilot/pcp/tree/master/src/pmdas/bcc) which supports ucalls and ustat modules so in case you'd like to leave things running in the background for a longer period of time or collect also OS/DB/etc metrics at the same time, that might be something worth considering.

**Pull request merged**
