### PR TITLE
Include bcc headers in /usr/include

### PR DESCRIPTION
**Pull request by drzaeus77**
* Add wrapper bcc.h to include dependencies
* Add text bpf_module_create_* to list of exports

Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>

### CODE REVIEW

**Comment by 4ast** [comment]
what's the point of unused bcc.h?

**Comment by drzaeus77** [comment]
I am including that one file in a separate project (fuse filesystem). Might be an unnecessary abstraction at this point.

**Comment by 4ast** [comment]
why fuse stuff cannot include 3 .h:
+#include <bcc/bpf_common.h>
+#include <linux/bpf.h>
+#include <bcc/libbpf.h>
?
single 'rule them all file' reminds me of 'windows.h' file from win32 days...

**Comment by drzaeus77** [comment]
No preference, will update. There are plenty of OSS projects which take wrapper header approach, fuse.h being one of them.

**Comment by drzaeus77** [comment]
Does this version address your comments?

**Pull request merged**
