### PR TITLE
cmake: always link to packaged libbpf if CMAKE_USE_LIBBPF_PACKAGE is set

### PR DESCRIPTION
**Pull request by bluca**
For some binaries, even if CMAKE_USE_LIBBPF_PACKAGE is set static linking is still used, breaking expectations. If the option to use the packaged version is set, it should be respected.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by bluca** [comment]
CMake's NAME_WLE was introduced in v3.14, changed to NAME_WE which is available in older releases. Let's see if this works or it needs permissions:

**Comment by bluca** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by bluca** [comment]
The build failure on the Ubuntu CIs was due to the order of linker flags being changed - on some compilers it matters. I've fix it and restored the original order - bpf-static first, then its dependencies (elf/zlib).

**Comment by bluca** [comment]
@yonghong-song gentle ping for review. We will be using these patches in the upcoming Debian 11 release (and as a consequence in the next Ubuntu release and other derivatives). TIA!

**Comment by yonghong-song** [comment]
The change looks good to me. Thanks!

**Pull request merged**
