### PR TITLE
tools/biolatpcts: Support measuring overall latencies between two events

### PR DESCRIPTION
**Pull request by htejun**
* When exit is requested through SIGINT, TERM or HUP, output the latency
  distribution one more time before exiting.

* Interpret negative interval as infinite.

Combined, this allows using biolatpcts to measure the overall latency
distribution between two events.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by htejun** [comment]
Sorry, please hold off a bit. Making one more generalization. Thanks.

**Comment by yonghong-song** [comment]
> Sorry, please hold off a bit. Making one more generalization. Thanks.

Did not see this. Could you just do a followup?

**Comment by htejun** [comment]
Will do. Thanks!

**Pull request merged**
