### PR TITLE
Handle the text and src_file the same way in the BPF constructor

### PR DESCRIPTION
**Pull request by tobiasblass**
Instead of having two different code paths for code passed in as a
string (via the text parameter) and code passed in via file (via the
src_file parameter), load the contents of src_file into the text
variable and handle both in the same code path.
This fixes issue #2385.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
How about C++ APIs? Do you think we could change clang frontends for both C++ and python?

**Comment by palmtenor** [comment]
@yonghong-song I don’t think C++ API has by-file interface

**Comment by yonghong-song** [comment]
Looks good to me. Currently, the `b` language still uses src_file. In the future, when `b` language is retired, we can remove those related codes which deal with src_file.

**Pull request merged**
