### PR TITLE
Add missing nfsdist and nfsslower to snap

### PR DESCRIPTION
**Pull request by ColinIanKing**
Signed-off-by: Colin Ian King <colin.king@canonical.com>

### CODE REVIEW

**Comment by goldshtn** [comment]
Thanks! Perhaps it might make sense to add this to the CONTRIBUTING-SCRIPTS document?

In fact, while we're at it, maybe it could be nice to have an automatic script for new tool contributions that:

- Checks spelling
- Runs lint checks
- Makes sure there's a smoke test
- Makes sure there's a man page, examples page, README entry for the tool
- Makes sure the tool is added to the snap file
- etc.

Thoughts? @brendangregg @drzaeus77

**Comment by goldshtn** [comment]
[buildbot, ok to test]

**Comment by pchaigno** [comment]
> Runs lint checks

@goldshtn There's already a [.travis.yml file](https://github.com/iovisor/bcc/blob/master/.travis.yml) to run link checks. It's just not enabled yet.

**Comment by brendangregg** [comment]
@goldshtn we could write a tool checker, but OTOH, I'm not sure how often we'd need to run it. I think once we get to about 150 tools, we may have pretty much everything we want for tackling low-hanging fruit and common problems, and additional tools would be more niche/esoteric, and can live in other locations/repositories. We have to draw the line somewhere, otherwise we're maintaining too much for too little additional value. I published over 500 different DTrace tools, and wrote more that I didn't publish, and I don't think they'd all belong in bcc. So far what I've been including is pretty generic: ext4 latency, runq latency, etc.

**Comment by goldshtn** [comment]
Sure, that makes sense.

**Pull request merged**
