### PR TITLE
Libbpf/fixes

### PR DESCRIPTION
**Pull request by olsajiri**
* Fix bpf linking if specified via LIBBPF_LIBRARIES variable
* Unite libbpf includes

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
@olsajiri  any update on this?

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by olsajiri** [comment]
hi,
is anything wrong with this one?

thanks,
jirka

**Pull request closed without merging**
