### PR TITLE
tcpstates: Add systemd journal logging.

### PR DESCRIPTION
**Pull request by geraldcombs**
Add a -Y/--journal flag to tcpstates.py, which logs events to the
systemd journal.

### CODE REVIEW

**Comment by geraldcombs** [comment]
Wireshark 3.0 will include an "sdjournal" extcap interface, which lets you capture systemd journal events alongside packets on Linux. This change lets you capture and view TCP state changes via sdjournal.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
fc28 failure is a test infra issue and should go away with retrying the test.
Could you add the new flag to the man page?

**Comment by geraldcombs** [comment]
> Could you add the new flag to the man page?

Done, along with updating tcpstates_example.txt.

**Pull request merged**
