### PR TITLE
tcp tools: finalize data type conversion

### PR DESCRIPTION
**Pull request by myllynen**
Finish the conversion started with commit 36ce1124.

Minor tweaks to make the tools consistent within themselves.

### CODE REVIEW

**Comment by myllynen** [comment]
Please double check this, I'm not 100% __builtin_memcpy() is the right choice here but it seems to work. Thanks.

**Comment by myllynen** [comment]
(Btw, after this only the *slower tools are in the need of this sort of conversion.)

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
@myllynen some of changes may be problematic. For a structure with pads, The C compiler will not initialize these pads and verifier may complain. In such cases, it is still necessary to initialize the whole structure first and then assign individual fields.

**Comment by myllynen** [comment]
@yonghong-song It would be nice to know exactly which cases could be problematic, as mentioned here such changes were to make the tools consistent within themselves, more precisely:

* tcpdrop, tcpretrans: use the same initialization with IPv4 as is already used with IPv6
* tcplife: use the same initialization with IPv6 as is already used with IPv4

Thanks.

**Comment by pchaigno** [comment]
@yonghong-song is referring to the issue documented in #269. Not all objects are initialized the same way because of that issue. If you look at the Jenkins' logs, you'll see that the tests are failing because the kernel verifier is rejecting the programs. You should be able to reproduce locally easily if you run the tools.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
There is a missing change for `tcptop.py` for ipv6 (probably you did not test it),
```
 def get_ipv6_session_key(k):
     return TCPSessionKey(pid=k.pid,
-                         laddr=inet_ntop(AF_INET6, pack("QQ", k.saddr0, k.saddr1)),
+                         laddr=inet_ntop(AF_INET6, k.saddr),
                          lport=k.lport,
-                         daddr=inet_ntop(AF_INET6, pack("QQ", k.daddr0, k.daddr1)),
+                         daddr=inet_ntop(AF_INET6, k.daddr),
                          dport=k.dport)
```
Could you add this change and resubmit?
Thanks!

**Comment by myllynen** [comment]
The current PR actually would do:

```
def get_ipv6_session_key(k):
    return TCPSessionKey(pid=k.pid,
                         laddr=inet_ntop(AF_INET6, pack("QQ", k.saddr)),
                         lport=k.lport,
                         daddr=inet_ntop(AF_INET6, pack("QQ", k.daddr)),
                         dport=k.dport)
```

Which is like for IPv4 except uses "QQ" instead of "I". If you still prefer, I'll change this to your proposal? Thanks.

**Comment by yonghong-song** [comment]
`pack("QQ", k.saddr)` probably won't work. The following is what I got:
```
Traceback (most recent call last):
  File "./tcptop.py", line 266, in <module>
    key = get_ipv6_session_key(k)
  File "./tcptop.py", line 204, in get_ipv6_session_key
    laddr=inet_ntop(AF_INET6, pack("QQ", k.saddr)),
struct.error: pack expected 2 items for packing (got 1)
```
Unfortunately, I did not see pack has an encoding letter for
16-byte integer.
Maybe just change to my proposed change is easier.

**Comment by myllynen** [comment]
Ok, I've updated the PR to match your suggestion. Thanks.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
