### PR TITLE
Explain possible reason of an error in scripts that rely on /proc/kallsyms (fixes #1391)

### LINKED ISSUE #1391: ext4slower doesn't work and the error message is not very helpful
Hi,

I would like to use ext4slower. I execute it like this:

```
sudo /usr/share/bcc/tools/ext4slower 1
```

... and it tells me:

```
ERROR: no ext4_file_operations in /proc/kallsyms. Exiting.
```

It's not very helpful since I can't understand from this error message whether I should rebuild a kernel with some additional flags or do something else. Could you please add some hint text that would explain how to make ext4slower work?

The environment is Arch Linux x64, uname -a:

```
Linux e733 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by afiskon**
An update of https://github.com/iovisor/bcc/pull/1406, fixes #1391

### CODE REVIEW

**Comment by afiskon** [comment]
cc: @yonghong-song @markdrayton

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
@drzaeus77 buildbot seems not working, could you help take a look?

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Comment by drzaeus77** [comment]
Sorry, the letsencrypt (https certificate) daemon was broken, and the certificate had expired. Fixed now.

**Comment by yonghong-song** [comment]
@drzaeus77  Thanks a lot!

**Pull request merged**
