### PR TITLE
tools/tcpstates: fix local/remote port output

### PR DESCRIPTION
**Pull request by boat0**

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
The code change looks okay. But I think this won't change end result as the original implementation should be still correct, right?

**Comment by boat0** [comment]
> The code change looks okay. But I think this won't change end result as the original implementation should be still correct, right?

The original implementation
`data4.ports = dport + ((0ULL + lport) << 32);`
has a bug here: since data4.ports is u32, lport gets lost.

**Comment by yonghong-song** [comment]
Okay, I see. Thanks!

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
