### PR TITLE
migrated biosnoop and bashreadline to use bpf_perf_event_output

### PR DESCRIPTION
**Pull request by mcaleavya**
Moved old tools to tools/old , updated man pages and added updated version of the tools.

### CODE REVIEW

**Comment by brendangregg** [comment]
LGTM, and tested (works).

I mentioned some minor things that can be done now or later. Also, a couple of commits seem to have their messages reversed.

**Comment by brendangregg** [comment]
On biosnoop I'd put a blank line before 141, and a comment on 171 (and a blank line before it). Just so the eyes can scan down and see groups of code with a high level comment.

BTW, in the future the rwflg stuff (and I did something similar in xfsslower) can be replaced with a char in the data_t.

**Comment by brendangregg** [comment]
Thanks, LGTM. (I'd merge it but I don't the right access.)

**Comment by mcaleavya** [comment]
Cheers, I am really just picking at some low hanging fruit to better understand things. I will try and get a few more done over the next week or so, as I will be mostly out of action due to our baby arriving. 

Al

**Comment by brendangregg** [comment]
Congrats Al! :)

**Comment by drzaeus77** [comment]
Nice!

**Comment by mcaleavya** [comment]
Cheers, from what I hear I will have plenty of sleepless nights!! might help me work on things and catch up with you all on IRC your time for a change :)

**Pull request merged**
