### PR TITLE
trace: trace function execution with custom format strings and filters

### PR DESCRIPTION
**Pull request by goldshtn**
See discussion on https://github.com/iovisor/bcc/issues/387.

### CODE REVIEW

**Comment by brendangregg** [comment]
I've played with this and it's pretty awesome, and I'm excited to get this in.

I'm not a github expert, but there's 50 commits, I think from previous merges? I don't know if there's a button to clean that up.

The syntax shortcuts still don't feel quite right; here's the current examples from USAGE:

```
trace ::do_sys_open
trace '::do_sys_open "%s", arg2'
trace '::sys_read (arg3 > 20000) "read %d bytes", arg3'
trace r::do_sys_return
trace ':c:open (arg2 == 42) "%s %d", arg1, arg2'
trace ':c:malloc "size = %d", arg1'
trace 'r:c:malloc (retval) "allocated = %p", retval
```

And how I was thinking they could be:

```
trace do_sys_open
trace 'do_sys_open "%s", arg2'
trace 'sys_read (arg3 > 20000) "read %d bytes", arg3'
trace r::do_sys_return
trace 'c:open (arg2 == 42) "%s %d", arg1, arg2'
trace 'c:malloc "size = %d", arg1'
trace 'r:c:malloc (retval) "allocated = %p", retval
```

Imagine teaching someone these for the first time, where you are reading them out load: "we are going to trace sys_read where arg3 is greater than 20000 and then ..." -- which maps directly to the command. That's really nice. You aren't getting tripped up by having to explain ":"s every time for the common case.

Plus I'd add a couple to the usage to show the full specification: 'p::do_sys_open' and 'p:c:open'. 'r:' can't be dropped, of course. Sorry if I wasn't clearer about that earlier.

If it is easier code-wise, the current short cut style could be retained as well (just dropping the 'p'):

```
trace ::do_sys_open
trace :c:open
```

**Comment by goldshtn** [comment]
Yeah, forgot to update the examples. The shorter syntax should just work. Also, I see the commit storm -- not sure how that happened. Will try to clean up or just do a new branch and apply these changes in one go, for a new PR.

**Comment by drzaeus77** [comment]
To clean up the commits, you can do a rebase -i and squash locally then
force push to the same branch, github will update the pr appropriately.

**Comment by goldshtn** [comment]
Yeah, I kind of got into a git mess and decided to use read-tree instead into a new branch. Closing this, please see #409.

**Pull request closed without merging**
