### PR TITLE
offwaketime: make sure to catch Ctrl-C

### PR DESCRIPTION
**Pull request by r4f4**
Otherwise the tool never stops running until you SIGKILL it.

### CODE REVIEW

**Comment by brendangregg** [comment]
I'm fine with the change, but I haven't had that problem where Ctrl-C didn't work.

Just because I'm looking at it.. I wonder if my comment is wrong, and that it's printing the extra newline for non-folded output. And offwaketime.py should be chmod 755.

**Comment by vitalyvch** [comment]
Hmmm, maybe we should do it in signal handler?

**Comment by goldshtn** [comment]
@r4f4 @brendangregg What do we need to move forward on this?

**Comment by goldshtn** [comment]
I'm closing for now, please feel free to reopen if there's any progress to be made.

**Pull request closed without merging**
