### PR TITLE
syncsnoop migrated to use bpf_perf_events

### PR DESCRIPTION
**Pull request by mcaleavya**
I have added in a strcpy to copy in the Sync() text, I am thinking it might be best to just print this from python. Thoughts?

Al

### CODE REVIEW

**Comment by brendangregg** [comment]
Yeah, I'd just print that from Python. Missed a " " too. ;)

**Comment by mcaleavya** [comment]
I forgot to remove the string.h include, doing so now and will push.

**Comment by brendangregg** [comment]
Sorry, I'd also combine a couple of lines:

```
data.ts = bpf_ktime_get_ns() / 1000;
````

Rest is good.

**Comment by mcaleavya** [comment]
done , going through checks now

**Comment by brendangregg** [comment]
thanks

**Pull request merged**
