### PR TITLE
offwaketime: update with get_stackid fixes #437

### LINKED ISSUE #437: offwaketime userspace stack
Would it be possible to get the userspace stack? 
eg. I can't see where these calls are coming from in the java runtime. 

```
    waker:           java
    ffffffff8181c832 entry_SYSCALL_64_fastpath
    ffffffff81101861 sys_futex
    ffffffff8110162e do_futex
    ffffffff810ffa2c futex_wake_op
    -                -
    ffffffff81818755 schedule
    ffffffff810fe902 futex_wait_queue_me
    ffffffff810fec16 futex_wait
    ffffffff81101400 do_futex
    ffffffff81101861 sys_futex
    ffffffff8181c832 entry_SYSCALL_64_fastpath
    target:          java
        19974615
```

### PR DESCRIPTION
**Pull request by ceeaspb**
Update for userspace stacks plus various changes from offcputime.
Some minor tweaks to feedback to offcputime.
Tested on an ubuntu virtualbox VM. I see lots of incomplete/corrupted/unreportable stacks which may need further investigation/checks.

### CODE REVIEW

**Comment by 4ast** [comment]
lgtm. Thanks for converting to get_stackid.
cc @brendangregg

**Comment by brendangregg** [comment]
G'Day Alex, thanks for the fixes. Here's a few comments:

- -k and -u options error, I think a copy-n-paste error:

```
# ./offwaketime.py -k 
/virtual/main.c:35:11: error: use of undeclared identifier 'prev'
    if (!(prev->flags & PF_KTHREAD)) {
          ^
1 error generated.
Traceback (most recent call last):
  File "./offwaketime.py", line 243, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 240, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

I'd rename the "prev" to "p".

- wakeup stacks should be reversed

eg, a -f folded stack from the original:

```
migration/1;ret_from_fork;kthread;smpboot_thread_fn;schedule;-;cpu_stop_queue_work;stop_one_cpu;sched_exec;do_execveat_common.isra.37;SyS_execve;do_syscall_64;return_from_SYSCALL_64;;bash 4019115
```

the update (note the wakeup stack):

```
migration/1;ret_from_fork;kthread;smpboot_thread_fn;schedule;-;return_from_SYSCALL_64;do_syscall_64;SyS_execve;do_execveat_common.isra.37;sched_exec;stop_one_cpu;cpu_stop_queue_work;bash 951169
```

I have it explained in http://www.brendangregg.com/blog/2016-02-01/linux-wakeup-offwake-profiling.html , with a legend http://www.brendangregg.com/blog/images/2016/offwaketime-legend.png . It's nice to reverse the waker stacks, as then you have this meeting in the middle of the function that woke up the other function, making it easier to read.

- The missing stacks warning

```
# ./offwaketime -f
[...]
WARNING: 315 stack traces could not be displayed.
```

It's this:

```
    if (not args.user_stacks_only and (k.w_k_stack_id < 0 or k.t_k_stack_id < 0) or \
            (not args.kernel_stacks_only and (k.w_u_stack_id < 0 or k.t_u_stack_id < 0) and
                 (k.w_u_stack_id != -errno.EFAULT or k.t_u_stack_id != -errno.EFAULT))):
[...]
        continue
```

The warning seems alarming, but what is this really? Did we catch a schedule but miss the wakeup stack, just due to when the script was executed? I didn't exclude these in the original version.

I get the ENOMEM warning, that's good to have as is. But I'm wondering what's causing this other one. Maybe you shouldn't exclude them for now, and let null stacks be included in the output -- given one half (the waker or the target) it might help us debug what happened.

- Info message:

```
# ./offwaketime.py -U
Tracing blocked time (us) by kernel off-CPU and waker stack... Hit Ctrl-C to end.
```

That should say "user..." not "kernel...".

- Both stacks?

With -U and -K, and the default output (-K), I have to wonder: how can we trace both user and kernel? add a -B for both? or make both the default? ... Is this too messy?

I think the default output should be both (similar to profile.py's default), and -U and -K can be used as needed. The only reason offwaketime didn't already do both to start with was limits with the unrolling loop hack.

Having both stacks will also create a delimiter problem. I'd suggest using "-" for the user/kernel delimiter, and then changing it so that "--" is used for the target/waker delimiter. I can update flamegraph.pl to recognize this change.

- Some pep8 style errors (these break some builds):

```
# pep8 --show-source --ignore=E123,E125,E126,E127,E128,E302 offwaketime.py 
offwaketime.py:275:80: E501 line too long (85 > 79 characters)
    if (not args.user_stacks_only and (k.w_k_stack_id < 0 or k.t_k_stack_id < 0) or \
                                                                               ^
offwaketime.py:275:85: E502 the backslash is redundant between brackets
    if (not args.user_stacks_only and (k.w_k_stack_id < 0 or k.t_k_stack_id < 0) or \
                                                                                    ^
offwaketime.py:276:80: E501 line too long (91 > 79 characters)
            (not args.kernel_stacks_only and (k.w_u_stack_id < 0 or k.t_u_stack_id < 0) and
                                                                               ^
offwaketime.py:277:80: E501 line too long (88 > 79 characters)
                 (k.w_u_stack_id != -errno.EFAULT or k.t_u_stack_id != -errno.EFAULT))):
                                                                               ^
offwaketime.py:300:80: E501 line too long (82 > 79 characters)
            [b.ksym(addr) for addr in reversed(list(target_kernel_stack)[1:])] + \
                                                                               ^
offwaketime.py:302:80: E501 line too long (87 > 79 characters)
            [b.sym(addr, k.tgid) for addr in reversed(list(target_user_stack)[1:])] + \
                                                                               ^
offwaketime.py:314:18: E211 whitespace before '('
            print ("    %016x %s" % (addr, b.sym(addr, k.tgid)))
                 ^
```

- USAGE message says "offcputime" instead of "offwaketime".

- Man page should mention new switches.

**Comment by ceeaspb** [comment]
Thanks Brendan for the review comments! I'll work through them.

**Comment by ceeaspb** [comment]
@brendangregg I have gone through the comments.
Delimiters may need more work for when there are missing parts of the stack. I left it for feedback.
I am not sure about style checking for the man page.

The only query I had on your comments was around both stacks. I think it was already as you wanted with the default being both?

**Comment by brendangregg** [comment]
@ceeaspb sorry, was at a conference.

This is almost perfect, thanks, just a few small things:

```patch
--- offwaketime.py.orig	2016-12-09 18:39:06.204372324 +0000
+++ offwaketime.py	2016-12-09 18:54:44.136354053 +0000
@@ -41,7 +41,7 @@
     ./offwaketime 5           # trace for 5 seconds only
     ./offwaketime -f 5        # 5 seconds, and output in folded format
     ./offwaketime -m 1000     # trace only events that last more than 1000 usec
-    ./offwaketime -M 10000    # trace only events that last less than 10000 usec
+    ./offwaketime -M 9000     # trace only events that last less than 9000 usec
     ./offwaketime -p 185      # only trace threads for PID 185
     ./offwaketime -t 188      # only trace thread 188
     ./offwaketime -u          # only trace user threads (no kernel)
@@ -69,6 +69,8 @@
     help="show stacks from user space only (no kernel space stacks)")
 stack_group.add_argument("-K", "--kernel-stacks-only", action="store_true",
     help="show stacks from kernel space only (no user space stacks)")
+parser.add_argument("-d", "--delimited", action="store_true",
+    help="insert delimiter between kernel/user stacks")
 parser.add_argument("-f", "--folded", action="store_true",
     help="output folded format")
 parser.add_argument("--stack-storage-size", default=1024,
@@ -245,7 +247,7 @@
 
 # header
 if not folded:
-    print("Tracing blocked time (us) by %s off-CPU and waker stack",
+    print("Tracing blocked time (us) by %s off-CPU and waker stack" %
         stack_context, end="")
     if duration < 99999999:
         print(" for %d secs." % duration)
@@ -290,15 +292,15 @@
             [k.target] + \
             [b.sym(addr, k.tgid)
                 for addr in reversed(list(target_user_stack)[1:])] + \
-            ["-"] + \
+            (["-"] if args.delimited else [""]) + \
             [b.ksym(addr)
                 for addr in reversed(list(target_kernel_stack)[1:])] + \
             ["--"] + \
             [b.ksym(addr)
-                for addr in reversed(list(waker_kernel_stack)[1:])] + \
-            ["-"] + \
+                for addr in reversed(list(waker_kernel_stack))] + \
+            (["-"] if args.delimited else [""]) + \
             [b.sym(addr, k.tgid)
-                for addr in reversed(list(waker_user_stack)[1:])] + \
+                for addr in reversed(list(waker_user_stack))] + \
             [k.waker]
         print("%s %d" % (";".join(line), v.value))
 
@@ -307,17 +309,19 @@
         print("    %-16s %s %s" % ("waker:", k.waker, k.t_pid))
         for addr in waker_user_stack:
             print("    %016x %s" % (addr, b.sym(addr, k.tgid)))
-        print("    -")
+        if args.delimited:
+            print("    -")
         for addr in waker_kernel_stack:
             print("    %016x %s" % (addr, b.ksym(addr)))
 
         # print waker/wakee delimiter
-        print("    %-16s %s" % ("-", "-"))
+        print("    %-16s %s" % ("--", "--"))
 
         # print default multi-line stack output
         for addr in target_kernel_stack:
             print("    %016x %s" % (addr, b.ksym(addr)))
-        print("    -")
+        if args.delimited:
+            print("    -")
         for addr in target_user_stack:
             print("    %016x %s" % (addr, b.sym(addr, k.tgid)))
         print("    %-16s %s %s" % ("target:", k.target, k.w_pid))
```

Eg, I saw you were filtering the "try_to_wakeup" frame from the stacks, but it was also dropping a frame from other stacks. I also updated the delimiter behavior.

With this patch, it LGTM.

**Comment by ceeaspb** [comment]
No problem and thanks @brendangregg 
I applied your patch, rebased and squashed the commits

**Comment by brendangregg** [comment]
thanks, LGTM.

I'm not sure if any existing offwaketime.py users need to know (@4ast), but the default behavior changes in these ways:
- default now includes user stacks. Use -K for prior behavior (kernel only).
- default delimiter between target & waker is now "--", instead of "-". ("-" is used for user/kernel delimiter, when selected with -d, as with other tools).

**Pull request merged**
