### PR TITLE
Modify trace function from generic_file_read_iter() to ext4_file_read_iter()

### PR DESCRIPTION
**Pull request by kernel-z**
The new Linux version (since form 4.10) uses ext4_file_read_iter(), And if the 'CONFIG_FS_DAX' 
 is not set ,then ext4_file_read_iter() will call generic_file_read_iter(), else it will call 
 ext4_dax_read_iter(), and trace generic_file_read_iter() will fail.

### CODE REVIEW

**Comment by kernel-z** [comment]
There are too many scripts, and will be more. 
I think one script for one function is better.
If two scripts for one function, when the kernel evolving ,it may be  need another one.

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by kernel-z** [comment]
Thank you ,@yonghong-song,@pchaigno, I have changed the code as zfsdist.py type.

**Comment by yonghong-song** [comment]
LGTM. Thanks!

**Pull request merged**
