### PR TITLE
[iovisor/bcc] trace: Incorrect symbol offsets when using build_id (#2161)

### PR DESCRIPTION
**Pull request by vijunag**
bcc_bsym_resolve API returned absolute address instead of offset from start of the function.

### CODE REVIEW

**Comment by yonghong-song** [comment]
@vijunag the majority of changes already in trunk. Could you rebase your change to the trunk and resubmit? Thanks.

**Comment by yonghong-song** [comment]
@vijunag The following is what I typically do:
  - Use git remote to add a remote branch to link to the upstream one, e.g.,
```
     git remote add upstream https://github.com/iovisor/bcc.git
     git fetch upstream
     git checkout upstream/master -b upstream
```
Periodically you need to `git pull` your upstream branch to keep it syncing with the trunk.

With the `upstream`, you can always forcefully update your forked `master` branch to be up-to-date.

Your work can then rebase on top of the latest code.

**Comment by vijunag** [comment]
@yonghong-song - Can you check once now ? Only the changes appear now.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
@sandip4n could you check whether this patch fixed the issue or not? Thanks!

**Comment by yonghong-song** [comment]
@sandip4n @vijunag thank you both!

**Pull request merged**
