### PR TITLE
dbslower and dbstat

### PR DESCRIPTION
**Pull request by goldshtn**
dbslower traces MySQL/PostgreSQL queries (similarly to mysqld_qslower, but with PostgreSQL support and some additional features). dbstat summarizes query latencies into a histogram.

/cc @brendangregg

### CODE REVIEW

**Comment by brendangregg** [comment]
I'm wondering if it would be easier for discovery/usage if we had two tools (wrappers):

- mysqld_qslower
- pgsqld_qslower

With dbstat/dbslower are moved to a tools/lib directory (or something like it), and these mysqld/pgsqld tools are either symlinks or script wrappers to tools/lib. Eg:

```
mysqld_qslower:
#!/bin/bash
lib=$(dirname)/lib
$lib/dbslower mysql "$@"
```

Scripts give a bit more flexibility in adjusting the interface as needed.

Since the mysql/pgsql tools will behave the same, they can share the same man page as well (symlinked). Not the first time multiple similar things are in one man page (eg, readv(2)).

I'd also switch the 1st positional parameter back to latency too, since it's the primary function of the tool and it would be nice to use without the -m. mysqld_qslower 10.

... could even put the u* tools in a tools/lib one day, and then tools gets javagc, pythongc, rubygc, nodegc, javacalls, pythoncalls, rubycalls, etc. Might sound crazy, but if you're a Java developer you can type "ls java*" and see all the java tools, just like you can right now with tcp*, bio*, ext4*, etc.

The u* man pages can be symlinked in a similar way. If you type "man javagc", it would say:

```
ugc(8)                      System Manager's Manual                     ugc(8)


NAME
       javagc, pythongc, rubygc, nodegc - Trace garbage collection events in high-level languages.

SYNOPSIS
       javagc [-h] [-v] [-m] pid
       pythongc [-h] [-v] [-m] pid
       rubygc [-h] [-v] [-m] pid
       nodegc [-h] [-v] [-m] pid

DESCRIPTION
       This  traces  garbage  collection events as they occur, including their
       duration and any additional information (such as  generation  collected
       or type of GC) provided by the respective language's runtime.
[...]
```

Ie, you wouldn't need to write 30 new man pages. Examples files could symlink too, with an intro to say that while example were for java only, other languages look the same. (At least initially, until someone wanted to create separate ones.)

**Comment by goldshtn** [comment]
@brendangregg 
Sounds like a plan, but I think it's best addressed separately. Let's open a separate issue for tackling the whole discoverability process, with symlinks or wrapper scripts, for all relevant tools. And in the meantime merge this. Would that work?

**Comment by goldshtn** [comment]
@4ast @drzaeus77 So the build suddenly failed on fc25 after I merely updated the README and pushed :)
Here's the build log, it looks like it can't find git (??). Can you retrigger the build please, or tell me what can be done to investigate this?

```
Building remotely on fedora25-slave-90f (fc25) in workspace /home/fedora/jenkins/workspace/bcc-pr/label/fc25
Cloning the remote Git repository
Cloning repository https://github.com/iovisor/bcc.git
 > git init /home/fedora/jenkins/workspace/bcc-pr/label/fc25 # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/fedora/jenkins/workspace/bcc-pr/label/fc25
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:663)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:464)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to fedora25-slave-90f(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1537)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:822)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor255.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy145.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1057)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Error performing command: git init /home/fedora/jenkins/workspace/bcc-pr/label/fc25
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1791)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1757)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1753)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1409)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:661)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:464)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/fedora/jenkins/workspace/bcc-pr/label/fc25"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at hudson.Proc$LocalProc.<init>(Proc.java:245)
	at hudson.Proc$LocalProc.<init>(Proc.java:214)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:846)
	at hudson.Launcher$ProcStarter.start(Launcher.java:384)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1780)
	... 15 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 20 more
```

**Comment by drzaeus77** [comment]
Still working out kinks in the on-demand jenkins...

If it fails like this again, just comment on your own PR with:
[buildbot, test this please]

**Comment by goldshtn** [comment]
It happened again after you triggered the rebuild. Let's try again:
[buildbot, test this please]

Is the "please" mandatory btw? :)

**Comment by drzaeus77** [comment]
Sigh, failed again...the nodes are sometimes not pulling the metadata when they boot for the first time, and thus not even installing basic packages...hence why the git command fails (git isn't installed).

**Comment by drzaeus77** [comment]
> Is the "please" mandatory btw? :)

Yes, I can change it, but I've already trained 4ast and brendangregg on it :)

**Comment by goldshtn** [comment]
Oh no, I love the pretense of politeness.  Can the bots reply here? Maybe something like "you need to ask nicely" or "I don't think you really want to build this, Dave".

**Comment by brendangregg** [comment]
> Oh no, I love the pretense of politeness.

You might like INTERCAL too... :) https://github.com/brendangregg/GuessingGame/blob/master/src/guess.i

**Comment by brendangregg** [comment]
@goldshtn oh, and yes, we can do a separate ticket for to mysql/pgsql wrappers, and another ticket for the the java/python/ruby/node wrappers.

**Comment by goldshtn** [comment]
@brendangregg Filed as #979, #980. Also, rebased and pushed. Can be merged now?

**Comment by brendangregg** [comment]
[buildbot, test this please]

**Pull request merged**
