### PR TITLE
tcpconnect: supported UID options 

### PR DESCRIPTION
**Pull request by takumakume**
Hi.

UID related options supported.

Specification similar to this patch that I wrote: https://github.com/iovisor/bcc/pull/2113 

- The -U option prints a UID column:
  ```sh
  # ./tcpconnect -U
  UID   PID    COMM         IP SADDR            DADDR            DPORT
  0     31333  telnet       6  ::1              ::1              23
  0     31333  telnet       4  127.0.0.1        127.0.0.1        23
  1000  31322  curl         4  127.0.0.1        127.0.0.1        80
  1000  31322  curl         6  ::1              ::1              80
  ```
- The -u option filtering UID:
  ```sh
  # ./tcpconnect -Uu 1000
  UID   PID    COMM         IP SADDR            DADDR            DPORT
  1000  31338  telnet       6  ::1              ::1              23
  1000  31338  telnet       4  127.0.0.1        127.0.0.1        23
  ```

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
The github complains there is a conflict on tools/tcpconnect.py against trunk. Could you take a look and resolve the conflicts. See the above. Maybe you can use github `resolve conflicts` in the above?

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by takumakume** [comment]
Thank you for merge!

**Pull request merged**
