### PR TITLE
Use the STL's make_unique if available

### PR DESCRIPTION
**Pull request by kylezh**
Fixes build errors with some compilers.

Signed-off-by: Kyle Zhang <kyle@smartx.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
Could you be a little specific which compiler and which platform have this build failure?

**Comment by kylezh** [comment]
@yonghong-song I have updated the commit message where I put more details about the compile errors.

**Comment by yonghong-song** [comment]
The commit message and change for `make_unique` makes sense.
I found your pull request also has changes for updated cento os installation instructions.
Is this intended for this pull request? I can merge it if it is intended.

**Comment by kylezh** [comment]
Yes, I think that is a much simpler way of installing LLVM.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
