### PR TITLE
add runqlen tool

### PR DESCRIPTION
**Pull request by brendangregg**
also adds a linear histogram

### CODE REVIEW

**Comment by brendangregg** [comment]
@4ast this is the first example of a bpf_get_current_task() from a sampling perf event. I ran into a couple of minor things that can be future feature requests:

I'm fetching the run queue length from task->se.cfs_rq->nr_running, which I don't think is ideal (cfs_rq always populated?). I'd rather something like a this_rq() or task_rq(p) BPF call: bpf_get_current_rq().

I'm also fetching the CPU from task->wake_cpu, which I'm assuming is right (seems so). Would also be nice to have a bpf_get_current_cpu(). We can get the CPU from perf_submit() for outputting records, but I was after one in BPF context to use in maps.

**Comment by 4ast** [comment]
useful tool !
as far as feature request... bpf_get_current_rq() probably won't fly, since 'struct rq' is the kernel internal data structure and scheduler folks are the biggest opponent of tracepoints. Exposing them to user space is pretty much unthinkable from their point of view, since it limits how scheduler can be changed in the future.
For 2nd part.. i'm missing how that's different from bpf_get_smp_processor_id() ?

**Comment by brendangregg** [comment]
Ah, damn, I'd missed bpf_get_smp_processor_id(), I was looking for bpf.*cpu. I'll update the tool to use it (testing first).

**Comment by brendangregg** [comment]
@4ast there's a few more scheduler tools I'd like to do. I really want a tool that shows the percent of time there were idle CPUs at the same time as tasks were queued waiting. Eg:

```
# ./runqaffinity.py -OT 1 
Sampling run queues... Hit Ctrl-C to end.

19:54:53
queued when idle: 0.00%

19:54:54
queued when idle: 0.05%

19:54:55
queued when idle: 0.01%
[...]
```

A little bit of this is ok (CPU affinity). A lot is not (Eg, an app trying to be clever and doing CPU binding, but then overloading the bound CPUs). Or just scheduler bugs.

But the BPF problem is knowing whether there's queued tasks and idle CPUs at the same time. I could setup perf sampling to only fire on one CPU, and then do unrolled loops.. but bleh.. I'm actually thinking of dumping timestamped samples to user-space and post-processing there...

**Comment by brendangregg** [comment]
Oh, I think I've figured out at least one way. Double-sampling and alternating between recording and reporting. Will cause some extra interrupts (198 Hertz instead of 99), but should still be cheap. Some pseudocode.

```
// Timer fires at 2x desired frequency. CPU 0 toggles a global variable,
// "recording", between 0 and 1. On 1 cycles, all CPUs record. On 0 cycles,
// CPU 0 post processes the previous cycle's data.

// if not recording, and not CPU 0, return
if (cpu != 0 && recording == 0)
        return;

// do record
if (recording)
        idle++ if idle
        queued++ if queued

// recorders are now done
if (cpu != 0)
        return

// end recording
if (recording)
        recording = 0
        return

// this sample was processing
if (idle && queued)
        queued_when_idle++
recording = 1
```

**Comment by 4ast** [comment]
i'm not quite following why double sampling is needed.
can do the same with normal frequency and record into alternating variables?
two global idle and two global queued variables?
they're going to be incremented with xadd, right?
could you also add a flag to the current tool to use nmi hw cycles instead of sw timer?
i think it will be more accurate. I understand you cannot really test it due to hypervisor,
but datacenter folks would prefer hw cycles due to accuracy ;)
another question: idlea means nr_running==0 ?
do you think adding direct helper like idle_cpu() will be meaningfully better?
probably not.
I was also thinking that 'this_rq' feature request can be solved by adding generic helpers like
bpf_get_per_cpu_var(var, cpu_id)
bpf_get_this_cpu_var(var)
most of the global variables like runqueue and current_task are accessible this way.
Are there any other vars that would be interesting to fetch?
Not sure how to do it safely though...

**Comment by brendangregg** [comment]
I'm not sure alternating variables works: at the same time, we'll have all CPUs updating counters, and one CPU trying to process them. If it flipped between variable sets, it could do so at slightly different times on each wakeup, and each variable set may or may not have been populated by the other CPUs yet.

With double sampling, there's a full sample cycle for the CPUs to quiesce. (I've now written the tool and it does work; man page next...)

Good point about HW cycles, thanks, I should make these tools default to HW if it's available.

> another question: idle means nr_running==0 ?

Yes. I just noticed I have a wrong code comment about that; I'll fix it in a following PR. runqlen is measuring the length beyond nr_running==1 (which is one non-idle running thread), hence a -1 in there, and other comments saying it is excluding the running thread.

There's also this in include/linux/sched.h:

```C
/**
 * is_idle_task - is the specified task an idle task?
 * @p: the task in question.
 *
 * Return: 1 if @p is an idle task. 0 otherwise.
 */
static inline bool is_idle_task(const struct task_struct *p)
{
        return p->pid == 0;
}
```

If I'm writing a tool that just needs to identify idle, I'd use that instead, since it avoids the task_struct->se->cfs_rq walk. I'm not here, since these tools have to walk that anyway to get to nr_running.

> I was also thinking that 'this_rq' feature request can be solved by adding generic helpers like
> bpf_get_per_cpu_var(var, cpu_id)
> bpf_get_this_cpu_var(var)
> most of the global variables like runqueue and current_task are accessible this way.

Accessing global variables is likely going to be a big help sooner or later, but I'll need to think of examples.

Thanks!

**Comment by brendangregg** [comment]
... RE variable set switching: I should add, a constraint here is that we need all CPU's run queue information at the same point in time, so we can reason about queues on some CPUs at the same time as idle on others. I know variable set switching works for things like counts, where the timing isn't important.

**Comment by 4ast** [comment]
having been thinking that doing queued_when_idle this way is not quite correct, since sampling is not quite applicable here. There are many scheduling events in the system and 99 hz or any other frequency != kernel HZ. Also there are no_hz setups and no_hz when idle, etc. Would it make sense to do such accounting during scheduling events instead?

**Comment by brendangregg** [comment]
It's a sampling (rough) approach, and avoids the overhead of scheduler event tracing. As with any sampler, there'll be give and take when hitting or missing short-lived events. If we can reliably sample at 99 Hz it should work.

But I think I did just hit an issue where SW samples are not firing during idle states, like you describe.

idle:

```
# ./cpuunclaimed.py 1
Sampling run queues... Hit Ctrl-C to end.

%CPU 0.00%, unclaimed idle 0.00%

%CPU 0.00%, unclaimed idle 0.00%

%CPU 0.00%, unclaimed idle 0.00%
[...]
```

Looks good.

All CPUs busy (8 hot threads, 8 CPUs):

```
# ./cpuunclaimed.py 1
Sampling run queues... Hit Ctrl-C to end.

%CPU 100.00%, unclaimed idle 0.00%

%CPU 100.00%, unclaimed idle 0.00%

%CPU 100.00%, unclaimed idle 0.00%

%CPU 99.87%, unclaimed idle 0.13%

%CPU 100.00%, unclaimed idle 0.00%
[...]
```

Looks good.

Inbalance: 8 hot threads bound to 1 CPU (via taskset), 8 CPUs, remaining 7 CPUs idle:

```
# ./cpuunclaimed.py 1
Sampling run queues... Hit Ctrl-C to end.

%CPU 12.50%, unclaimed idle 87.37%

%CPU 12.50%, unclaimed idle 87.37%

%CPU 16.42%, unclaimed idle 83.58%

%CPU 16.67%, unclaimed idle 82.83%

%CPU 19.57%, unclaimed idle 80.43%

%CPU 17.24%, unclaimed idle 82.76%

%CPU 16.84%, unclaimed idle 83.16%

%CPU 16.67%, unclaimed idle 83.33%
```

The first two lines are perfect, then it drifts. I added more columns, and I can see the number of samples decreases. Hmm...

**Comment by brendangregg** [comment]
Yes, those events aren't firing. Easy to see with "perf record -F99 -a", "perf script". Some CPUs seem to go in a power down state (C state?).

**Comment by brendangregg** [comment]
So I can just infer idle_cpu_count as cpu_count - running_cpu_count:

```
# ./cpuunclaimed.py 1
Sampling run queues... Hit Ctrl-C to end.

%CPU 12.50%, unclaimed idle 86.49%

%CPU 12.50%, unclaimed idle 87.50%

%CPU 12.50%, unclaimed idle 87.50%

%CPU 12.50%, unclaimed idle 87.50%

%CPU 12.50%, unclaimed idle 87.50%

%CPU 12.63%, unclaimed idle 87.37%

%CPU 12.50%, unclaimed idle 87.50%
[...]
```

Just need a nice way to know the CPU count (ncpu).

**Comment by brendangregg** [comment]
Do I need to call xadd explicitly from bcc/BPF? Like:

```
            if (val) xadd(val, 1);                                              
[...]
error: couldn't allocate output register for constraint 'r' at line 2150480047
```

I was looking at the output of:

```
if (val) (*val)++;
[...]
57: (79) r1 = *(u64 *)(r0 +0)
58: (07) r1 += 1
```

which doesn't look atomic.

**Comment by 4ast** [comment]
sorry. it's lock_xadd() or use __sync_fetch_and_add() directly.
see src/cc/export/helpers.h

**Comment by brendangregg** [comment]
thanks! I should put an example of this in bcc somewhere. Turns out that wasn't my bug -- I still have a race condition.

**Comment by brendangregg** [comment]
... is it expected I can't use _sync_val_compare_and_swap()?

```
LLVM ERROR: Cannot select: 0x3c50070: i64,ch = AtomicCmpSwap 0x2a62a10, 0x2785d60, 0x2b3c5f0, 0x3c4fe20<Volatile LDST8[%18]> [ORD=3] [ID=11]
  0x2785d60: i64,ch = CopyFromReg 0x2a62a10, 0x3c25198 [ORD=2] [ID=8]
    0x3c25198: i64 = Register %vreg2 [ID=1]
  0x2b3c5f0: i64,ch = CopyFromReg 0x2a62a10, 0x2b3c150 [ORD=3] [ID=9]
    0x2b3c150: i64 = Register %vreg3 [ID=2]
  0x3c4fe20: i64,ch = CopyFromReg 0x2a62a10, 0x3c259b0 [ORD=3] [ID=10]
    0x3c259b0: i64 = Register %vreg1 [ID=3]
```

Trying to implement a tie-breaker when two samples fire at exactly the same time, and I want only one to then execute some code. Also tried __atomic_compare_exchange()...

**Comment by 4ast** [comment]
correct. there is only __sync_fetch_and_add.

**Comment by brendangregg** [comment]
My work in progress so far... https://gist.github.com/brendangregg/731cf2ce54bf1f9a19d4ccd397625ad9

It works, but isn't perfect (without a way to do thread synchronization like a CAS). I might have to give up and dump samples to user space for perfection, although I don't know how much that matters, and that will cost more.

**Pull request merged**
