### PR TITLE
tools: Added exitsnoop: Trace all process termination

### PR DESCRIPTION
**Pull request by amdn**
This is a resubmission of https://github.com/iovisor/bcc/pull/2349 from an Instana, Inc. fork.
This PR also has updates as suggested by @brendangregg, and a refactor by @JeroenSoeters of Insatana to allow import as a python module.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by brendangregg** [comment]
Tested, works, looks good, thanks!

```
window1# sleep 1.3
window2# ./exitsnoop.py 
PCOMM            PID    PPID   TID    AGE(s)  EXIT_CODE 
sleep            15480  7866   15480  1.30    0
[...]
```

One note: do we want to reserve -u in case we add a "-u uid" option later? I'd consider deleting the "-u" and leave it as "--utc" for now (no single character version).

**Comment by amdn** [comment]
@brendangregg - I agree, will revert my last minute addition of -u ... should have left it alone haha

**Comment by brendangregg** [comment]
[buildbot, test this please]

**Comment by brendangregg** [comment]
Can you add an entry for this in README.md, like the other tools? Thanks.

**Comment by brendangregg** [comment]
[buildbot, ok to test]

**Comment by brendangregg** [comment]
Thanks!

**Comment by amdn** [comment]
Gladly! I learned a lot.

**Pull request merged**
