### PR TITLE
libbpf-tools: Fix cachestat with kernel 5.15

### PR DESCRIPTION
**Pull request by chenhengqi**
The tool cachestat is broken on kernel 5.15 due to kernel function
renaming. Fix the tool by detecting symbol existence. See #3687 and
 #3692.

Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>

### CODE REVIEW

**Comment by davemarchevsky** [comment]
@chenhengqi is this still a 'draft'? I think it's mergeable as-is

**Comment by chenhengqi** [comment]
It works on kernel 5.15, but still broken on recent 5.16-rc :(

**Comment by inevity** [comment]
Works on 5.16.7 kernel.

**Comment by chenhengqi** [comment]
@davemarchevsky  Could you take a look at this again ?

**Pull request merged**
