### PR TITLE
Fix ucalls

### PR DESCRIPTION
**Pull request by r4f4**
Fix some compatibility issues with python3.

### CODE REVIEW

**Comment by 4ast** [comment]
cc @goldshtn

**Comment by drzaeus77** [comment]
[buildbot, ok to test]
[buildbot, add to whitelist]

**Comment by goldshtn** [comment]
Hold on - did you test on Python 2.x after making these changes? Or does it break Python 2.x? (which is not acceptable)

**Comment by r4f4** [comment]
It seems this [1] is the way to make it work on both py2 and py3. I'll update the patch.

[1] https://www.python.org/dev/peps/pep-3113/

**Comment by goldshtn** [comment]
There's also the already merged patch that needs this fix

**Comment by r4f4** [comment]
Just sent a separate PR addressing them.

**Pull request merged**
