### PR TITLE
Update to the latest API

### PR DESCRIPTION
**Pull request by ddompe**

### CODE REVIEW

**Comment by brendangregg** [comment]
buildbot, ok to test

**Comment by brendangregg** [comment]
Thanks, tested, works, LGTM.

**Comment by 4ast** [comment]
this conflicts with @goldshtn PR https://github.com/iovisor/bcc/pull/698

**Comment by goldshtn** [comment]
Please don't merge this, #698 will have the whole thing fixed shortly. I just pushed another update that fixes `trace` and there remains only a minor issue with `argdist` to fix.

**Comment by 4ast** [comment]
@ddompe please double check that merged @goldshtn 's fix works for you as well and if so, please close this PR. Thanks

**Pull request closed without merging**
