### PR TITLE
add uprobe support in funcinterval

### PR DESCRIPTION
**Pull request by zhaoyao73**
Signed-off-by: Yao Zhao <yao.zhao1@huawei.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
@zhaoyao73 Thanks. LGTM. Could you add an example to the man page as well?

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by zhaoyao73** [comment]
> @zhaoyao73 Thanks. LGTM. Could you add an example to the man page as well?

sure. Added man change as well. Please review again

**Pull request merged**
