### PR TITLE
Add an option to strip leading zeros from linear histograms

### PR DESCRIPTION
**Pull request by netedwardwu**
Signed-off-by: Edward Wu <edwardwu@realtek.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
@netedwardwu could you provide better commit messages to explain why this change is more user friendly than the old way?

**Comment by netedwardwu** [comment]
Hi @yonghong-song , if not enough please tell me, thanks

**Comment by yonghong-song** [comment]
@netedwardwu I think commit message is not quite right. I see below,
```
For example:
      usec         : count     distribution
        0          : 1        |                                        |
        1          : 2        |                                        |
        2          : 0        |                                        |
        3          : 1        |                                        |
        4          : 0        |                                        |
        5          : 0        |                                        |
        6          : 0        |                                        |
        7          : 0        |                                        |
        8          : 0        |                                        |
        9          : 0        |                                        |
        10         : 0        |                                        |
        11         : 0        |                                        |
        12         : 0        |                                        |
        13         : 0        |                                        |
        14         : 0        |                                        |
        15         : 0        |                                        |
        16         : 0        |                                        |
        17         : 0        |                                        |
        18         : 0        |                                        |
        19         : 0        |                                        |
        20         : 0        |                                        |
        21         : 0        |                                        |
        22         : 0        |                                        |
        23         : 0        |                                        |
        24         : 0        |                                        |
        25         : 0        |                                        |
        26         : 0        |                                        |
        27         : 0        |                                        |
        28         : 0        |                                        |
        29         : 0        |                                        |
        30         : 0        |                                        |
        31         : 0        |                                        |
        32         : 0        |                                        |
        33         : 0        |                                        |
        34         : 0        |                                        |
        35         : 0        |                                        |
        36         : 0        |                                        |
        37         : 0        |                                        |
        38         : 0        |                                        |
        39         : 0        |                                        |
        40         : 0        |                                        |
        41         : 0        |                                        |
        42         : 0        |                                        |
        43         : 0        |                                        |
        44         : 1559     |****************************************|

Such much info is hard to analyze by FIRST glance, especially console view

After supporting strip leading zeros
print_linear_hist("usec", "name", name_print, strip_leading_zero=True)

      usec         : count     distribution
        0          : 1        |                                        |
        1          : 2        |                                        |
        3          : 1        |                                        |
        44         : 1559     |****************************************|

This is what we really care, and it's clear.
```

But the patch actually tried to remove the leading 0's, so for the above case, the first `count` is not 0, so there should be no change. Is that right?

**Comment by netedwardwu** [comment]
A little weird...give me some times to verify...I remember that I verified on Ubuntu...Will get back later...thanks for your carefulness

**Comment by netedwardwu** [comment]
Hi @yonghong-song ,

True cast now, sorry about that. Thanks

**Comment by yonghong-song** [comment]
No problem. One more typo,
```
      usec         : count     distribution
        41         : 3        |****************************************|
        42         : 1        |*************                           |
```
The `count` should be 7 and 2, to be consistent with the output without this patch.

**Comment by netedwardwu** [comment]
ok, although those are my true cases, but if consistent is better, then I just modified it to fit it.

**Pull request merged**
