### PR TITLE
Add open_perf_event to the C/C++ API

### PR DESCRIPTION
**Pull request by romain-intel**
Another change to bring the C/C++ API more in line with the Python one.

### CODE REVIEW

**Comment by 4ast** [comment]
cc @palmtenor

**Comment by palmtenor** [comment]
Already chatted with @romain-intel offline. This looks good in general.

My only concern is naming are a bit confusing. I suggest rename the table class to `BPFPerfEventArray` (more aligned with name in Python API), and in `BPF` class rename `perf_event_buffers_` also to `perf_event_arrays_` (they are not really buffers).

Let's also maybe add some tests reading counter values to make sure this would always work in the future.

**Comment by goldshtn** [comment]
[buildbot, add to whitelist]

**Comment by romain-intel** [comment]
Addressed renaming comments. Will do a future update with a few tests. Should I add a new file to tests/cc/ for these tests or is there a better place?

**Pull request merged**
