### PR TITLE
Create undump.py examples text file

### PR DESCRIPTION
**Pull request by Rtoax**

### CODE REVIEW

**Comment by davemarchevsky** [comment]
[buildbot, test this please]

**Comment by davemarchevsky** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
Since you are creating an undump.py example file, could you also add 'x' permission to undump.py. Currently we have
```
[$ ~/work/bcc/examples/tracing] ls -l undump.py
-rw-r--r-- 1 yhs users 3621 Oct 12 10:06 undump.py
[$ ~/work/bcc/examples/tracing]
```
which is not an executable.

Could you also add some minimum commit message? Currently it is empty.

**Comment by Rtoax** [comment]
git update-index --chmod=+x examples/tracing/undump.py

**Comment by Rtoax** [comment]
it's `git update-index --chmod=+x examples/tracing/undump.py` work?

**Comment by Rtoax** [comment]
> Since you are creating an undump.py example file, could you also add 'x' permission to undump.py. Currently we have
> 
> ```
> [$ ~/work/bcc/examples/tracing] ls -l undump.py
> -rw-r--r-- 1 yhs users 3621 Oct 12 10:06 undump.py
> [$ ~/work/bcc/examples/tracing]
> ```
> 
> which is not an executable.
> 
> Could you also add some minimum commit message? Currently it is empty.

it's `git update-index --chmod=+x examples/tracing/undump.py` works?

**Comment by yonghong-song** [comment]
> > Since you are creating an undump.py example file, could you also add 'x' permission to undump.py. Currently we have
> > ```
> > [$ ~/work/bcc/examples/tracing] ls -l undump.py
> > -rw-r--r-- 1 yhs users 3621 Oct 12 10:06 undump.py
> > [$ ~/work/bcc/examples/tracing]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which is not an executable.
> > Could you also add some minimum commit message? Currently it is empty.
> 
> it's `git update-index --chmod=+x examples/tracing/undump.py` works?

Not sure, you can try. Maybe just `chmod +x examples/tracing/undump.py` and `git commit` should also work.

**Pull request closed without merging**
