### PR TITLE
Do not throw exception on ipv6 packets in tcpretrans

### PR DESCRIPTION
**Pull request by bobrik**
Really not sure how come I get ipv6 retransmissions when ipv6 is disabled, but I don't like the exception either way 😕

### CODE REVIEW

**Comment by bobrik** [comment]
With python 3 or netaddr we can print ipv6 addresses nicely.

**Comment by markdrayton** [comment]
Hah. I just fixed this too :) I also fixed up the v6 handling — at the moment we're only sending the last 4 bytes of the address from the kernel to userspace. I'll put my PR up in a few hours but if this one is committed before then I can just rebase on top.

**Comment by brendangregg** [comment]
yes, see #503. This code should be moved into bcc, and tools updated to use it:

```Python
def inet_ntoa(addr):
    # u32 to dotted quad string
    dq = ''
    for i in range(0, 4):
        dq = dq + str(addr & 0xff)
        if (i != 3):
            dq = dq + '.'
        addr = addr >> 8
    return dq

def inet6_ntoa(addr):
    # see RFC4291 summary in RFC5952 section 2
    s = ":".join(["%x" % x for x in unpack_from(">HHHHHHHH",
        pack("QQ", addr & 0xffffffff, addr >> 64))])

    # compress left-most zero run only (change to most for RFC5952):
    s = re.sub(r'(^|:)0:(0:)+', r'::', s, 1)
    return s
```

If someone wants to do that (and/or improve the code!), please go ahead!

**Comment by brendangregg** [comment]
I'll accept this PR for now and look out for the next one. Really looking forward to having these inet things in __init__.py. Can't remember why I didn't do it -- maybe I wanted to write a test suite first?

**Comment by brendangregg** [comment]
Correction, I won't accept it as github is not letting me (branch is out of date)!...

**Comment by bobrik** [comment]
@brendangregg I just rebased.

**Pull request merged**
