### PR TITLE
tools/opensnoop: Fix compilation problem

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Fix stupid bug introduced by myself.

Signed-off-by: Mauricio Vásquez <mauricio@kinvolk.io>

### CODE REVIEW

**Comment by mauriciovasquezbernal** [comment]
cc @alban

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by alban** [comment]
The fix works in my test.

**Pull request merged**
