### PR TITLE
Unify python executables to use `#!/usr/bin/env python` shebang

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
Currently some python executables either do not have shebang or have it hardcoded to `#!/usr/bin/python`. This is causing some problems on our production systems. 

RPM specs currently workaround that problem by `sed`ing the resulting files:
https://github.com/iovisor/bcc/blob/dccc4f28b7404b2f77f8ad8c7ad1ea741db589f2/SPECS/bcc.spec#L91-L94

This diff:
* rewrites shebangs across all executable python files to: `#!/usr/bin/env python`.
* removes the mangling code from RPM specs.
* adds a travis-ci test to verify that all python executables continue to have proper shabangs.

PS. It seems like the travis build is not enabled for bcc: https://travis-ci.org/iovisor/bcc

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
The change looks good. But there is a timeout for py_test_tools_smoke with lib/ustat.py on fc25/26/27. Not sure why yet.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
I have no idea why timeout happens with ustat.py in test_tools_smoke.py. I tried on my local fc27 and it works fine. Maybe the test VM has higher load? Maybe you could try to increase timeout value to see whether it works or not?
```
diff --git a/tests/python/test_tools_smoke.py b/tests/python/test_tools_smoke.py
index 211dbdb..14f72ee 100755
--- a/tests/python/test_tools_smoke.py
+++ b/tests/python/test_tools_smoke.py
@@ -363,7 +363,7 @@ class SmokeTests(TestCase):
 
     @skipUnless(kernel_version_ge(4,4), "requires kernel >= 4.4")
     def test_ustat(self):
-        self.run_with_duration("lib/ustat.py 1 1")
+        self.run_with_duration("lib/ustat.py 1 1", 20)
 
     @skipUnless(kernel_version_ge(4,4), "requires kernel >= 4.4")
     def test_uthreads(self):
```

**Comment by yonghong-song** [comment]
@SaveTheRbtz usdt.py fix has been merged. Now you can rebase and resubmit. Thanks!

**Comment by SaveTheRbtz** [comment]
@yonghong-song can you ping the buildbot? he is ignoring my pleas for some reason =)

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Just pinged and the test started!

**Comment by yonghong-song** [comment]
Right. Let me do a test again.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by SaveTheRbtz** [comment]
@yonghong-song Ok, now it is a fc28 with:
```
removing 'bcc-0.7.0' (and everything under it)
removing 'bcc-0.7.0' (and everything under it)
error: [Errno 2] No such file or directory: 'bcc-0.7.0'
make[2]: *** [src/python/CMakeFiles/bcc_py_python2.dir/build.make:62: src/python/dist-python2/bcc-0.7.0.tar.gz] Error 1
make[2]: *** Deleting file 'src/python/dist-python2/bcc-0.7.0.tar.gz'
make[1]: *** [CMakeFiles/Makefile2:650: src/python/CMakeFiles/bcc_py_python2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

seems like the resulting makefile is racy (it builds `bpf-shared` and `bpf-static` in the same dir) but still is ran in parallel:
```
+ make -j2
```

**Comment by yonghong-song** [comment]
Right. We need to fix this as well. It happens quite frequently.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by SaveTheRbtz** [comment]
Yey! Thanks, will wait for a release now (no rush).

As for the build error something fishy is going on as it does generate same targets twice:
```
[ 17%] Generating dist-python2/bcc-0.7.0.tar.gz
...
[ 18%] Generating dist-python2/bcc-0.7.0.tar.gz
```

and indeed generated makefile for the python3 distribution (`src/python/CMakeFiles/bcc_py_python3.dir/build.make`) also generates python2 archive:
```
src/python/dist-python3/bcc-0.7.0.tar.gz: ../src/python/bcc/__init__.py
src/python/dist-python3/bcc-0.7.0.tar.gz: src/python/setup.py
src/python/dist-python3/bcc-0.7.0.tar.gz: src/python/dist-python2/bcc-0.7.0.tar.gz
    @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/Users/rbtz/c0d3/bcc/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Generating dist-python3/bcc-0.7.0.tar.gz"
    cd /Users/rbtz/c0d3/bcc/build/src/python && python3 setup.py sdist --dist-dir dist-python3

src/python/dist-python2/bcc-0.7.0.tar.gz: ../src/python/bcc/__init__.py
src/python/dist-python2/bcc-0.7.0.tar.gz: src/python/setup.py
    @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/Users/rbtz/c0d3/bcc/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Generating dist-python2/bcc-0.7.0.tar.gz"
    cd /Users/rbtz/c0d3/bcc/build/src/python && python2 setup.py sdist --dist-dir dist-python2
```

Something is likely wrong with #1951

**Pull request merged**
