### PR TITLE
libbpf-tools: gethostlatency allow specify libc path

### PR DESCRIPTION
**Pull request by chenhengqi**
This commit adds a new option to gethostlatency which
allows user to specify which libc to use for tracing.
This is useful when application is not linked against
default libc.

Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>

### CODE REVIEW

**Comment by anakryiko** [comment]
you have a lot of clean up changes that are not related to libc path, can you please split your changes into two separate commit so it's clear what's going on?

**Comment by chenhengqi** [comment]
OK, will do that.

**Comment by chenhengqi** [comment]
> you have a lot of clean up changes that are not related to libc path, can you please split your changes into two separate commit so it's clear what's going on?

Done.

**Review by danobi — APPROVED** [review]
LGTM

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
