### PR TITLE
Fix shared library loaded into multiple sections

### PR DESCRIPTION
**Pull request by palmtenor**
As @goldshtn explained in comment of #1357, our current code (namely `ProcSyms`) are not handling shared libraries loaded into multiple executable memory sections well, since it ignores file offset.

This PR fixes the such issue for both symbol resolution and global address resolution

### CODE REVIEW

**Comment by goldshtn** [comment]
LGTM - this fixes the multi-section load issue for me. Thanks! 👍

**Comment by palmtenor** [comment]
@yonghong-song Please let me know when #1358 merges. I will rebase and make sure everything goes correctly:)

**Comment by yonghong-song** [comment]
@palmtenor just merged #1358, please rebase and resubmit this patch. Thanks!

**Comment by palmtenor** [comment]
Rebased and minor style updates

**Comment by goldshtn** [comment]
LGTM.

**Pull request merged**
