### PR TITLE
add missing PT_REGS_RET definition for x86

### PR DESCRIPTION
**Pull request by boat0**

### CODE REVIEW

**Comment by palmtenor** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
change looks good. Thanks!

**Comment by palmtenor** [comment]
[buildbot, test this please]

**Comment by palmtenor** [comment]
@boat0 Please rebase to fix test issues:)

**Comment by boat0** [comment]
reopened as https://github.com/iovisor/bcc/pull/2134

**Comment by yonghong-song** [comment]
duplicated of pull request #2134

**Pull request closed without merging**
