### PR TITLE
ext4dist: code cleanup (#2181)

### PR DESCRIPTION
**Pull request by arighi**
- Dynamically handle different ext4_file_operations
   (avoid wasting extra cycles).

 - make the code pep8 compliant

 - clarify comments

Signed-off-by: Andrea Righi <righi.andrea@gmail.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
ubuntu 16.04 ext4dist test failed
```
27: ======================================================================
27: FAIL: test_ext4dist (__main__.SmokeTests)
27: ----------------------------------------------------------------------
27: Traceback (most recent call last):
27:   File "/home/iovisor/jenkins/workspace/bcc-pr/label/ubuntu1604/tests/python/test_tools_smoke.py", line 152, in test_ext4dist
27:     self.run_with_duration("ext4dist.py 1 1")
27:   File "/home/iovisor/jenkins/workspace/bcc-pr/label/ubuntu1604/tests/python/test_tools_smoke.py", line 32, in run_with_duration
27:     (timeout, full_command), shell=True))
27: AssertionError: 0 != 1
27: 
27: ----------------------------------------------------------------------
27: Ran 79 tests in 197.075s
27: 
27: FAILED (failures=1, skipped=19)
27: Failed
27/38 Test #27: py_test_tools_smoke ..............***Failed  197.11 sec
test 28
      Start 28: py_test_tools_memleak
```

**Comment by arighi** [comment]
It looks like it's failing with kernels < 4.10. I'll fix it and test it. Sorry about that.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
