### PR TITLE
Add uretprobe example for indirect function

### PR DESCRIPTION
**Pull request by rhdxmr**
Already there is strlen_hist.py as a nice example of uretprobe. But it can
not work correctly if strlen is indirect function(IFUNC). So
strlen_hist_ifunc.py is introduced to show how to use uprobe/uretprobe for
indirect functions.

### CODE REVIEW

**Review by yonghong-song — COMMENTED** [review]
Looks good. Thanks! The example is python3 only. If you can make it python2 compatible, it will be great. I believe some people/system still uses python2...

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by rhdxmr** [comment]
Hello @yonghong-song 
OK 👌 I will change the code to be compatible with python 2 and will push the modified code again.

Thanks,

**Comment by rhdxmr** [comment]
@yonghong-song 
I modified the code python 2 and 3 compatible. It is tested under python 2.7.17 and 3.8.2
Can you review this code please?

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Thanks!

**Pull request merged**
