### PR TITLE
stackcount: do per-pid statistics only if -P is provided

### LINKED ISSUE #2308: stackcount default output shouldn't do -P
This is annoying -- stackcount by default does per-process breakdowns:

```
# stackcount kmem_cache_alloc
Tracing 1 functions for "kmem_cache_alloc"... Hit Ctrl-C to end.
[...]

  kmem_cache_alloc
  user_path_at_empty
  vfs_statx
  SYSC_newstat
  SyS_newstat
  do_syscall_64
  entry_SYSCALL_64_after_hwframe
  __xstat
  [unknown]
    python3 [15243]
    1026
```

See the "python3 [15243]" line? Most of the time I don't want this -- I'd rather just group on the stack trace, to reduce the output. Sometimes I want per-process, but only sometimes, and stackcount already has this:

```
  -P, --perpid          display stacks separately for each process
```

My guess is that -P is broken, and has become the default behavior by mistake.

Could someone please look into fixing this: eliminate the per-process breakdown by default, and only do it if -P is used.

### PR DESCRIPTION
**Pull request by boat0**
Fixes #2308.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Do we need to adjust examples and man pages?

**Comment by brendangregg** [comment]
Thanks! The quickest fix for the examples is to add -P to all the existing examples, so we don't have to change the output.

If you look at the git history for stackcount_example.txt, my first commit has examples that can be included again: examples without -P.

**Comment by boat0** [comment]
Yes. Examples and man pages need some updates too.

**Comment by boat0** [comment]
> Thanks! The quickest fix for the examples is to add -P to all the existing examples, so we don't have to change the output.

-P added to all but two examples with "-K".

> If you look at the git history for stackcount_example.txt, my first commit has examples that can be included again: examples without -P.

Done. That example is restored to be 1st one.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Thanks!

**Pull request merged**
