### PR TITLE
Add installation instructions for snap builds.

### PR DESCRIPTION
**Pull request by evandandrea**
Hi,

We've been providing ~weekly builds of bcc for users of Ubuntu and other distros for a while now, but it would great if we could also get the docs to point at them.

### CODE REVIEW

**Comment by goldshtn** [comment]
[buildbot, ok to test]

**Comment by goldshtn** [comment]
Looks good, will merge once the build passes (it's just a Markdown update but we still need the build so I can click "Merge" :grin:).

**Comment by 4ast** [comment]
This is great. Thank you for doing this.
My only question is ordering of this info in INSTALL.md
I get the marketing aspect of it, but does it really work on anything but ubuntu?
and do we really need to list it first?
@brendangregg @drzaeus77

**Comment by evandandrea** [comment]
>I get the marketing aspect of it, but does it really work on anything but ubuntu?

Yes, it works [anywhere snapd does](https://snapcraft.io/docs/core/install#support-overview). @popey was kind enough to test it on Fedora:

virtualbox_fedora_27_04_2017_14_34_38

 And Mint:
virtualbox_linux mint_27_04_2017_14_27_47

**Comment by evandandrea** [comment]
See also #1138.

**Comment by drzaeus77** [comment]
I'm also hesitant about listing this first, but I am biased since I've put all the effort into maintaining the binary packages for Ubuntu and Fedora. I think that the binaries that the iovisor project itself hosts should come first, and third-party builds (gentoo, arch, snap, etc.) separately.

In addition to that, whichever order we agree to, there should a section heading and corresponding ToC update.

**Comment by brendangregg** [comment]
I wouldn't do it first: it's not the most adopted package manager. I'd do it second. Headings could be 

```
# Packages

Different ways to install it

## Ubuntu Xenial - Binary, apt-get

...

## Ubuntu/Fedora - Binary, snap
```

Plus it doesn't work on our typical systems:

```
$ sudo snap install bcc --edge
error: unknown flag `edge'
```

Plus it works strangely even when it does work:

```
$ sudo snap install bcc 
17.94 MB / 17.94 MB [=====================================================================================================================================] 100.00 % 1.64 MB/s 

Name  Version                      Rev  Developer
bcc   0.3.0-20170420-1809-e512f02  18   ev

$ biosnoop
No command 'biosnoop' found, did you mean:
 Command 'iosnoop' from package 'perf-tools-unstable' (universe)
biosnoop: command not found

$ find /usr -name biosnoop
$

# ok, what the heck?

$ snap connect bcc:system-observe
error: the required argument `<snap>:<slot>` was not provided

# umm....
```

I assume I'm on an old version of snap. .. if I fix all that, does it get to the point where I can just run "biosnoop" like the apt-get package?

**Comment by brendangregg** [comment]
... I'd looked at those screenshots to see how you'd run the tools, but since they are *top tools they clear the screen and I can't see the command.

**Comment by evandandrea** [comment]
@brendangregg sorry about that. What's the output of `lsb_release -ra` and `snap version` on your system? That looks like an old version of snapd (as you suggest), and it's not immediately clear to me why it didn't auto-update. Also, is /snap/bin on your PATH?

**Comment by brendangregg** [comment]
```
# snap version
error: Unknown command `version'. Please specify one command of: abort, ack, changes, connect, disconnect, find, install, interfaces, known, list, login, logout, refresh or remove

# lsb_release -ra
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by evandandrea** [comment]
@brendangregg just saw in #1138 that you're stuck on snapd 2.0.3. Does `sudo apt update; sudo apt install snapd` give you 2.25?

**Comment by brendangregg** [comment]
Well, I could run those commands on this one instance, but that doesn't fix all the others.

Should the bcc snap instructions begin with that line? ```sudo apt update; sudo apt install snapd``` seems like that would make it work better for everyone.

**Comment by evandandrea** [comment]
@brendangregg you're right. I've created https://github.com/iovisor/bcc/pull/1161 to guide users to updating their snapd.

**Comment by evandandrea** [comment]
I also have a [PR](https://github.com/CanonicalLtd/snappy-docs/pull/79) open to have the docs suggest an `apt update` before installing snapd on Ubuntu. Other distributions start with more recent versions of snapd that include automatic self-updating.

**Comment by goldshtn** [comment]
@evandandrea @brendangregg What's the status of this PR as far as you're concerned? Is this still relevant?

**Comment by 4ast** [comment]
have been pending for too long. Please resubmit if it's still relevant.

**Pull request closed without merging**
