### PR TITLE
Fix function keys enter an infinite loop (#665)

### PR DESCRIPTION
**Pull request by oujunli**

### CODE REVIEW

**Comment by 4ast** [comment]
that is still a race. how is better?

**Comment by oujunli** [comment]
I log out the table.py zero routime:
```Python
    def zero(self):
        count = 0
        for k in self.keys():
            self[k] = self.Leaf()
            count += 1
            print("count: %d"%(count))
```
run python tools/funccount.py  "SyS_*":
```
Tracing 335 functions for "SyS_*"... Hit Ctrl-C to end.
^C
ADDR             FUNC                          COUNT
ffffffff811fc1d0 sys_execve                        1
ffffffff811f3f60 sys_lseek                         1
ffffffff8107cf30 sys_wait4                         1
...
ffffffff810f4690 SyS_futex                      7450
count: 1
count: 2
count: 3
...
count: 333308
count: 333309
count: 333310
...
````
Tracing 335 functions, but the zero for larger the 335 and enter an infinite loop. I set the map to zero when funccount  loops use counts.items(), avoid this problem and less call counts.Leaf(). If I missing something, please checkout. 

Thank you.

**Comment by 4ast** [comment]
then we need to fix zero() function instead of trying to workaround it in the script

**Comment by drzaeus77** [comment]
The code should already be working around this. The way keys() works is relies on Iter(), which itself relies on the fact that bpf_get_next_key returns the least upper bound for the last position in the iteration, so it only loops through the list once, even if items are being added back into the map.

**Comment by oujunli** [comment]
should we change the `zero` function loops through the list once as the `items` and `values` function?  
because funccount is used `items`, so depend on it's `item` loop solve this problem and no need to loop the map again to set value zero. can make another commit let `zero` function  loops through the list once.  
thanks.

**Comment by oujunli** [comment]
I try to fix this issue by through the keys list once as the items and values function do, not solve by funccount script.  update the commit.  
thanks.

**Comment by drzaeus77** [comment]
ok to test
[message to buildbot]

**Comment by 4ast** [comment]
@drzaeus77 pls review

**Comment by drzaeus77** [comment]
FYI, I'm currently investigating the kernel behavior w.r.t. this patch. It may possibly be a kernel-side issue, and we'll decide best how/if to workaround this in userspace after getting a better understanding.

**Comment by oujunli** [comment]
OK. If want more information and test, I am very happy to provide.  

thanks.

**Comment by oujunli** [comment]
a better way in [780](https://github.com/iovisor/bcc/pull/780#issuecomment-255966580), close.

**Pull request closed without merging**
