### PR TITLE
mdflush: fix for Linux 4.14

### PR DESCRIPTION
**Pull request by pchaigno**
[Starting Linux 4.14](https://github.com/torvalds/linux/commit/74d46992e0d9dee7f1f376de0d56d31614c8a17a), there's one less indirection layer to get the
disk name.

### CODE REVIEW

**Comment by yonghong-song** [comment]
This probably will not work with backported distribution (fb internal, netflix internal, certain redhat dist.) I am not sure what is the standard way to deal with this.

cc @brendangregg

**Comment by brendangregg** [comment]
So far we've gotten away with checking if symbols exist rather than kernel versions. But in this case it's a structure difference. I wonder if there's a symbol change from the same patchset we could use as an indicator?

In any case, this should be commented to say that it's temporary code. "# workaround for the 4.14 change." That way, we can find it in the distant future and delete it when it's no longer needed.

**Comment by pchaigno** [comment]
I hadn't though about backported distribution.
I've updated the pull request to use the `bio-dev` macro as a discriminator to detect the structure difference. That macro was introduced in the [same commit](https://github.com/torvalds/linux/commit/74d46992e0d9dee7f1f376de0d56d31614c8a17a) as the structure change.

@drzaeus77 Could you relaunch the build? Looks like it failed due to the certificate expiration.

**Comment by yonghong-song** [comment]
LGTM. I think this addressed Brendan's concern.

**Pull request merged**
