### PR TITLE
update debian packaging

### PR DESCRIPTION
**Pull request by drzaeus77**
Updated version of PR #506 with included clang-format-3.7 fix.

### CODE REVIEW

**Comment by drzaeus77** [comment]
retest this please

**Comment by drzaeus77** [comment]
@lnussbaum @taem The last commit in this series breaks Ubuntu packaging (which doesn't have `/lib/modules/$(uname -r)/source`, so this would need to be made into a toggle for debian vs ubuntu. Do you have a preferred mechanism (env variables, multiple files, etc.) to toggle this in the relevant build system?

**Comment by taem** [comment]
Hi @drzaeus77,

You can use dpkg-vendor(1) to change the build behavior as per distribution.

**Comment by lnussbaum** [comment]
@taem, yes that would be the way to go.

However, I'm surprised that this breaks on Ubuntu. Maybe there's another way to achieve the same thing that works on both distributions.

**Comment by drzaeus77** [comment]
In our previous experiments, most of the distros have unique preferences w.r.t. kernel header directories. See, for example, #397. In other words, I'm not at all surprised that it broke :)

**Comment by lnussbaum** [comment]
Yeah, but I suspected that there's a way to make this work automatically on both Debian and Ubuntu. Given Ubuntu tries to pull as many packages as possible from Debian without modification, I would be surprised if they introduced a difference that would cause some stuff to break.

**Pull request merged**
