### PR TITLE
Explicitly include sys/types.h

### PR DESCRIPTION
**Pull request by gmile**
This will help build bcc on Alpine Linux.

See discussion in https://github.com/iovisor/bcc/issues/421#issuecomment-362889861.

### CODE REVIEW

**Comment by gmile** [comment]
There's one other issue with Alpine left that I'm not sure how to fix: the problem is that `RTLD_DI_ORIGIN` constant (see this https://github.com/iovisor/bcc/issues/421#issuecomment-362911704) is not defined during bcc compilation.

This _looks_ like a `musl` issue / limitation, as it does not define this constant:

* https://pkgs.alpinelinux.org/contents?file=dlfcn.h&path=&name=musl-dev&branch=edge
* https://git.musl-libc.org/cgit/musl/tree/include/dlfcn.h?h=v1.1.18

This can be solved either by re-writing `(dlinfo(dlhdl, RTLD_DI_ORIGIN, &libpath) < 0)` somehow differently to be supported by alpine too, or by making an `APKBUILD` to build bcc, with patching the bcc sources on the fly during packaging.

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
is it possible to add `RTLD_DI_ORIGIN` in `musl` `dlfcn.h`?

**Comment by gmile** [comment]
@yonghong-song I asked people on `musl` IRC, they did not like the idea to `RTLD_DI_ORIGIN` add define.

Someone suggested an idea how to adapt the code to make it more generic and compile on Alpine. I took their suggestion and made a PR https://github.com/iovisor/bcc/pull/1599

**Pull request merged**
