### PR TITLE
libbpf-tools: fix misuse of bpf_get_current_pid_tgid

### PR DESCRIPTION
**Pull request by chenhengqi**
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by chenhengqi** [comment]
Push with commit message.

**Review by anakryiko — APPROVED** [review]
LGTM.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
