### PR TITLE
Do not rely on RTLD_DI_ORIGIN

### PR DESCRIPTION
**Pull request by gmile**
This will allow the bcc to be built on Alpine without additional
patches to musl.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
The testtest_libbcc  failed.
>> 3: Unable to open /lib64/libz.so.1/libz.so.1: Not a directory

Looks like RTLD_DI_ORIGIN gives a library path (not including lib name) while
link_map->l_name includes the path + lib_name.

Could you correct this and resubmit the patch?

Thanks.

**Comment by gmile** [comment]
@yonghong-song thank you for pointing out what the problem was. I was looking at the build logs but could not figure out what was the problem.

I've amended the original commit, the build passes now. Please consider taking another look at the patch.

**Comment by yonghong-song** [comment]
Looks good. Thanks!

**Pull request merged**
