### PR TITLE
Tool tcpsubnet

### PR DESCRIPTION
**Pull request by rmanyari**
PR for [1571](https://github.com/iovisor/bcc/issues/1571)

I updated the tool based on Brendan's feedback, added some validation as well.

Signed-off-by: Rodrigo Manyari rodrigo@twosigma.com

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
Tested. Looks good.

cc @brendangregg

**Comment by brendangregg** [comment]
Looks good. A couple of things.

I'd add 0.0.0.0/0 to the default, as a catch-all.

And there should be a newline after the output, or a timestamp line before the output (like argparse's "[18:21:00]"), because without these, we can't really understand the output. Eg:

```
# ./tcpsubnet.py
Tracing... Output every 1 secs. Hit Ctrl-C to end
127.0.0.1/32            2734
127.0.0.1/32             183
^C
```

Was that 2734 segments in the first second, and then 183 segments in the second? No, it wasn't, they were several seconds apart, but tcpsubnet prints nothing if there was no activity. It should look like this, at least:

```
# ./tcpsubnet.py
Tracing... Output every 1 secs. Hit Ctrl-C to end
127.0.0.1/32            2734





127.0.0.1/32             183

^C
```

Or:

```
# ./tcpsubnet.py
Tracing... Output every 1 secs. Hit Ctrl-C to end
[18:21:03]
127.0.0.1/32            2734
[18:21:04]
[18:21:05]
[18:21:06]
[18:21:07]
[18:21:08]
127.0.0.1/32             183
^C
```

**Comment by rmanyari** [comment]
Good catch, the behavior was obvious to me but only because I wrote the tool... I made date and time keys in the JSON object, putting it as a header would defeat the point of having JSON in the first place.

I also updated the examples, man page and brought back 0.0.0.0/0 as the last default

**Comment by brendangregg** [comment]
Looks good, thanks!

**Pull request merged**
