### PR TITLE
stackcount: add -c option for CPU only events

### PR DESCRIPTION
**Pull request by dstepanovsrc**
Add the -c option to trace events happened only the requested CPU.
Update command line, man and example.

Signed-off-by: Dima Stepanov <dimastep@yandex-team.ru>
Signed-off-by: Yury Kotov <yury-kotov@yandex-team.ru>

### CODE REVIEW

**Comment by dstepanovsrc** [comment]
While working on the linux scheduler, it was a nice thing to trace the function stacks based on the CPU id. Because for the scheduler routines the process id often differs.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Looks good to me. Thanks!

**Comment by brendangregg** [comment]
Thanks;

While we're looking at stackcount. :-) ... I just filed #2308 -- would be good to get that fixed if someone wants to do it.

**Pull request merged**
