### PR TITLE
Expand io_latencies example to iolatpcts tool

### PR DESCRIPTION
**Pull request by htejun**
Expand the example into more fully developed tool and add documentation and simplified example as suggested in #2861.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Thanks!

**Comment by brendangregg** [comment]
I've been testing it and the percentiles don't match other tools. Example output with a streaming read workload:

```
# ./biolatpcts.py 
Block I/O latency percentile example. See tools/biolatpcts.py for the full utility.
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=5us 
p50=5us p75=5us p90=5us p99=5us 
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=1500us 
p50=5us p75=5us p90=5us p99=5us 
^CTraceback (most recent call last):
  File "./biolatpcts.py", line 101, in <module>
    sleep(3)
KeyboardInterrupt
```

(The first line needs updating.) This output shows either 5us or 1500us latency. Odd.

At the same time, I was running other tools. biolatency:

```
# more out.biolatency 
Tracing block device I/O... Hit Ctrl-C to end.

     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 0        |                                        |
        64 -> 127        : 0        |                                        |
       128 -> 255        : 0        |                                        |
       256 -> 511        : 0        |                                        |
       512 -> 1023       : 0        |                                        |
      1024 -> 2047       : 95       |**************                          |
      2048 -> 4095       : 145      |**********************                  |
      4096 -> 8191       : 259      |****************************************|
      8192 -> 16383      : 13       |**                                      |
[...]
```

This shows a latency distribution of between 1 and 16 ms. Now iostat:

```
# iostat -xz 1
[...]
Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
nvme0n1        513.00    0.00 131328.00      0.00     0.00     0.00   0.00   0.00    4.78    0.00   1.22   256.00     0.00   1.95 100.00
[...]
```

(I hate the wide output.) This shows an average I/O time of around 7 ms (r_await + svctm), matching biolatency.

Now for biosnoop: I edited the bpftrace version to show start->end based latency (LAT1) as well as rq->io_start_time_ns based latency (LAT2) which biolatpct uses:

```
# ./biosnoop.bt 
Attaching 4 probes...
TIME(ms)     COMM             PID      LAT1(us)   LAT2(us)
158          dd               12878        1773       1748
160          dd               12878        3807       3796
162          dd               12878        5619       5603
165          dd               12878        8294       8277
166          dd               12878        1315       1294
168          dd               12878        3046       3036
170          dd               12878        5050       5035
172          dd               12878        7169       7153
174          dd               12878        1887       1865
176          dd               12878        3845       3834
178          dd               12878        5618       5603
[...]
```

So the problem isn't the latency measurement. (And I'd prefer to use rq->io_start_time_ns as it avoids an extra kprobe in this case: I'd looked into it earlier but couldn't see how it matched bpf_ktime_get_ns() for comparison with other events.)

I think something is wrong with the percentile calculation.

**Comment by brendangregg** [comment]
I forgot to mention: the streaming read workload was:

```
# dd if=/dev/nvme0n1 iflag=direct of=/dev/null bs=1024k 
^C1028+0 records in
1027+0 records out
1076887552 bytes (1.1 GB, 1.0 GiB) copied, 7.02547 s, 153 MB/s
```

This just further confirms that the I/O time should be ~6.5 ms (1000 / 153).

**Comment by htejun** [comment]
So, on my laptop:

```

**Comment by htejun** [comment]
So, on my laptop running the same command:

```
p50=395us p75=615us p90=885us p99=1500us 
p50=785us p75=995us p90=1500us p99=2500us 
p50=725us p75=955us p90=1500us p99=2500us 
p50=745us p75=995us p90=1500us p99=2500us 
p50=555us p75=775us p90=1500us p99=2500us 
p50=445us p75=575us p90=775us p99=1500us 

```
and
```
     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 63       |                                        |
        32 -> 63         : 103      |                                        |
        64 -> 127        : 46       |                                        |
       128 -> 255        : 171      |                                        |
       256 -> 511        : 7373     |***********************                 |
       512 -> 1023       : 12327    |****************************************|
      1024 -> 2047       : 4203     |*************                           |
      2048 -> 4095       : 335      |*                                       |
      4096 -> 8191       : 6        |                                        |
```
which are in line with each other. Your result almost looks like the script was getting only few samples per period. Can you make it print out how many samples it was seeing per period?

**Comment by htejun** [comment]
Printing out `lat_total` should do the trick.

**Comment by brendangregg** [comment]
I added print(lat_total) to the loop:

```
# ./biolatpcts.py 
Block I/O latency percentile example. See tools/biolatpcts.py for the full utility.
p50=5us p75=5us p90=5us p99=5us 
1545
p50=5us p75=5us p90=5us p99=1500us 
1544
p50=5us p75=5us p90=5us p99=5us 
1546
```

It really loves 5us and 1500us.

**Comment by htejun** [comment]
Hmm... that's really curious. I've been using the script pretty extensively. Can you see whether changing req->io_start_time_ns to req->start_time_ns gives a different result?

**Comment by htejun** [comment]
If that doesn't solve the problem, can you please run `tools/biolatpcts.py -v nvme0n1` and post the output? That'll dump all the buckets and should tell us whether the issue is on the collection side or me counting dumb.

**Pull request merged**
