### PR TITLE
fix lua-bcc build issue with cmake try_compile

### PR DESCRIPTION
**Pull request by yonghong-song**
Certain versions of recent gcc (e.g., gcc 6.3.0 on ubuntu17.04)
has pie enabled by default at linker (collect2) stage.
The compilation flag "-no-pie" is available to negate
this linker option.

Add -no-pie to compilation flag only if it is available.
Earlier gcc compiler may not have this option but it does
not have linker pie on-by-default either.

Tested with ubuntu 17.04 and my local gcc 4.8.5 (not accepting -no-pie).

Signed-off-by: Yonghong Song <yhs@fb.com>

### CODE REVIEW

**Comment by yonghong-song** [comment]
cc @prakashsurya @markdrayton Please help verify as well.

**Comment by prakashsurya** [comment]
This works for me. Thank you!

**Comment by markdrayton** [comment]
I'll verify this first thing this morning.

**Comment by markdrayton** [comment]
The patch works for me. Thanks for coming up with a robust solution!

Nit: is the PR description inaccurate? As far as I can tell we only add `-no-pie` if the compiler supports it. As far as I can see we don't add `--no-pie` in any case.

**Comment by yonghong-song** [comment]
The patch is in its 2nd revision and I have changed description. Goto commit page you will see the new commit message. Unfortunately, it is not automatically updated here. I will manually update here.

**Comment by drzaeus77** [comment]
I think this patch deserves to be separated out into a file in the cmake/ directory, with an implementation as a macro that fills in the proper string for nopie.

**Comment by yonghong-song** [comment]
Okay. Will give another spin.

**Comment by yonghong-song** [comment]
I have reorged and simplified patch a little. @prakashsurya @markdrayton  Could you help take a look again?

**Comment by cirocosta** [comment]
Working fine here as well :+1: I'm on `Linux version 4.10.0-32-generic (buildd@lcy01-05) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017
`

**Comment by markdrayton** [comment]
Looks good to me.

**Pull request merged**
