### PR TITLE
Improve helper Macros

### PR DESCRIPTION
**Pull request by palmtenor**
- Documentations indicates we can pass a size argument for `BPF_HASH`, but we actually can't. This PR fixes that.
- This PR also adds helper Macros for popular array map type.
- Make tools and examples use those new Macros.

### CODE REVIEW

**Comment by goldshtn** [comment]
@drzaeus77 fc25 bot needs a nudge

**Comment by pchaigno** [comment]
@goldshtn Closing-reopening pull requests restarts CI builds ;)

**Comment by goldshtn** [comment]
@pchaigno I can restart the build with a buildbot command, but the problem is that the VMs would occasionally initialize incorrectly, in such a way that 'git' is missing. Restarting the build wouldn't help in that case, only restarting the VM.

**Comment by pchaigno** [comment]
Oh, okay :-)
I thought it worked in #1066 but @drzaeus77 might have restarted the VM in the meantime :zap:

**Comment by drzaeus77** [comment]
> @drzaeus77 might have restarted the VM in the meantime 

Correct :) Doing my morning janitorial work now...

**Comment by drzaeus77** [comment]
[buildbot, test this please]

**Pull request merged**
