### PR TITLE
bashreadline: Filter out non-bash COMMs

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Prevents the output of non-bash readlines when bash is dynamically
linked. Refs #1851.

### CODE REVIEW

**Comment by juergenhoetzel** [comment]
Without this commit `bashreadline` will also output readline calls from other binaries (For example gnuplot):

```
17:48:38  5640   plot(x*x)
```

**Comment by palmtenor** [comment]
[buildbot, ok to test]

**Comment by palmtenor** [comment]
[buildbot, retest this please]

**Comment by yonghong-song** [comment]
ubuntu 16.04 failed. could you try to change `char comm[TASK_COMM_LEN];` to `char comm[TASK_COMM_LEN] = {};` to see whether it helps?

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
