### PR TITLE
[test][python] temptatively attach to blk_start_request probe.

### PR DESCRIPTION
**Pull request by chantra**
`blk_start_request` is gone since kernel 5. This patch is in the same vein as https://github.com/iovisor/bcc/pull/4124
except that we only conditionally attach to `blk_start_request` but attach also attach to
`blk_mq_start_request`.

### CODE REVIEW

**Comment by chantra** [comment]
Mind that this is currently based off #4204 .

@chenhengqi , @yonghong-song I could fix #4124 at the same time (e.g remove the conditional).

**Comment by chenhengqi** [comment]
As I commented in #4124, I think we should trace both `blk_mq_start_request` and `blk_start_request`.

**Comment by chantra** [comment]
> As I commented in #4124, I think we should trace both `blk_mq_start_request` and `blk_start_request`.

I am happy to fix this as part of this diff. @yonghong-song WDYT?

**Comment by chantra** [comment]
@chenhengqi , I checked with Jens offline and he confirmed what you said. e.g for 4.x, a driver would either be using blk-mq or the legacy stack.

I have updated this PR with a revert of #4124.

**Pull request merged**
