### PR TITLE
Add installation instructions for Amazon Linux 1 AMI

### PR DESCRIPTION
**Pull request by travisdarkphysics**
Sign-Off-By Travis Davies <trdavies@amazon.com>

### CODE REVIEW

**Comment by brendangregg** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by brendangregg** [comment]
[buildbot, test this please]

**Comment by brendangregg** [comment]
Can someone who has the right privileges please click merge? I can't as it's failing checks.

**Pull request merged**
