### PR TITLE
Fix llvm shared build

### PR DESCRIPTION
**Pull request by ismail**
Trim the llvm libs to the direct requirements only and use llvm_expand_dependencies to discover all dependencies.

### CODE REVIEW

**Comment by ismail** [comment]
Breaks fedora build, I'll recheck please don't close the PR.

**Comment by drzaeus77** [comment]
FYI, both fedora and ubuntu buildbots have 3.7.1 llvm installed on them currently.

**Comment by ismail** [comment]
Now, ready to merge.

**Comment by drzaeus77** [comment]
Thanks.

**Pull request merged**
