### PR TITLE
Python build: copy files instead of creating link

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Fix for https://github.com/iovisor/bcc/issues/1964, more details in commit message.

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by mauriciovasquezbernal** [comment]
I'm not sure why tests were failing, I forced pushed to rerun them but I just realized that somebody has to ask the build bot to do it.

**Comment by yonghong-song** [comment]
Not sure what is going on with the pull request got stuck in testing stage.
cc @drzaeus77

**Comment by yonghong-song** [comment]
okay.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
