### PR TITLE
bcc/tools: Fix renaming of the state field of task_struct

### PR DESCRIPTION
**Pull request by chenhengqi**

### CODE REVIEW

**Comment by chenhengqi** [comment]
@yonghong-song  I got verification failure again. Feel like something we fix in #3669 .

<details>
<pre>
bpf: Failed to load program: Permission denied
; int oncpu(struct pt_regs *ctx) {
0: (bf) r6 = r1
; struct task_struct *p = ctx->di;
1: (79) r7 = *(u64 *)(r6 +112)
2: (b7) r8 = 0
; u32 pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->pid); _val; });
3: (63) *(u32 *)(r10 -80) = r8
last_idx 3 first_idx 0
regs=100 stack=0 before 2: (b7) r8 = 0
; u32 pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->pid); _val; });
4: (bf) r3 = r7
5: (07) r3 += 2384
6: (bf) r1 = r10
; 
7: (07) r1 += -80
; u32 pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->pid); _val; });
8: (b7) r2 = 4
9: (85) call bpf_probe_read#4
last_idx 9 first_idx 0
regs=4 stack=0 before 8: (b7) r2 = 4
; u32 pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->pid); _val; });
10: (61) r1 = *(u32 *)(r10 -80)
; u32 pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->pid); _val; });
11: (63) *(u32 *)(r10 -4) = r1
; u32 tgid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->tgid); _val; });
12: (07) r7 += 2388
; u32 tgid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->tgid); _val; });
13: (63) *(u32 *)(r10 -80) = r8
14: (bf) r1 = r10
; 
15: (07) r1 += -80
; u32 tgid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&p->tgid); _val; });
16: (b7) r2 = 4
17: (bf) r3 = r7
18: (85) call bpf_probe_read#4
last_idx 18 first_idx 0
regs=4 stack=0 before 17: (bf) r3 = r7
regs=4 stack=0 before 16: (b7) r2 = 4
; u64 ts = bpf_ktime_get_ns();
19: (85) call bpf_ktime_get_ns#5
; u64 ts = bpf_ktime_get_ns();
20: (7b) *(u64 *)(r10 -16) = r0
; bpf_map_update_elem((void *)bpf_pseudo_fd(1, -2), &pid, &ts, BPF_ANY);
21: (18) r1 = 0xffff9f18d4b6e800
23: (bf) r8 = r10
; 
24: (07) r8 += -4
25: (bf) r3 = r10
26: (07) r3 += -16
; bpf_map_update_elem((void *)bpf_pseudo_fd(1, -2), &pid, &ts, BPF_ANY);
27: (bf) r2 = r8
28: (b7) r4 = 0
29: (85) call bpf_map_update_elem#2
; pid = bpf_get_current_pid_tgid();
30: (85) call bpf_get_current_pid_tgid#14
; pid = bpf_get_current_pid_tgid();
31: (63) *(u32 *)(r10 -4) = r0
; tgid = bpf_get_current_pid_tgid() >> 32;
32: (85) call bpf_get_current_pid_tgid#14
33: (bf) r7 = r0
; tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, -2), &pid);
34: (18) r1 = 0xffff9f18d4b6e800
; tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, -2), &pid);
36: (bf) r2 = r8
37: (85) call bpf_map_lookup_elem#1
; if (tsp == 0) {
38: (15) if r0 == 0x0 goto pc+104
 R0_w=map_value(id=0,off=0,ks=4,vs=8,imm=0) R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=3) R8=fp-4 R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-80=????mmmm
; u64 delta = ts - *tsp;
39: (79) r9 = *(u64 *)(r0 +0)
 R0_w=map_value(id=0,off=0,ks=4,vs=8,imm=0) R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=3) R8=fp-4 R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-80=????mmmm
; u64 delta = ts - *tsp;
40: (79) r8 = *(u64 *)(r10 -16)
; bpf_map_delete_elem((void *)bpf_pseudo_fd(1, -2), &pid);
41: (18) r1 = 0xffff9f18d4b6e800
43: (bf) r2 = r10
; 
44: (07) r2 += -4
; bpf_map_delete_elem((void *)bpf_pseudo_fd(1, -2), &pid);
45: (85) call bpf_map_delete_elem#3
; u64 delta = ts - *tsp;
46: (1f) r8 -= r9
47: (b7) r1 = 1000
; if ((delta < MINBLOCK_US) || (delta > MAXBLOCK_US)) {
48: (2d) if r1 > r8 goto pc+94
 R0=inv(id=0) R1_w=inv1000 R6=ctx(id=0,off=0,imm=0) R7=inv(id=3) R8_w=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-80=????mmmm
49: (77) r7 >>= 32
50: (b7) r1 = 0
; struct key_t key = {};
51: (7b) *(u64 *)(r10 -24) = r1
last_idx 51 first_idx 46
regs=2 stack=0 before 50: (b7) r1 = 0
52: (7b) *(u64 *)(r10 -32) = r1
53: (7b) *(u64 *)(r10 -40) = r1
54: (7b) *(u64 *)(r10 -48) = r1
55: (7b) *(u64 *)(r10 -56) = r1
56: (7b) *(u64 *)(r10 -64) = r1
57: (7b) *(u64 *)(r10 -72) = r1
58: (7b) *(u64 *)(r10 -80) = r1
59: (bf) r1 = r10
60: (07) r1 += -64
; bpf_get_current_comm(&key.target, sizeof(key.target));
61: (b7) r2 = 16
62: (85) call bpf_get_current_comm#16
last_idx 62 first_idx 46
regs=4 stack=0 before 61: (b7) r2 = 16
; key.t_tgid = tgid;
63: (63) *(u32 *)(r10 -28) = r7
; key.t_pid = pid;
64: (61) r1 = *(u32 *)(r10 -4)
; key.t_pid = pid;
65: (63) *(u32 *)(r10 -32) = r1
; key.t_k_stack_id = bcc_get_stackid(bpf_pseudo_fd(1, -4), ctx, 0);
66: (18) r2 = 0xffffbe7c44001000
; return bcc_get_stackid_(ctx, (void *)map, flags);
68: (bf) r1 = r6
69: (b7) r3 = 0
70: (85) call bpf_get_stackid#27
; key.t_k_stack_id = bcc_get_stackid(bpf_pseudo_fd(1, -4), ctx, 0);
71: (63) *(u32 *)(r10 -40) = r0
; key.t_u_stack_id = bcc_get_stackid(bpf_pseudo_fd(1, -4), ctx, BPF_F_USER_STACK);
72: (18) r2 = 0xffffbe7c44001000
; return bcc_get_stackid_(ctx, (void *)map, flags);
74: (bf) r1 = r6
75: (b7) r3 = 256
76: (85) call bpf_get_stackid#27
; key.t_u_stack_id = bcc_get_stackid(bpf_pseudo_fd(1, -4), ctx, BPF_F_USER_STACK);
77: (63) *(u32 *)(r10 -36) = r0
; woke = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, -3), &pid);
78: (18) r1 = 0xffff9f18d4b6d400
80: (bf) r2 = r10
; 
81: (07) r2 += -4
; woke = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, -3), &pid);
82: (85) call bpf_map_lookup_elem#1
; if (woke) {
83: (15) if r0 == 0x0 goto pc+23
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=00000000 fp-32=inv fp-40=mmmmmmmm fp-48=00000000 fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80=00000000
; key.w_k_stack_id = woke->k_stack_id;
84: (61) r1 = *(u32 *)(r0 +16)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=00000000 fp-32=inv fp-40=mmmmmmmm fp-48=00000000 fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80=00000000
; key.w_k_stack_id = woke->k_stack_id;
85: (63) *(u32 *)(r10 -48) = r1
; key.w_u_stack_id = woke->u_stack_id;
86: (61) r1 = *(u32 *)(r0 +20)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=00000000 fp-32=inv fp-40=mmmmmmmm fp-48_w=inv fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80=00000000
; key.w_u_stack_id = woke->u_stack_id;
87: (63) *(u32 *)(r10 -44) = r1
; key.w_pid = woke->w_pid;
88: (61) r1 = *(u32 *)(r0 +24)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=00000000 fp-32=inv fp-40=mmmmmmmm fp-48_w=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80=00000000
; key.w_pid = woke->w_pid;
89: (63) *(u32 *)(r10 -24) = r1
; key.w_tgid = woke->w_tgid;
90: (61) r1 = *(u32 *)(r0 +28)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24_w=inv fp-32=inv fp-40=mmmmmmmm fp-48_w=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80=00000000
; key.w_tgid = woke->w_tgid;
91: (63) *(u32 *)(r10 -20) = r1
; __builtin_memcpy(&key.waker, woke->name, TASK_COMM_LEN);
92: (61) r1 = *(u32 *)(r0 +4)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24_w=mmmmmmmm fp-32=inv fp-40=mmmmmmmm fp-48_w=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80=00000000
93: (67) r1 <<= 32
94: (61) r2 = *(u32 *)(r0 +0)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0,smax_value=9223372032559808512,umax_value=18446744069414584320,var_off=(0x0; 0xffffffff00000000),s32_min_value=0,s32_max_value=0,u32_max_value=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24_w=mmmmmmmm fp-32=inv fp-40=mmmmmmmm fp-48_w=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80=00000000
95: (4f) r1 |= r2
96: (7b) *(u64 *)(r10 -80) = r1
97: (61) r1 = *(u32 *)(r0 +8)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24_w=mmmmmmmm fp-32=inv fp-40=mmmmmmmm fp-48_w=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80_w=mmmmmmmm
98: (61) r2 = *(u32 *)(r0 +12)
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0,umin_value=1000) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24_w=mmmmmmmm fp-32=inv fp-40=mmmmmmmm fp-48_w=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=00000000 fp-80_w=mmmmmmmm
99: (67) r2 <<= 32
100: (4f) r2 |= r1
101: (7b) *(u64 *)(r10 -72) = r2
; bpf_map_delete_elem((void *)bpf_pseudo_fd(1, -3), &pid);
102: (18) r1 = 0xffff9f18d4b6d400
104: (bf) r2 = r10
; 
105: (07) r2 += -4
; bpf_map_delete_elem((void *)bpf_pseudo_fd(1, -3), &pid);
106: (85) call bpf_map_delete_elem#3
107: (37) r8 /= 1000
; ({ typeof(counts.key) _key = key; typeof(counts.leaf) *_leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -1), &_key); if (_leaf) (*_leaf) += delta;else { typeof(counts.leaf) _zleaf; __builtin_memset(&_zleaf, 0, sizeof(_zleaf)); _zleaf += delta;bpf_map_update_elem_(bpf_pseudo_fd(1, -1), &_key, &_zleaf, BPF_NOEXIST); } });
108: (79) r1 = *(u64 *)(r10 -24)
109: (7b) *(u64 *)(r10 -88) = r1
110: (79) r1 = *(u64 *)(r10 -32)
corrupted spill memory
processed 104 insns (limit 1000000) max_states_per_insn 0 total_states 6 peak_states 6 mark_read 4

Traceback (most recent call last):
  File "./offwaketime.py", line 296, in <module>
    fn_name="oncpu")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 824, in attach_kprobe
    (fn_name, '/'.join(probes)))
Exception: Failed to attach BPF program oncpu to kprobe finish_task_switch
</pre>
</details>

**Comment by chenhengqi** [comment]
Comment out the `bpf_get_current_comm` calls make `offwaketime` and `offcputime` works.

**Comment by yonghong-song** [comment]
Thanks for the fix. I just merged a patch to sync with latest libbpf repo. You can just rebase on top of master so you don't need to worry about that.

**Comment by yonghong-song** [comment]
Regarding to verifier failure, I think this is due to recent verifier change. Mostly this is due to patch
  93dd0d0922f3 bpf: Check the other end of slot_type for STACK_SPILL

In this particular case, we have
68: R0_w=inv(id=0) R1_w=inv1000 R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=0) R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0) R10=fp0 fp-8=mmmm??
?? fp-16=mmmmmmmm fp-48=????mmmm                                                                                                                                     
; key.tgid = tgid;                                                                                                                                                   
68: (63) *(u32 *)(r10 -44) = r8 

Note that r10-44 4 bytes is NOT marked as spill.

69: (61) r1 = *(u32 *)(r10 -4)                                                                                                                                       
70: R0_w=inv(id=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=0) R8=inv(id=0,umax_value=4294967295,var_off=(
0x0; 0xffffffff)) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-48=mmmmmmmm                                                                                   
; key.pid = pid;                                                                                                                                                     
70: (63) *(u32 *)(r10 -48) = r1

r10-48 is marked as SPILL.

So for the 8byte slot r10-48, we have 4byte SPILL and 4 byte not SPILL and overall type is SPILL since
the aligned access r10-48 is marked as SPILL.

Later on, the compiler tries to load the whole 8 bytes since it is marked as SPILL but some bytes actually not SPILL, and the verifier complains.

97: R0=inv(id=0) R1_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0) R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0) R10=fp0 fp-8=[16/542]
 fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=inv fp-56_w=mmmmmmmm fp-64_w=mmmmmmmm fp-72_w=mmmmmmmm
97: (79) r1 = *(u64 *)(r10 -48)
corrupted spill memory

Please use the following workaround:

diff --git a/tools/offcputime.py b/tools/offcputime.py
index 128c6496..077804ed 100755
--- a/tools/offcputime.py
+++ b/tools/offcputime.py
@@ -116,8 +116,8 @@ bpf_text = """
 #define MAXBLOCK_US    MAXBLOCK_US_VALUEULL
 
 struct key_t {
-    u32 pid;
-    u32 tgid;
+    u64 pid;
+    u64 tgid;
     int user_stack_id;
     int kernel_stack_id;
     char name[TASK_COMM_LEN];
@@ -250,7 +250,7 @@ if debug or args.ebpf:
         exit()

So pid/tgid field will be in separate 8-byte memory location and this will fix the issue.

I will discuss this issue with other kernel folks on how to proper fix this verifier issue.

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by chenhengqi** [comment]
> Regarding to verifier failure, I think this is due to recent verifier change. Mostly this is due to patch 93dd0d0922f3 bpf: Check the other end of slot_type for STACK_SPILL
> 
> In this particular case, we have 68: R0_w=inv(id=0) R1_w=inv1000 R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=0) R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0) R10=fp0 fp-8=mmmm?? ?? fp-16=mmmmmmmm fp-48=????mmmm ; key.tgid = tgid; 68: (63) *(u32 *)(r10 -44) = r8
> 
> Note that r10-44 4 bytes is NOT marked as spill.
> 
> 69: (61) r1 = *(u32 *)(r10 -4) 70: R0_w=inv(id=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=0) R8=inv(id=0,umax_value=4294967295,var_off=( 0x0; 0xffffffff)) R9=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-48=mmmmmmmm ; key.pid = pid; 70: (63) *(u32 *)(r10 -48) = r1
> 
> r10-48 is marked as SPILL.
> 
> So for the 8byte slot r10-48, we have 4byte SPILL and 4 byte not SPILL and overall type is SPILL since the aligned access r10-48 is marked as SPILL.
> 
> Later on, the compiler tries to load the whole 8 bytes since it is marked as SPILL but some bytes actually not SPILL, and the verifier complains.
> 
> 97: R0=inv(id=0) R1_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0) R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0) R10=fp0 fp-8=[16/542] fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=inv fp-56_w=mmmmmmmm fp-64_w=mmmmmmmm fp-72_w=mmmmmmmm 97: (79) r1 = *(u64 *)(r10 -48) corrupted spill memory
> 
> Please use the following workaround:
> 
> diff --git a/tools/offcputime.py b/tools/offcputime.py index 128c6496..077804ed 100755 --- a/tools/offcputime.py +++ b/tools/offcputime.py @@ -116,8 +116,8 @@ bpf_text = """ #define MAXBLOCK_US MAXBLOCK_US_VALUEULL
> 
> struct key_t {
> 
> * u32 pid;
> * u32 tgid;
> 
> * u64 pid;
> * u64 tgid;
>   int user_stack_id;
>   int kernel_stack_id;
>   char name[TASK_COMM_LEN];
>   @@ -250,7 +250,7 @@ if debug or args.ebpf:
>   exit()
> 
> So pid/tgid field will be in separate 8-byte memory location and this will fix the issue.
> 
> I will discuss this issue with other kernel folks on how to proper fix this verifier issue.

Thanks for the explanations. Will keep an eye on BPF mailing list to see how this is fixed.

BTW, could you elaborate more on this spill/ NOT spill things, I would like to know how to match this with the verifier logs,
so that I can debug myself. Thanks.

**Comment by chenhengqi** [comment]
> Thanks for the fix. I just merged a patch to sync with latest libbpf repo. You can just rebase on top of master so you don't need to worry about that.

Thanks, will drop the first commit.

**Comment by yonghong-song** [comment]
For
> BTW, could you elaborate more on this spill/ NOT spill things, I would like to know how to match this with the verifier logs,
so that I can debug myself. Thanks.

Unfortunately, this needs to look at kernel source code.
First, from below verifier code,
```
                for (i = 1; i < BPF_REG_SIZE; i++) {
                        if (stype[(slot - i) % BPF_REG_SIZE] != STACK_SPILL) {
                                verbose(env, "corrupted spill memory\n");
                                return -EACCES;
                        }
                }
```
You know that the reason is a 8-byte slot does not have everything marked as SPILL

Second, let us traceback why the 8-slot is marked as SPILL but second 4-byte not.
This can be explained in verifier.c function check_stack_write_fixed_off().
The first 4  byte met the condition and is marked as SPILL together with the 8-byte
slot.
```
        if (reg && !(off % BPF_REG_SIZE) && register_is_bounded(reg) &&
            !register_is_null(reg) && env->bpf_capable) {
                if (dst_reg != BPF_REG_FP) {
                        /* The backtracking logic can only recognize explicit
                         * stack slot address like [fp - 8]. Other spill of
                         * scalar via different register has to be conservative.
                         * Backtrack from here and mark all registers as precise
                         * that contributed into 'reg' being a constant.
                         */
                        err = mark_chain_precision(env, value_regno);
                        if (err)
                                return err;
                }       
                save_register_state(state, spi, reg, size);
        }
```
The second 4 byte is not marked as SPILL as it does not meet the
above condition or the another condition in the funciton,
```
        } else if (reg && is_spillable_regtype(reg->type)) {
                /* register containing pointer is being spilled into stack */
                if (size != BPF_REG_SIZE) {
                        verbose_linfo(env, insn_idx, "; ");
                        verbose(env, "invalid size of register spill\n");
                        return -EACCES;
                }
                if (state != cur && reg->type == PTR_TO_STACK) {
                        verbose(env, "cannot spill pointers to stack into stack frame of the caller\n");
                        return -EINVAL;
                }
                save_register_state(state, spi, reg, size);
        } else {
                u8 type = STACK_MISC;
```

**Comment by yonghong-song** [comment]
LGTM. Thanks for the fix!

**Pull request merged**
