### PR TITLE
bcc: support BPF_MAP_TYPE_{INODE, TASK}_STORAGE maps

### PR DESCRIPTION
**Pull request by chenhengqi**
Add support for BPF_MAP_TYPE_{INODE, TASK}_STORAGE in BCC.
Like sk local storage, this commit allows creating inode/task
local storage using BPF_{INODE, TASK}_STORAGE macros, and
manipulating maps using map.{inode, task}_storage_get() and
map.{inode, task}_storage_delete() helpers.

Also add examples to demostrate BPF_{INODE, TASK}_STORAGE usage.

### CODE REVIEW

**Review by yonghong-song — COMMENTED** [review]
Thanks for the implementation. This is really useful, esp. task local storage. Currently quiet some bcc tools use a hash map with tid as the key to preserve data between different bpf programs. We could use task local storage here.

So for example task_storate.py, I suggest to make it a little bit more omplex. For example, we can have two programs, one KFUNC and another KRETFUNC, we can use task local storage to pass some data (e.g., timestamp in order to calculate latency) from KFUNC program to KRETFUNC program. This example can serve as a template for bcc tools use case with task local storage. WDYT?

**Comment by chenhengqi** [comment]
OK, will do.

**Comment by chenhengqi** [comment]
Updated.

**Comment by yonghong-song** [comment]
LGTM. Thanks!

**Pull request merged**
