### PR TITLE
examples/tracing: add io_latencies - IO latency distribution monitor

### PR DESCRIPTION
**Pull request by htejun**
This adds flexible low overhead latency percentile monitoring for block
devices which can be useful in understanding and debugging IO related
issues.

Signed-off-by: Tejun Heo <tj@kernel.org>

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Thanks. Looks like we have some installation for old fedora systems. For example, fc28, which is successful, we have
```
+ find /tmp/rpmbuild.llxwdE/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/share/bcc/tools /tmp/rpmbuild.llxwdE/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/share/bcc/examples -type f -exec sed -i -e '1 s|^#!/usr/bin/python$|#!/usr/bin/python3|' -e '1 s|^#!/usr/bin/env python$|#!/usr/bin/python3|' '{}' ';'
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python3 1
Bytecompiling .py files below /tmp/rpmbuild.llxwdE/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
Bytecompiling .py files below /tmp/rpmbuild.llxwdE/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/lib/python3.6 using /usr/bin/python3.6
/tmp/rpmbuild.llxwdE/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/share/bcc/examples/networking/simple_tc.py
...
```

in fc27, we have failure,
```
+ find /tmp/rpmbuild.YDH9zV/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/share/bcc/tools /tmp/rpmbuild.YDH9zV/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/share/bcc/examples -type f -exec sed -i -e '1 s|^#!/usr/bin/python$|#!/usr/bin/python2|' -e '1 s|^#!/usr/bin/env python$|#!/usr/bin/python2|' '{}' ';'
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python2 1
Bytecompiling .py files below /tmp/rpmbuild.YDH9zV/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
Compiling /tmp/rpmbuild.YDH9zV/BUILDROOT/bcc-0.11.0-201.git.c9d3e2ac.x86_64/usr/share/bcc/examples/tracing/io_latencies.py ...
  File "/usr/share/bcc/examples/tracing/io_latencies.py", line 138
    print(f'idx={idx} counted={counted} pct={counted / total:.2} req={req}')
                                                                          ^
SyntaxError: invalid syntax

error: Bad exit status from /var/tmp/rpm-tmp.f2nUYW (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.f2nUYW (%install)
```

Let me think how to resolve this. If anybody has experience how to resolve this, please help. Thanks!

**Comment by yonghong-song** [comment]
One way to fix this is to only install this .py binary if the machine has python3 as the default?
```
-bash-4.4$ pwd
/home/yhs/work/bcc/examples/tracing
-bash-4.4$ cat CMakeLists.txt 
file(GLOB C_FILES *.c)
file(GLOB PY_FILES *.py)
file(GLOB TXT_FILES *.txt)
install(PROGRAMS ${PY_FILES} DESTINATION share/bcc/examples/tracing)
install(FILES ${C_FILES} DESTINATION share/bcc/examples/tracing)
install(FILES ${TXT_FILES} DESTINATION share/bcc/examples/tracing)
-bash-4.4$
```
Ideally, the best is for tools to be available for both python2 and python3. But I am aware that python2 is slowly out-of-date...

**Comment by htejun** [comment]
I think the only new feature it uses is the f-strings. Lemme replace them with the good ol' .format and test it against python2.7.

**Comment by htejun** [comment]
* Replaced f-strings with .format()'s.
* Removed _ separators in numeric literals and replaced them with named constants.

python2 on my machine doesn't complain on parsing phase at least. Can't really test it locally as my installation doesn't seem to have bcc for python2.

[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by brendangregg** [comment]
I like it, although it's both a new example (showing how to do percentiles) and a tool (I'd want to use this). I don't know if you have the time to do it yourself, but in the future I'd see this becoming:

- examples/biolatencies.py: with options stripped out
- tools/biolatencies.py: with options intact, support for "sda" as an argument, man page, examples file.

If someone else wants to do this work, I'd leave the Copyrights intact in both files to show where the code came from.

**Comment by htejun** [comment]
Oh, I didn't know there was tools directory. I'll implement the suggestions later this week. Thanks!

**Comment by yonghong-song** [comment]
Thanks @htejun , FYI, this is the bcc contributor guideline for tools: https://github.com/iovisor/bcc/blob/master/CONTRIBUTING-SCRIPTS.md

**Pull request merged**
