### PR TITLE
tools: add option --cgroupmap to tcp tools

### PR DESCRIPTION
**Pull request by alban**
List of tcp tools updated: tcpaccept, tcpconnect, tcptracer.

This is the same pattern used initially in #2651 (opensnoop, execsnoop) and then in #2749 (bindsnoop).

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
Looks good. Since new options are added, could you change the man page as well?

**Comment by alban** [comment]
Rebased & man pages updated (including for opensnoop and execsnoop: the option --cgroupmap was missing too).

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by alban** [comment]
The "tcptracer --cgroupmap" filter for "TCP accept" events does not work well. Sorry I missed that. I'll fix in a moment.

**Comment by alban** [comment]
Updated.

**Pull request merged**
