### PR TITLE
stackcount: fix TypeError

### PR DESCRIPTION
**Pull request by mwesolowski**
fix for one of the problems mentioned in https://github.com/iovisor/bcc/issues/2512

### CODE REVIEW

**Comment by palmtenor** [comment]
[buildbot, test this please]

**Comment by palmtenor** [comment]
[buildbot, ok to test]

**Comment by palmtenor** [comment]
@yonghong-song Is it OK for us to hard-code `utf-8` as the encoding?

**Comment by yonghong-song** [comment]
@palmtenor I think it should be okay in this case as it is already used 'utf-8' encoding in the same file. Typically, we do not want to do encoding for parameters of bcc python library calls. In this case, it is for print and sometimes for python 3, byte array may print with prefix 'b' which may be undesirable in some cases.

**Pull request merged**
