### PR TITLE
sync readme hello_world.py example with actual implementation

### PR DESCRIPTION
**Pull request by yonghong-song**
Signed-off-by: Yonghong Song <yhs@plumgrid.com>

### CODE REVIEW

**Comment by brendangregg** [comment]
I just created a PR with what I had in mind -- I don't think it clashes with this.

**Comment by drzaeus77** [comment]
@yonghong-song since Brendan's change isn't conflicting with yours, can you please address his comment and then I will merge them both.

**Comment by yonghong-song** [comment]
@drzaeus77, since we touch the same file, it looks like I cannot push further change to my private directory yhs_dev, which is prohibited by github. Please go ahead to to merge Gregg's patch and
I will rebase and re-submit my patch with fixes.

**Comment by yonghong-song** [comment]
will provide a new consolidated one soon.

**Pull request closed without merging**
