### PR TITLE
Update SDT argument constraints

### PR DESCRIPTION
**Pull request by sandip4n**
Update SDT argument constraints, that is, `FOLLY_SDT_ARG_CONSTRAINT` in the folly tracing header `tests/python/include/folly/tracing/StaticTracepoint-ELF.h`, to support all architectures as discussed with @palmtenor in #1365. Also, we update the constraint for `powerpc` as the new constraint allows register indexed or indirect operands as well.

[Update 10/10] This also sets the default argument parser to that of `x86_64`.

### CODE REVIEW

**Comment by yonghong-song** [comment]
Could you make a similar change to usdt.cc file as well?
#ifdef __powerpc64__
  ArgumentParser_powerpc64 parser(arg_fmt);
#elif defined(__x86_64__)
  ArgumentParser_x64 parser(arg_fmt);
#else
#error "bcc does not support this platform yet"
#endif

Similar to your StaticTracepoint-ELF.h change, change the default to x86_64 and does not error out during compilation time. Other architecture can add their implementation later.

**Comment by sandip4n** [comment]
@yonghong-song I have added a new commit with the changes you suggested.

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by yonghong-song** [comment]
@sandip4n test failed due to git checkout. Could you rebase your change on top of the current master and retry? Thanks.

**Comment by yonghong-song** [comment]
[buildbot, ok to test]

**Comment by sandip4n** [comment]
Looks like you figured out a way to merge this. Thanks @yonghong-song

**Pull request merged**
