### PR TITLE
Trace add filter

### PR DESCRIPTION
**Pull request by tty5**
add filter of process name and msg

### CODE REVIEW

**Comment by yonghong-song** [comment]
Could you also update the example file and man page?

**Comment by tty5** [comment]
> Could you also update the example file and man page?

example file and man page has updated.

thanks

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
LGTM. Thanks!

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
