### PR TITLE
tools/tcpaccept compatible with kernel version >= 5.6

### PR DESCRIPTION
**Pull request by chenyuezhou**
After kernel version 5.6, `sk_protocol` is no longer bitfield.

https://patchwork.ozlabs.org/project/netdev/patch/20191219220557.17823-3-mathew.j.martineau@linux.intel.com/

My patch tries to access `->sk_protocol` directly. If the kernel version is before 5.6, it will output the error message `error: address of bit-field requested`, and then works as before. If the kernel version is 5.6 or later, tcpaccept will work properly.

If my patch is acceptable, I will adjust the `bindsnoop` tool in the same way in the next PR.

### CODE REVIEW

**Comment by chenyuezhou** [comment]
It seems that using `BPF_CORE_READ_BITFIELD_PROBED` would be a better choice, but I got this error when I tried to use it.

```
/virtual/main.c:57:14: warning: implicit declaration of function 'BPF_CORE_READ_BITFIELD_PROBED' is invalid in C99 [-Wimplicit-function-declaration]
```

**Comment by chenyuezhou** [comment]
> It seems that using `BPF_CORE_READ_BITFIELD_PROBED` would be a better choice, but I got this error when I tried to use it.

I didn't add the correct header file, let me solve this problem first.

**Comment by yonghong-song** [comment]
This is not supported yet. There is an effort for bcc to use more libbpf functionalities. cc @davemarchevsky

**Comment by chenyuezhou** [comment]
> This is not supported yet. There is an effort for bcc to use more libbpf functionalities. cc @davemarchevsky

@yonghong-song Excuse me. Is anyone working on this issue?

**Comment by yonghong-song** [comment]
@chenyuezhou @davemarchevsky has some interest on this subject. I think the first step is compile into an object file instead of llvm jit. Once we got an object file (or a buffer with ELF object), we can then take advantage of libbpf parsing functionalities. One example is from rust redbpf,
   https://github.com/foniod/redbpf/blob/main/cargo-bpf/src/llvm.rs
specifically pay attention to function LLVMTargetMachineEmitToFile().

If you have any ideas, feel free to share here.

**Pull request closed without merging**
