### PR TITLE
support bcc on ARM64 platform

### PR DESCRIPTION
**Pull request by sjtuhjh**
This new pull request is based on previous pull request 985 (https://github.com/iovisor/bcc/pull/985) review comments.  In addition, the 985 pull request will be closed.

### CODE REVIEW

**Comment by 4ast** [comment]
lgtm
cc @drzaeus77 can clang::rewriter do this instead?
I mean removing 'asm' automatically ?

**Comment by sjtuhjh** [comment]
@4ast  could we merge this pull request or wait for clang enhancement?

**Comment by drzaeus77** [comment]
Yes, the clang rewriter should be able to handle this. Alternatively, you could read the files needing rewriting into c++ strings and modify them in-memory similar to how the exported_files.cc buffers are loaded. Basically, if you add a remapped file through invocation.getPreprocessorOpts().addRemappedFile() it should override the built-in version, without having to change anything on disk.

**Comment by 4ast** [comment]
there is another alternative:
https://www.spinics.net/lists/arm-kernel/msg567602.html

**Comment by goldshtn** [comment]
@sjtuhjh Would you like to move this forward, or should I close for now while we examine the alternatives?

**Comment by 4ast** [comment]
have been pending for too long. Please resubmit if it's still relevant.

**Comment by vielmetti** [comment]
I'm still interested in this issue. Has there been any progress since May?

**Comment by yonghong-song** [comment]
arm64 is okay with bcc now. This pull request is not needed, I think. Could you double check?

**Pull request closed without merging**
