### PR TITLE
Fix the output of example scripts with python3 and handle KeyboardInterrupt

### PR DESCRIPTION
**Pull request by lcp**
Switch to printb to get rid of the prefix 'b' of the byte arrays.
Also handle the KeyboardInterrupt exception for some scripts to avoid the code tracing when stopping the program.

### CODE REVIEW

**Comment by brendangregg** [comment]
I would not change hello world from a 1 line to a 4 line program. It needs to be the simplest possible program -- that's its whole purpose.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
@lcp could you revert the hello_world.py change as commented above by @brendangregg?

**Comment by lcp** [comment]
I see. Will update the PR.

**Comment by lcp** [comment]
The change of hello_world.py has been removed.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request merged**
