### PR TITLE
Linter cleanups

### PR DESCRIPTION
**Pull request by pchaigno**
Would it be possible to enable Travis CI for the repo **before** merging this pull request?

### CODE REVIEW

**Comment by goldshtn** [comment]
Paddin my ignorance, what would we gain by having Travis CI build this repository? We already have three Jenkins build bots.

**Comment by goldshtn** [comment]
Paddin = pardon, silly phone :)

**Comment by pchaigno** [comment]
I'm :+1: with having this as part of the Jenkins' pipeline.

I initially went for Travis CI (proposed in #920, added in #987) because, contrary to the other tests, lint checks should not depend on the underlying OS version and we thus don't need to start a VM; a Travis container is faster. I also really appreciate the integration with GitHub. In particular, the configuration is part of the source code, which doesn't seem to be the case for the current Jenkins build bots.

**Comment by 4ast** [comment]
LGTM. Merge ready? cc @drzaeus77

**Comment by pchaigno** [comment]
Without Travis-CI (or some other CI) enabled, we'll probably have to do this again in a few weeks...

**Pull request merged**
