### PR TITLE
cc: Handle nested functions correctly when resolving symbols

### PR DESCRIPTION
**Pull request by goldshtn**
`ProcSyms::Module::find_addr` incorrectly resolves symbols when
functions are nested in each other. Specifically, this was discovered
with libpthread, where there are multiple symbols for `write`,
and `write_nocancel` is strictly nested inside `write`. Fix by
explicitly going backward until we reach a matching symbol -- see
details in `ProcSyms::Module::find_addr` comments.

/cc @markdrayton

### CODE REVIEW

**Comment by goldshtn** [comment]
@4ast @markdrayton Would be nice to get this merged, it's unbreaking a lot of stacks for me.

**Comment by markdrayton** [comment]
Ugh sorry I missed this. Looks like a nice fix! I look forward to having more sensible stacks :-)

**Comment by palmtenor** [comment]
@goldshtn Sasha, we are working on something related to this. Do you have an example of when such nesting would happen? It would be very helpful for our debugging. Thank you very much in ahead!

**Comment by goldshtn** [comment]
I don’t remember all the details now (traveling), but the PR description says I saw it happen with write and write_nocancel in libpthread.

**Pull request merged**
