### PR TITLE
tools/funccount: Fix 'Failed to attach BPF program' error

### PR DESCRIPTION
**Pull request by Rtoax**
bcc commit e16b628bed37("Add more hints for error kprobe") added hint for failed probes, but did not resolve the issue. If the function is untraceable, we can ignore it so that the program can run normally.

Add the -s,--skip command-line parameter to manually skip probes that fail to attach.

    For example:

    In the 6.2.9 kernel, vfsuid_gt_kuid() is the inline function, at which
    point funccount attach vfsuid_gt_kuid() fails, causing the program to fail.

```
    $ sudo ./funccount.py -r 'vfs.*'
    cannot attach kprobe, Invalid argument
    Failed to attach BPF program b'trace_count_1' to kprobe b'vfsuid_eq_kuid'
```

    These functions all have the same situation:
```
    vfsuid_gt_kuid
    vfsgid_eq_kgid
    vfsgid_gt_kgid
    vfsuid_lt_kuid
    vfsuid_eq_kuid
    vfsgid_lt_kgid
```

```
    $ sudo ./funccount.py -r '^vfs_*' --skip vfsuid_gt_kuid vfsgid_eq_kgid vfsgid_gt_kgid vfsuid_lt_kuid vfsuid_eq_kuid vfsgid_lt_kgid
    Tracing 74 functions for "b'^vfs_*'"... Hit Ctrl-C to end.
    ^C
    FUNC                                    COUNT
    vfs_statfs.part.0.isra.0                    2
    vfs_getxattr                                4
    vfs_write                                  17
    vfs_statx                                 104
    vfs_getattr_nosec                         104
    vfs_fstatat                               104
    vfs_open                                  136
    vfs_read                                  216
```

### CODE REVIEW

**Comment by chenhengqi** [comment]
Does `vfsuid_eq_kuid` appear in `/sys/kernel/debug/tracing/available_events` ?

**Comment by Rtoax** [comment]
> Does `vfsuid_eq_kuid` appear in `/sys/kernel/debug/tracing/available_events` ?

Hi, Hengqi, It seems not appear in `available_events` but in `kallsyms`, so does `vfs_`.

```bash
# grep vfsuid_eq /proc/kallsyms
ffffffff9d7022b0 t __pfx_vfsuid_eq_kuid
ffffffff9d7022c0 t vfsuid_eq_kuid

# grep vfsuid_eq /sys/kernel/debug/tracing/available_events
Get nothing

# grep vfs_ /sys/kernel/debug/tracing/available_events
Get nothing
```

**Comment by Rtoax** [comment]
> Does `vfsuid_eq_kuid` appear in `/sys/kernel/debug/tracing/available_events` ?

Hi, Hengqi, It seems not appear in `available_events` but in `kallsyms`, so does `vfs_`.

```bash
# grep vfsuid_eq /proc/kallsyms
ffffffff9d7022b0 t __pfx_vfsuid_eq_kuid
ffffffff9d7022c0 t vfsuid_eq_kuid

# grep vfsuid_eq /sys/kernel/debug/tracing/available_events
Get nothing

# grep vfs_ /sys/kernel/debug/tracing/available_events
Get nothing
```

**Comment by chenhengqi** [comment]
Please also check `available_filter_functions`, perhaps we should check `available_filter_functions` and skip not tracable functions automatically. (IIRC, bpftrace already do that)

**Comment by Rtoax** [comment]
> Please also check `available_filter_functions`, perhaps we should check `available_filter_functions` and skip not tracable functions automatically. (IIRC, bpftrace already do that)

Thank you, i start a new PR https://github.com/iovisor/bcc/pull/4567, use available_filter_functions filter out untraceable funtions.

**Comment by yonghong-song** [comment]
#4567 is a better solution to solve this problem.

**Pull request closed without merging**
