### PR TITLE
Build CI containers

### PR DESCRIPTION
**Pull request by chantra**
Currently, it takes between 7 and 8 minutes to go through the step "Build docker container with all deps", which is time spent in setting up the CI essentially.
This step is quite long because on top of pulling packages, we also build ruby.

We can greatly reduce this time by using pre-made container images that our CI job will just pull with all deps installed.

The result can be seen in https://github.com/chantra/bcc/tree/faster_ci .
Building and publishing the containers workflow run : https://github.com/chantra/bcc/actions/runs/2862888407
and then a subsequent CI run pulling those containers straight from the registry: https://github.com/chantra/bcc/runs/7844899211?check_suite_focus=true

End result, the step to get our CI containers is in the 30 or 40 seconds. And there is also ways to make this even smaller by making the containers smaller.

This is the first patches in a series of 2 to achieve this.

With those patches I:
- move the docker files used for building CI containers to their own subdir (docker/build) and rename the file `Dockerfile.test` to `Dockerfile.ubuntu`, which will make the workflow logic easier.
- Create a new workflow that will build new containers images:
  - daily to ensure that we have an up to date container
  - on pushes to `master` to only create new images that align with master.
  
  
  This PR will be followed by another PR which will start using those images as demonstrated in https://github.com/chantra/bcc/runs/7844899211?check_suite_focus=true

### CODE REVIEW

**Comment by chantra** [comment]
Follow up on sizing...

In https://github.com/chantra/bcc/tree/slimmer_container I reduce the final container images by 400MB (from a rought 2G)

Before:
```
$ docker image ls
REPOSITORY                           TAG           IMAGE ID      CREATED       SIZE
localhost/ci_fedora-34               latest        b3ba0f13984e  3 hours ago   2.27 GB
ghcr.io/chantra/bcc                  fedora-34     b3ba0f13984e  3 hours ago   2.27 GB
localhost/ci_ubuntu-18.04            latest        85c35be35436  3 hours ago   1.97 GB
ghcr.io/chantra/bcc                  ubuntu-18.04  85c35be35436  3 hours ago     1.97 GB
```

after:
```
$ docker image ls             
REPOSITORY                           TAG           IMAGE ID      CREATED         SIZE
localhost/ci_fedora-34               latest        acd9872a1298  58 minutes ago  1.84 GB
ghcr.io/chantra/bcc                  fedora-34     acd9872a1298  58 minutes ago  1.84 GB
localhost/ci_ubuntu-18.04            latest        9fd62c8b393b  58 minutes ago  1.52 GB
ghcr.io/chantra/bcc                  ubuntu-18.04  9fd62c8b393b  58 minutes ago  1.52 GB
```

or individual layers:
Before: https://gist.github.com/chantra/583b036bea041f5642c89fa07c4d7937
After: https://gist.github.com/chantra/c6325138aedc6c5d2523cf837b594148

Example run shows the time to download the images would now be between 25 and 35s.

https://github.com/chantra/bcc/runs/7847715897?check_suite_focus=true

**Comment by davemarchevsky** [comment]
LGTM. One nit: is it possible to not add the `/build/` subdir? I don't think the current `Dockerfile.ubuntu` is used

**Comment by chantra** [comment]
> LGTM. One nit: is it possible to not add the `/build/` subdir? I don't think the current `Dockerfile.ubuntu` is used

it is actually used, probably super outdated, as part of the publish pipeline: 
https://github.com/iovisor/bcc/blob/3e90aa4ff32e94201f7498c31ae1058053fe6425/.github/workflows/publish.yml#L49
and
https://github.com/iovisor/bcc/blob/3e90aa4ff32e94201f7498c31ae1058053fe6425/docker/Dockerfile.ubuntu

**Comment by davemarchevsky** [comment]
Changes LGTM, fedora 36 tests unsurprisingly have some failures which short-circuits fedora 34 tests. If it's possible to mark the fedora 36 tests as not-critical for the time being (i.e. not short-circuit 34 tests, and not have entire test result be red becaus they fail), I'm comfortable shipping

**Comment by chantra** [comment]
> If it's possible to mark the fedora 36 tests as not-critical for the time being (i.e. not short-circuit 34 tests, and not have entire test result be red becaus they fail), I'm comfortable shipping

How do you do that? Is it something that can be done directly through the mayFail decorator? Or somewhere else?

**Pull request merged**
