### PR TITLE
capture UNIX socket packet

### PR DESCRIPTION
**Pull request by Rtoax**
1. start up server
[rongtao@localhost tools]$ nc --unixsock /work/workspace/undump3.sock -l

2. start undump.py 
[root@localhost study]# ./undump.py -p $(pidof nc)
Tracing UNIX socket packets ... Hit Ctrl-C to end
PID    COMM

3. startup UNIX  socket client
[rongtao@localhost ~]$ nc --unixsock /work/workspace/undump3.sock

4. input some words
[rongtao@localhost ~]$ nc --unixsock /work/workspace/undump3.sock
Hello, World

5. capture the packet
----------------48 65 6c 6c 6f 2c 20 57 6f 72 6c 64 0a 
----------------recv 13 bytes
153784 nc

### CODE REVIEW

**Comment by Rtoax** [comment]
Is this submission valuable?

**Comment by chenhengqi** [comment]
The commit message should explain why this tool is useful, what problems it could solve.

Dumping raw bytes does not make sense to me.
In production, we often use gRPC + protobuf over UDS, so it might be helpful to allow user decode those raw bytes in a specific encoding.

BTW, I would suggest you invest this effort to libbpf-based tool.

**Comment by yonghong-song** [comment]
This tool just dump unix socket packets and by itself it cannot be directly used to solve a production issue unless post analysis with the dump data. I am inclined to put this tool under examples so other people can extend it as necessary to help resolve their own use cases. WDYT? BTW, the code has some misalignment and empty lines, maybe you want to clean them up as well. Thanks!

**Comment by Rtoax** [comment]
> The commit message should explain why this tool is useful, what problems it could solve.
> 
> Dumping raw bytes does not make sense to me.
> In production, we often use gRPC + protobuf over UDS, so it might be helpful to allow user decode those raw bytes in a specific encoding.
> 
> BTW, I would suggest you invest this effort to libbpf-based tool.

Thanks, i'll try it

**Comment by Rtoax** [comment]
> This tool just dump unix socket packets and by itself it cannot be directly used to solve a production issue unless post analysis with the dump data. I am inclined to put this tool under examples so other people can extend it as necessary to help resolve their own use cases. WDYT? BTW, the code has some misalignment and empty lines, maybe you want to clean them up as well. Thanks!

Thanks, i try https://github.com/iovisor/bcc/pull/3615

**Comment by davemarchevsky** [comment]
Closing in favor of #3615

**Pull request closed without merging**
