### PR TITLE
Add MAINTAINERS file with list of code owners

### PR DESCRIPTION
**Pull request by drzaeus77**
Signed-off-by: Brenden Blanco <bblanco@gmail.com>

### CODE REVIEW

**Comment by goldshtn** [comment]
I think you want to use (CODEOWNERS)[https://help.github.com/articles/about-codeowners/]  so that the GitHub web UI assigns the reviewers automatically.

**Comment by drzaeus77** [comment]
Thanks, will give this a try.

**Comment by pchaigno** [comment]
It just assigned everyone to #1308 and I only changed `src/cc/` and `tests/`. I'm guessing this is happening because of the misc. entry...?

**Comment by drzaeus77** [comment]
Yup. Let's add a /tests/ entry to prune it down a bit.

**Pull request merged**
