### PR TITLE
[Don't merge] Testing whether removal of HAVE_SDT_HEADER ifdefs causes tests on some platforms to break on its own 

### PR DESCRIPTION
**Pull request by davemarchevsky**
Yonghong and I were talking offline about [my other PR](https://github.com/iovisor/bcc/pull/2324). I'm starting to think that some of the weird test failures we're seeing on that PR are due to the removal of the `HAVE_SDT_HEADER` gate instead of the numerous other code changes.

Just pushing this up so that it can run on iovisor test infra. Nothing to see here.

/cc @yonghong-song

### CODE REVIEW

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
ubuntu 17.10 and 18.04 failed with the same reason
```
3: /home/iovisor/jenkins/workspace/bcc-pr/label/ubuntu1710/tests/cc/test_usdt_probes.cc:37
3: ...............................................................................
3: 
3: /home/iovisor/jenkins/workspace/bcc-pr/label/ubuntu1710/tests/cc/test_usdt_probes.cc:45: FAILED:
3:   REQUIRE( probe->in_shared_object(probe->bin_path()) == false )
3: with expansion:
3:   true == false
```

**Comment by davemarchevsky** [comment]
I think this might be because `in_shared_object` ends up [checking whether elf type == `ET_DYN`](https://github.com/iovisor/bcc/blob/master/src/cc/bcc_elf.c#L674-L676) and perhaps the relatively newer Ubuntus [compile binaries as PIEs by default](https://wiki.ubuntu.com/SecurityTeam/PIE), so we end up having `ET_DYN` binaries that aren't meant to be used as shared libs?

**Comment by palmtenor** [comment]
Well, I think PIE executable is more or less the same as shared object, that you can't really use USDT in it without PID right?

**Comment by yonghong-song** [comment]
Tried a simple example,
```
-bash-4.4$ cat t.c
int g;
int main()  { return g; }
-bash-4.4$ gcc -pie t.c
-bash-4.4$ readelf -a a.out                                                                                                          
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x550
  Start of program headers:          64 (bytes into file)
  Start of section headers:          6664 (bytes into file)
....
```
it does look like if compiled with -pie, the binary did have
```
  Type:                              DYN (Shared object file)
```

With the type DYN, bcc really does not know this is a truely binary or a shared library. 
We could check function `_start` since typically it is the starting point of the function, but it still looks like hacky.

We will need to find a solution for this. Otherwise, usdt won't work properly on ubuntu 17.04 and later.

For this particular test, we can temporarily fix it by returning success if the binary is considered as a shared library.

**Comment by yonghong-song** [comment]
okay, let us run the test with some debug info.

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
I just installed ubuntu 18.04 and compiled with test_libcc.
The following is `readelf -a test_libbcc` header
```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x948490
  Start of program headers:          64 (bytes into file)
  Start of section headers:          81326576 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         38
  Section header string table index: 37
```
So, yes, it is marked as a DYN.

**Comment by davemarchevsky** [comment]
> For this particular test, we can temporarily fix it by returning success if the binary is considered as a shared library.

I will modify the test to do this (and remove debug print). If this results in a green test run, I'll make similar changes on the other PR and see what state that brings it to.

**Comment by davemarchevsky** [comment]
@yonghong-song You already confirmed this two ways, but here's a 3rd from test output:

```
3: DAVEMARCHEVSKY: elf type of /home/iovisor/jenkins/workspace/bcc-pr/label/ubuntu1804/build/tests/cc/test_libbcc is 3
```

Glad we got to the bottom of this!

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Pull request closed without merging**
