### PR TITLE
cmake: expose bcc_elf.h in the API headers

### PR DESCRIPTION
**Pull request by mmarchini**
Ref: https://github.com/iovisor/bpftrace/pull/410

### CODE REVIEW

**Comment by yonghong-song** [comment]
@palmtenor You used to have some concerns to expose this header. Could you elaborate?
@mmarchini Which exact functions you try to use from bcc_elf.h?

**Comment by mmarchini** [comment]
`bcc_elf_foreach_sym`, we want to use it on bpftrace to get available uprobes from a binary without using `objdump`.

**Comment by palmtenor** [comment]
[buildbot, ok to test]

**Comment by palmtenor** [comment]
I remember last time it was `syms.h` which was explicitly designed not to be exposed. I think `bcc_elf.h` is OK...

**Pull request merged**
