### PR TITLE
filetop.py: precise reads count

### PR DESCRIPTION
**Pull request by 201341**
I try to solve the problem that issue #2360 talked about.  I use the `loff_t *pos` to record the read mounts rather than `size_t count`.  It has more precise value.

### CODE REVIEW

**Comment by brendangregg** [comment]
Just so I understand the key issue: to stop using the junk past \0 in the key, the fix was just to switch from bpf_probe_read() to bpf_probe_read_str(), right?

**Comment by brendangregg** [comment]
[buildbot, ok to test]

**Comment by 201341** [comment]
Yes. It is, And another issue is that the `count` is not the actual read size, but the buffer size.

**Comment by yonghong-song** [comment]
ubuntu 16.04 (4.4 kernel failed). Could you annotate `test_tools_smoke.py` `test_filetop` with kernel requirement `>= 4.11`?

**Comment by yonghong-song** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
@201341 Just ping, did you get time to fix the test issue?

**Comment by yonghong-song** [comment]
@201341 there are merge conflicts. could you rebase and resubmit? BTW, all tests passed.

**Comment by 201341** [comment]
@yonghong-song hi, I am not familiar with the comman `git rebase`, and spend some time to leran it online, I'm not sure whether it is ok to solve the merge conflicts.

**Comment by yonghong-song** [comment]
To make it easy to resolve conflicts, at your local branch, you squash all your commits into one. Rebase on top of the master. You can close this commit and resubmit a new pull request.
Thanks.

**Pull request closed without merging**
