### PR TITLE
Enable python3 compatible strings in biosnoop

### PR DESCRIPTION
**Pull request by drzaeus77**
Fixes: #431 
Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>

### CODE REVIEW

**Comment by 4ast** [comment]
lgtm

**Comment by brendangregg** [comment]
The change is ok, but I don't understand the logic. If the task name does not contain '?', then trust the sector value? What case was this for? //cc @mcaleavya

**Comment by mcaleavya** [comment]
By looking at the original I took this to mean we didn't find a request lookup for the task name, we print ?

    if (valp == 0) {

        bpf_trace_printk("0 0 ? %d\\n", req->__data_len);

I added a strcpy to populate the ? as I was using a string for the task name in my struct. It may be best to remove the strcpy, but at the moment I am not sure how many times now we hit the missing of the task name now it's no longer using the printk.

**Comment by brendangregg** [comment]
oh, right, thanks, I was using '?' to mean "start not seen". I was thrown by the re.match() thinking it was looking for ? elsewhere in the string, and I was wondering what kernel daemon / process that could be.

Later on we might want to make that a direct comparison (event.name != "?"), as well as renaming "val = event.sector" to be "nr_sector = ...". But we can do that later.

**Pull request merged**
