### PR TITLE
Add some XFS read/write kprobes.

### PR DESCRIPTION
**Pull request by Rtoax**
There are lots of read/write kprobes:

```
kprobe:xfs_file_buffered_read
kprobe:xfs_file_buffered_write
kprobe:xfs_file_dax_read
kprobe:xfs_file_dax_write
kprobe:xfs_file_dio_read
kprobe:xfs_file_dio_write_aligned
kprobe:xfs_file_dio_write_unaligned
kprobe:xfs_file_open
kprobe:xfs_file_read_iter
kprobe:xfs_file_readdir
kprobe:xfs_file_write_iter
```

### CODE REVIEW

**Comment by davemarchevsky** [comment]
IIUC, `xfs_file_buffered_{read,write}` probes have always existed, while the others may or may not exist depending on version. Is there some commit where these probes were added?

**Comment by Rtoax** [comment]
> IIUC, `xfs_file_buffered_{read,write}` probes have always existed, while the others may or may not exist depending on version. Is there some commit where these probes were added?

The following three commit in linux kernel:

```
xfs_file_dio_write_{aligned, unaligned}
	Commit: caa89dbc4303d9bc7caa6c1124a84aa3efa47e00
	Date:   Sat Jan 23 10:06:30 2021 -0800
	xfs: split the unaligned DIO write code out

xfs_file_dio_{read,write}
	Commit: ee1b218b09560982010e4dfffa8f9d4f05f62220
	Date:   Sat Jan 23 10:06:28 2021 -0800
	xfs: cleanup the read/write helper naming

xfs_file_dax_{read,write}
	Commit: 16d4d43595b4780daac8fcea6d042689124cb094
	Date:   Wed Jul 20 11:38:55 2016 +1000
	xfs: split direct I/O and DAX path
```

**Comment by chenhengqi** [comment]
I am afraid that this change is incorrect.

https://github.com/torvalds/linux/blob/30306f6194cadcc29c77f6ddcd416a75bf5c0232/fs/xfs/xfs_file.c#L276-L300

xfs_file_dax_read/xfs_file_dio_read/xfs_file_buffered_read are triggered by xfs_file_read_iter.

Actually, we should trace the read entrypoint only.

https://github.com/torvalds/linux/blob/30306f6194cadcc29c77f6ddcd416a75bf5c0232/fs/xfs/xfs_file.c#L1407-L1427

**Comment by Rtoax** [comment]
> I am afraid that this change is incorrect.
> 
> https://github.com/torvalds/linux/blob/30306f6194cadcc29c77f6ddcd416a75bf5c0232/fs/xfs/xfs_file.c#L276-L300
> 
> xfs_file_dax_read/xfs_file_dio_read/xfs_file_buffered_read are triggered by xfs_file_read_iter.
> 
> Actually, we should trace the read entrypoint only.
> 
> https://github.com/torvalds/linux/blob/30306f6194cadcc29c77f6ddcd416a75bf5c0232/fs/xfs/xfs_file.c#L1407-L1427

Thanks, you are right.

**Pull request closed without merging**
